table Formules
	lineageTag: 2ec12701-ca58-4b8c-87cd-1cf280314a9d
	sourceLineageTag: 132c8c98-06b5-4f03-8cc5-f2b2756e37df

	measure Orderbedrag = EXTERNALMEASURE("Orderbedrag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Eenmalige orders
		lineageTag: 4fa21c0a-269b-409d-8024-420ae254cae2
		sourceLineageTag: a997a8d9-0594-48bb-90d5-6758cdc07d7d
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs' = EXTERNALMEASURE("Definitieve kostprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: ec5e9253-2b37-44d7-b02f-0a13900eadbb
		sourceLineageTag: e95ccf65-a682-4e58-990f-f32de8f0d2d1
		dataCategory: Uncategorized

	measure 'Onverwerkte verrekenprijs' = EXTERNALMEASURE("Onverwerkte verrekenprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 5d258c1c-57ae-4c0b-aa6e-c80b72c4983e
		sourceLineageTag: e9e0655d-9594-418e-a3bc-8f71609c7c20
		dataCategory: Uncategorized

	measure 'Totaal kosten (verrekenprijs onverwerkt, kostprijs definitief)' = EXTERNALMEASURE("Totaal kosten (verrekenprijs onverwerkt, kostprijs definitief)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: b1f82fb4-8241-49f7-9a4f-cde2ebc2f74c
		sourceLineageTag: f42bf801-7573-45fc-a04c-4d7345725b4b
		dataCategory: Uncategorized

	measure 'Project omzet' = EXTERNALMEASURE("Project omzet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 1a93090b-f003-439d-8bfe-532335b7a284
		sourceLineageTag: cde9f6ba-e501-46be-90b1-c30da51e4422
		dataCategory: Uncategorized

	measure 'Projectgebonden uren' = EXTERNALMEASURE("Projectgebonden uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: b1e7810c-819e-4660-93c9-30e8f8256899
		sourceLineageTag: 8f04ce8d-7d79-4f31-9bbe-51c17409571f
		dataCategory: Uncategorized

	measure 'Montage uren' = EXTERNALMEASURE("Montage uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 182740a7-dcc0-473e-885d-d58ad8426151
		sourceLineageTag: acbc2b1e-762d-4782-b9fd-f4c9c12c89da
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs arbeid' = EXTERNALMEASURE("Definitieve kostprijs arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 408e79b1-8ea9-4082-b29e-bad11209c6fb
		sourceLineageTag: ac39d2c3-e057-43cd-9862-bd36d440cb0f
		dataCategory: Uncategorized

	measure 'Projectgebonden uren NOT BLANK' = EXTERNALMEASURE("Projectgebonden uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: ee1467c5-a4b7-45e7-8282-eee560dec06e
		sourceLineageTag: edd55f89-8c05-4c28-a759-df0150358d8b
		dataCategory: Uncategorized

	measure 'Totale kosten cum. (verrekenprijs onverwerkt, kostprijs definitief)' = EXTERNALMEASURE("Totale kosten cum. (verrekenprijs onverwerkt, kostprijs definitief)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: f1c9154c-7f34-4e9c-a9f6-7f8de253c81f
		sourceLineageTag: b0da1698-ef97-4cf8-8b4e-266fcd19063b
		dataCategory: Uncategorized

	measure 'Project omzet cum.' = EXTERNALMEASURE("Project omzet cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 4a611b5d-4ced-4a40-ac55-025af27d4af5
		sourceLineageTag: 47c64bb0-a66f-41aa-9f63-d9fea883d6f6
		dataCategory: Uncategorized

	measure 'Orderbedrag Niet gefactureerd' = EXTERNALMEASURE("Orderbedrag Niet gefactureerd", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Eenmalige orders
		lineageTag: b6126526-8110-466b-9da6-41f3a3b81292
		sourceLineageTag: cbd7900b-69a1-4a5c-b962-d283da599f7b
		dataCategory: Uncategorized

	measure 'Project resultaat' = EXTERNALMEASURE("Project resultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 557f0308-3a19-4de8-a814-86721fd373b7
		sourceLineageTag: 1cd7744f-7157-4af4-9fa1-a901fdd62d2c
		dataCategory: Uncategorized

	measure 'Project marge' = EXTERNALMEASURE("Project marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 2e68ed4e-eb14-4d0d-aca5-06f4a71693b5
		sourceLineageTag: 09791130-68cb-4a40-9fc8-746d79175c45
		dataCategory: Uncategorized

	measure 'Montage uren cumulatief' = EXTERNALMEASURE("Montage uren cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 3fbca219-10c4-43fa-89a5-88efa0c33235
		sourceLineageTag: d71ae32a-c88b-461d-90c6-c680cd69044d
		dataCategory: Uncategorized

	measure 'Projectgebonden uren cumulatief' = EXTERNALMEASURE("Projectgebonden uren cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: dc52fb7c-62d6-4f2a-bfac-75aded349811
		sourceLineageTag: 99890de5-4355-49a7-8ab4-4be141b6a330
		dataCategory: Uncategorized

	measure 'Hoofdproject Einddatum' = EXTERNALMEASURE("Hoofdproject Einddatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: Short Date
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 260bec0c-5b1a-4d01-9368-c5de8690cfd6
		sourceLineageTag: 35b7fefb-8adf-44e4-9703-9208a8a94ce2
		dataCategory: Uncategorized

	measure 'Hoofdproject Startdatum' = EXTERNALMEASURE("Hoofdproject Startdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: Short Date
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 3bdae4e6-e90d-4f54-9728-30454fda142c
		sourceLineageTag: ee77300a-5290-4b70-aafc-6505ffdcff5f
		dataCategory: Uncategorized

	measure 'Eerste boekdatum' = EXTERNALMEASURE("Eerste boekdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: General Number
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 564a7931-69b5-4b3d-9820-ec3f68c0086d
		sourceLineageTag: fd87e42d-fd71-4cbb-a809-521d0277b3da
		dataCategory: Uncategorized

	measure 'Laatste boekdatum' = EXTERNALMEASURE("Laatste boekdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 5f384503-ff4b-4635-8fc4-5ec7a7a9183a
		sourceLineageTag: b4d44f48-6ba4-4cf9-9bf6-af6f8b0e5866
		dataCategory: Uncategorized

	measure projectduur = EXTERNALMEASURE("projectduur", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 852eae51-79f0-4937-b4bc-97678de09853
		sourceLineageTag: f3490cc5-f55c-4c8e-b853-412bf7e6f936
		dataCategory: Uncategorized

	measure 'Werkelijke duur %' = EXTERNALMEASURE("Werkelijke duur %", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 7122ec02-36fd-4032-b18b-22f81434ee2f
		sourceLineageTag: 5899eca3-83d3-4bd4-be28-b8c31d8a6205
		dataCategory: Uncategorized

	measure 'Werkelijke duur' = EXTERNALMEASURE("Werkelijke duur", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: c98cdc64-ce32-43c9-8387-520e4b30432b
		sourceLineageTag: e2d31057-4aa7-47f5-9939-eb44125c6ef3
		dataCategory: Uncategorized

	measure 'Onverwerkte verrekenprijs inkoop' = EXTERNALMEASURE("Onverwerkte verrekenprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: cb47da51-3380-4db2-9c02-d3412cf8c013
		sourceLineageTag: 40a80c7d-a85f-49ea-9f69-5b5938bf1364
		dataCategory: Uncategorized

	measure 'Totale uren cumulatief' = EXTERNALMEASURE("Totale uren cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: af263785-6549-49bd-9c7a-34863f85d846
		sourceLineageTag: cf7a938f-3079-4761-b3d5-e0c2a1190241
		dataCategory: Uncategorized

	measure 'Nog te facturen (te laat)' = EXTERNALMEASURE("Nog te facturen (te laat)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 0bfe92ae-c307-453b-859e-6799b6c2538d
		sourceLineageTag: df90d4e0-f2e9-4f86-991c-9fc3b5365810
		dataCategory: Uncategorized

	measure 'Nog te factureren (komende 7 dagen)' = EXTERNALMEASURE("Nog te factureren (komende 7 dagen)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: da1b705e-0b2c-448b-8a27-aef8131794fd
		sourceLineageTag: e1120d37-b208-4cff-aeb3-052f0028cc69
		dataCategory: Uncategorized

	measure 'Nog te factureren (toekomstig)' = EXTERNALMEASURE("Nog te factureren (toekomstig)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 17f6b0bd-9225-41c6-a710-05a4a3560cc2
		sourceLineageTag: 4124e7e8-57e3-45e5-8887-f53e9591a534
		dataCategory: Uncategorized

	measure 'Onverwerkte opbrengstregels via orders' = EXTERNALMEASURE("Onverwerkte opbrengstregels via orders", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 4949a04e-31c8-4af1-88bc-5a3c37ea563e
		sourceLineageTag: f3699601-2f58-4fac-a042-88971dff26f0
		dataCategory: Uncategorized

	measure 'Prognose factureerdatum' = EXTERNALMEASURE("Prognose factureerdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten
		lineageTag: 8b7e4a65-af33-4953-b939-d712a2efaf58
		sourceLineageTag: d007e22c-63eb-4481-bb4c-41d7441fe553
		dataCategory: Uncategorized

	measure 'Nog te factureren - Totaal' = EXTERNALMEASURE("Nog te factureren - Totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 9173f5db-c9e2-43eb-a927-e6245e73506c
		sourceLineageTag: 31cef3da-3695-4ff9-86a0-a6ea23fad2ac
		dataCategory: Uncategorized

	measure 'Onverwerkte opbrengstregels' = EXTERNALMEASURE("Onverwerkte opbrengstregels", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: cd6c3d8a-e7bc-49e4-b62e-5fda25ec93fd
		sourceLineageTag: b2a69683-32f5-48f2-9f9e-5e8b323179f2
		dataCategory: Uncategorized

	measure 'Geselecteerd hoofdproject' = EXTERNALMEASURE("Geselecteerd hoofdproject", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 176c4fd2-f385-418e-a51b-fabf1ae11d32
		sourceLineageTag: 75aeeb6c-77bc-48fe-bb1f-19bf3a164658
		dataCategory: Uncategorized

	measure 'Project resultaat incl. kosten in bestelling' = EXTERNALMEASURE("Project resultaat incl. kosten in bestelling", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 3c6ba9da-7c59-47ee-841a-f904313b53e8
		sourceLineageTag: 9e46727d-4eb0-4f9f-b26e-c505797be02f
		dataCategory: Uncategorized

	measure 'Huidige gebruiker' = EXTERNALMEASURE("Huidige gebruiker", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: c40be581-8864-4e1a-a3c6-79668a704c9d
		sourceLineageTag: 7f6e5613-6643-452d-8878-050cb65c3d1b
		dataCategory: Uncategorized

	measure 'Calculatie montage uren' = EXTERNALMEASURE("Calculatie montage uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 0f13dc3d-5aa0-4b37-b8e2-946e0e92cb5e
		sourceLineageTag: a6d8f990-93b8-4abd-9c4e-84f60792d4ed
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs inkoop' = EXTERNALMEASURE("Calculatie kostprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 6ba4c9ca-89fa-4080-a419-f0c976a20e8c
		sourceLineageTag: 9e1bae4a-c154-4eee-abd0-2f51d703c8d2
		dataCategory: Uncategorized

	measure 'Calculatie montage uren NOT BLANK' = EXTERNALMEASURE("Calculatie montage uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: b0c1087a-5481-4eda-a563-8598a5fa6e01
		sourceLineageTag: c6f97cc1-f19b-4c3e-aa60-165c9ba7972b
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs inkoop NOT BLANK' = EXTERNALMEASURE("Calculatie kostprijs inkoop NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 13e16274-4f7f-4925-8751-9e9a5b37c0c0
		sourceLineageTag: bb8355fe-a00a-4328-9db8-3e24d904f219
		dataCategory: Uncategorized

	measure 'verrekenprijs inkoop NOT BLANK' = EXTERNALMEASURE("verrekenprijs inkoop NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: cfd9163c-5dc4-41ae-96fb-8096ea635a6f
		sourceLineageTag: 3fcead88-d3d7-4a07-b18a-60033b154464
		dataCategory: Uncategorized

	measure 'kostprijs inkoop NOT BLANK' = EXTERNALMEASURE("kostprijs inkoop NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 2aced5e3-a9ca-433a-8e5c-aed5683daa91
		sourceLineageTag: 7b3720fb-e2c0-435b-a8a0-22031eaae464
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs inkoop' = EXTERNALMEASURE("Definitieve kostprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 0bfbbc65-975e-479d-929e-18f6638bf9de
		sourceLineageTag: 3fdca52c-063d-4b83-9ccf-1f16f1ae8d5f
		dataCategory: Uncategorized

	measure 'Totale kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)' = EXTERNALMEASURE("Totale kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 28fa6bc1-b3d7-4907-9308-d013e780d901
		sourceLineageTag: 21f7371d-1437-4021-8e4d-b757df3509a1
		dataCategory: Uncategorized

	measure 'Totale kosten inkoop cum. (verrekenprijs onverwerkt, kostprijs definitief)' = EXTERNALMEASURE("Totale kosten inkoop cum. (verrekenprijs onverwerkt, kostprijs definitief)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: b8623fc1-8380-440f-aa10-978c2d3a00c3
		sourceLineageTag: 73253507-3c62-411a-a39c-cf0f35e96725
		dataCategory: Uncategorized

	measure 'Calculatie projectgebonden uren cum.' = EXTERNALMEASURE("Calculatie projectgebonden uren cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: fad1a325-f336-4b03-8f09-cdb185fb93f4
		sourceLineageTag: 19c707fc-ccf6-4eae-99c3-664310b5bfdc
		dataCategory: Uncategorized

	measure Projectfase = EXTERNALMEASURE("Projectfase", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 705b1989-1241-49a9-94fa-6d6826f30051
		sourceLineageTag: 96dd70a5-349d-401d-8620-8b814b230842
		dataCategory: Uncategorized

	measure Projectstatus = EXTERNALMEASURE("Projectstatus", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 5224d979-751c-48fd-93da-b759512287c6
		sourceLineageTag: 639dbd40-97c9-42fb-97f7-b408fc34f0b4
		dataCategory: Uncategorized

	measure Factureerwijze = EXTERNALMEASURE("Factureerwijze", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 453d0a9b-905f-4f32-896e-ff2903a391d4
		sourceLineageTag: 3fc1f83b-476f-4bfb-94d5-f81f1fb16ad8
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs NOT BLANK' = EXTERNALMEASURE("Calculatie kostprijs NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 84502286-00d4-4653-bffc-2f06887026b4
		sourceLineageTag: dce312d0-dbba-4005-aefa-8047b85f1fb4
		dataCategory: Uncategorized

	measure 'Calculatie projectgebonden uren NOT BLANK' = EXTERNALMEASURE("Calculatie projectgebonden uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 3d653e2b-9e32-4c7e-8a2a-eeff2971da96
		sourceLineageTag: d3a62e90-6245-4095-83cc-8418b6418942
		dataCategory: Uncategorized

	measure 'Gerealiseerde marge incl ontverwerkte kosten' = EXTERNALMEASURE("Gerealiseerde marge incl ontverwerkte kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 1b3dce0f-6264-4b48-915e-20164494fe3c
		sourceLineageTag: cbab520e-4aee-4bc2-b46a-5a0f8311afd2
		dataCategory: Uncategorized

	measure 'Budget resultaat' = EXTERNALMEASURE("Budget resultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: fba2f423-6fcd-4774-b177-4cbacd83f82d
		sourceLineageTag: dbfbdc94-afc8-4549-8c7e-1b358d9426c0
		dataCategory: Uncategorized

	measure 'Budget marge' = EXTERNALMEASURE("Budget marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: b384fa6f-b91e-4010-87d5-ed0d1b769b0e
		sourceLineageTag: a4419566-dd28-4bf0-b1c1-45a6a774c7d1
		dataCategory: Uncategorized

	measure logo = EXTERNALMEASURE("logo", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 2281876d-e20d-4f7e-a456-0620a75b9080
		sourceLineageTag: 94f5c2ee-e82b-4419-b3da-72370a715086
		dataCategory: ImageUrl

	measure 'Verschil calculatie - realisatie' = EXTERNALMEASURE("Verschil calculatie - realisatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 6441500a-692c-48a8-97ef-8f0dc64f9332
		sourceLineageTag: 4d98fb0f-dbd8-45a2-945f-31bcfd3f5c21
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren' = EXTERNALMEASURE("Gerealiseerde uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: e7f47e8f-0e2d-42e7-9b14-d04a9157f9ef
		sourceLineageTag: 2c672eff-7b39-4d5d-bfdb-7c28c50ae057
		dataCategory: Uncategorized

	measure 'Calculatie uren' = EXTERNALMEASURE("Calculatie uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 89729ca4-9e12-4005-ba0e-9243eccbefd5
		sourceLineageTag: 4359d2e4-7955-4ce8-9896-1698b11c8c73
		dataCategory: Uncategorized

	measure 'Verschil calculatie - realisatie uren' = EXTERNALMEASURE("Verschil calculatie - realisatie uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 2cf6ec04-812d-41bf-bfd3-cc48655d398c
		sourceLineageTag: b0539089-0c0f-4220-9676-f86ed5b91423
		dataCategory: Uncategorized

	measure Debet = EXTERNALMEASURE("Debet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual
		lineageTag: 756f2ca4-6973-4d4e-8583-1911d334a88a
		sourceLineageTag: a70b3f0e-ca95-4c18-bb4b-ccc1d4ea8f2c
		dataCategory: Uncategorized

	measure Credit = EXTERNALMEASURE("Credit", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual
		lineageTag: 46f219ac-df0c-4dbb-b55b-519dd07aafb3
		sourceLineageTag: 2010f667-2b8c-4d8e-82ed-3da523bc1c78
		dataCategory: Uncategorized

	measure 'Verzoek Kosten' = EXTERNALMEASURE("Verzoek Kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 6c9b0376-19dc-4629-8243-0291bb151972
		sourceLineageTag: 18214e60-b663-4452-af90-b4890c73a317
		dataCategory: Uncategorized

	measure 'Verzoek omzet' = EXTERNALMEASURE("Verzoek omzet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: e9cf7387-f4f8-409b-82c4-f0888fe2192c
		sourceLineageTag: d945b2e6-2582-478e-a40b-c5a52dfd7a8b
		dataCategory: Uncategorized

	measure 'Verzoek projectgebonden uren' = EXTERNALMEASURE("Verzoek projectgebonden uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 2669bede-47b9-48fc-8e92-91b5073297c4
		sourceLineageTag: 4dfb3220-42d4-477a-8f49-7a0e2d540593
		dataCategory: Uncategorized

	measure 'Verzoek projectgebonden uren NOT BLANK' = EXTERNALMEASURE("Verzoek projectgebonden uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 86c6c583-a20a-422b-8027-81003f77299c
		sourceLineageTag: 8fce42c0-43e0-4cc4-b6c7-5f8a9830eec0
		dataCategory: Uncategorized

	measure 'Verzoek uren' = EXTERNALMEASURE("Verzoek uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: bdf71a7b-97ec-4ac2-8ac4-97190005f3db
		sourceLineageTag: 5ee7897b-dc13-4717-a1e3-bed971f48ef1
		dataCategory: Uncategorized

	measure 'Verzoek montage uren' = EXTERNALMEASURE("Verzoek montage uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: c50e59a2-f5e4-403d-84c2-107b94fe3da3
		sourceLineageTag: cfff558f-6627-4128-a2c6-6a1287d5a966
		dataCategory: Uncategorized

	measure 'Verzoek montage uren NOT BLANK' = EXTERNALMEASURE("Verzoek montage uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: c87cea1a-ea07-48f9-b8c2-935e924da964
		sourceLineageTag: b38610ea-9113-409b-89e3-5d80274504a1
		dataCategory: Uncategorized

	measure 'Prognose kostprijs o.b.v. methode wachte marge' = EXTERNALMEASURE("Prognose kostprijs o.b.v. methode wachte marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: 6bf8bc7f-0ff6-490a-a1ea-a23fc2c27205
		sourceLineageTag: 2cd77dac-0b3d-4b9e-aa26-9352bba8a066
		dataCategory: Uncategorized

	measure 'Prognose omzet o.b.v. methode verwachte marge' = EXTERNALMEASURE("Prognose omzet o.b.v. methode verwachte marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: bdfbbb9f-4ce2-4760-b401-ad4df84c82a1
		sourceLineageTag: d726e874-9fc3-43f7-a80b-8165188d75a8
		dataCategory: Uncategorized

	measure 'Prognose projectgebonden uren' = EXTERNALMEASURE("Prognose projectgebonden uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 1a54ceb5-5017-4171-91dd-12cd15f20bf1
		sourceLineageTag: c5209886-60fb-4f21-8e00-7ad6ebc40b55
		dataCategory: Uncategorized

	measure 'Prognose montage uren' = EXTERNALMEASURE("Prognose montage uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 3b7eb904-3994-484b-9417-c867c2dad6f0
		sourceLineageTag: 1f5a49cb-5ae2-4f00-b860-588b20cb47f9
		dataCategory: Uncategorized

	measure 'Prognose projectbebonden uren NOT BLANK' = EXTERNALMEASURE("Prognose projectbebonden uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: a86102ee-b155-4acc-ab9e-051687ee169c
		sourceLineageTag: be6afa59-b0f3-45b6-af13-81e576029f61
		dataCategory: Uncategorized

	measure 'Prognose montage uren NOT BLANK' = EXTERNALMEASURE("Prognose montage uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 165ee001-22b8-4c1e-8227-818509ea4731
		sourceLineageTag: fb1bebbb-0a18-4bfa-b18e-187b52477746
		dataCategory: Uncategorized

	measure 'Prognose kostprijs o.b.v. methode wachte marge NOT BLANK' = EXTERNALMEASURE("Prognose kostprijs o.b.v. methode wachte marge NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: c2f27fd1-9542-4d80-baff-aadd3c97069e
		sourceLineageTag: a9cbdc33-fa1d-481e-9fca-483775ef4e8f
		dataCategory: Uncategorized

	measure 'Prognose omzet o.b.v. methode verwachte marge NOT BLANK' = EXTERNALMEASURE("Prognose omzet o.b.v. methode verwachte marge NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: 900eaa2a-6252-4d5b-96e3-a52996cdf0e2
		sourceLineageTag: 48d7e61a-9033-4201-94ca-9a1b4fcba689
		dataCategory: Uncategorized

	measure 'Prognose resultaat' = EXTERNALMEASURE("Prognose resultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: 463c0a71-b3e8-43ca-97f0-4df4fc0aecfc
		sourceLineageTag: 691385fe-603e-411c-b102-bd2c24b2208f
		dataCategory: Uncategorized

	measure 'Prognose marge' = EXTERNALMEASURE("Prognose marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: 4d59da69-b361-4cdd-acd4-a9b6fa2bc8e7
		sourceLineageTag: 3d442699-fe3b-4418-87ff-f55cc9679571
		dataCategory: Uncategorized

	measure 'Aantal budgetverzoeken' = EXTERNALMEASURE("Aantal budgetverzoeken", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 6ccb7241-e66a-44e8-8395-9e8353f797a6
		sourceLineageTag: e833ee39-2196-498b-9a62-1c3910972cc9
		dataCategory: Uncategorized

	measure 'Budget handhaven' = EXTERNALMEASURE("Budget handhaven", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 0fff063b-1254-4b5b-9c36-df698f0b7b65
		sourceLineageTag: 17bda61c-6c2b-45c2-a427-174afb82bd2c
		dataCategory: Uncategorized

	measure 'melding 1 hoofdproject selecteren' = EXTERNALMEASURE("melding 1 hoofdproject selecteren", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 932171b4-e9be-4691-b54c-15f525f53e85
		sourceLineageTag: 5a1f122f-db7c-4f91-91ad-b74e1a0825f2
		dataCategory: Uncategorized

	measure 'Aantal budgetverzoeken voor handhaven budget' = EXTERNALMEASURE("Aantal budgetverzoeken voor handhaven budget", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: cbb31fd6-f94c-48a9-8ffa-49883fc0be06
		sourceLineageTag: e70b96b5-dea1-4d42-ba53-b298bc521447
		dataCategory: Uncategorized

	measure 'Ouderdom laatste budgetverzoek' = EXTERNALMEASURE("Ouderdom laatste budgetverzoek", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 4dc74164-7797-4dae-9ee2-f36421379adf
		sourceLineageTag: 1a793289-700f-44c0-b4d5-49861156de1f
		dataCategory: Uncategorized

	measure KlantnummerDWH = EXTERNALMEASURE("KlantnummerDWH", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 6111e969-6f33-41dd-a79a-4d29643cdf6d
		sourceLineageTag: 1d039c55-642c-4381-9dbf-18032bde9c14
		dataCategory: Uncategorized

	measure Opdrachtgever = EXTERNALMEASURE("Opdrachtgever", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: b34d380a-e138-457c-8b09-34c363ab3d24
		sourceLineageTag: 41d37ede-308c-4f6d-8e46-717348d3bcdd
		dataCategory: Uncategorized

	measure Projectleider = EXTERNALMEASURE("Projectleider", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 4b35a350-d700-4087-bebd-64e584843e6c
		sourceLineageTag: 89b0f3bf-bc5f-40df-89ee-f963211fce39
		dataCategory: Uncategorized

	measure 'Calculatie verkoopprijs' = EXTERNALMEASURE("Calculatie verkoopprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: bdf884ea-a66b-4ac9-a005-6c3db57342f3
		sourceLineageTag: e17a6648-0c4b-4b1b-a22a-67986d39639e
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op calculatie (TWC)' = EXTERNALMEASURE("Toegevoegde Waarde op calculatie (TWC)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 52fd1cab-94b4-4e99-9027-bdf85203a44f
		sourceLineageTag: e1372a35-b275-45e1-ad48-15359574bd95
		dataCategory: Uncategorized

	measure 'Calculatie verrekenprijs exclusief arbeid' = EXTERNALMEASURE("Calculatie verrekenprijs exclusief arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: e96e98a2-9b5f-4d0c-a020-00051e6dc184
		sourceLineageTag: c7182406-d5e3-49de-b750-d02ba0531d45
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op calculatie per uur (TWC\u)' = EXTERNALMEASURE("Toegevoegde Waarde op calculatie per uur (TWC\u)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: ba93ba06-f9d0-4772-b3dc-4cf69d55faae
		sourceLineageTag: 686e0d33-3136-43a8-8fb0-77af6568a1ed
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op Realisatie (TWR)' = EXTERNALMEASURE("Toegevoegde Waarde op Realisatie (TWR)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 99930d64-346f-4f25-872a-85bfb77c8a62
		sourceLineageTag: 5d5587ed-b1e6-4b5a-a223-5dc1defc3cb5
		dataCategory: Uncategorized

	measure 'Verrekenprijs exclusief arbeid' = EXTERNALMEASURE("Verrekenprijs exclusief arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 775adc1e-2098-4f25-b83d-a51b6eeb005e
		sourceLineageTag: 6071c65c-a494-43bb-ab6f-3fba28b90ffd
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op realisatie per montage uur (TWR\u, zonder datumfilter)' = EXTERNALMEASURE("Toegevoegde Waarde op realisatie per montage uur (TWR\u, zonder datumfilter)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde\Zonder datumfilter
		lineageTag: cd03a42a-e7a6-4e59-ab03-537595564628
		sourceLineageTag: 5198854c-3e12-4369-963d-7f9467d01fd0
		dataCategory: Uncategorized

	measure 'Aantal actuele hoofdprojecten' = EXTERNALMEASURE("Aantal actuele hoofdprojecten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 4e3682e7-c726-4e10-9732-aad2037d930e
		sourceLineageTag: 985d16d9-f5b9-498b-955c-7912ffa23fe9
		dataCategory: Uncategorized

	measure 'Calculatie montage uren TWC' = EXTERNALMEASURE("Calculatie montage uren TWC", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: f3d3f367-d108-4dba-b826-ab72e643674d
		sourceLineageTag: 5808fd83-1aa7-4d76-864b-d002f520b750
		dataCategory: Uncategorized

	measure 'Calculatie omzet' = EXTERNALMEASURE("Calculatie omzet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 358fbb94-7191-447f-9402-2783c7c5e718
		sourceLineageTag: dd5e05f2-f54b-41d5-a005-9d9a22d50603
		dataCategory: Uncategorized

	measure 'Hoofdproject percentage gereed' = EXTERNALMEASURE("Hoofdproject percentage gereed", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 36181b70-ed13-4a88-88aa-0424528f48f2
		sourceLineageTag: ed5a9f33-8b65-4365-80e6-257581d0e34c
		dataCategory: Uncategorized

	measure 'Onverwerkte verrekenprijs arbeid' = EXTERNALMEASURE("Onverwerkte verrekenprijs arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: ee8cb5fb-4cd8-45e4-99de-f823045e10e6
		sourceLineageTag: fab950b3-2275-4529-88ac-f97202356494
		dataCategory: Uncategorized

	measure 'calculatie kostprijs inkoop cum.' = EXTERNALMEASURE("calculatie kostprijs inkoop cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: c7d445cc-6b0e-4a90-b05c-d817996aaf88
		sourceLineageTag: 5ef14144-fd11-4e1c-b2bb-ad2c1d6e34c0
		dataCategory: Uncategorized

	/// Betreft alle creditboekigen op doorbelasting rubrieken van het type "Winst & Verlies". Doorbelasting boekingen zijn niet projectgebonden.
	measure 'Doorbelasting projectkosten' = EXTERNALMEASURE("Doorbelasting projectkosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise
		lineageTag: 81a59b37-9573-4e79-957f-cfe5511f0f2f
		sourceLineageTag: b4c69c7f-9fcf-4c75-82fd-3fd18fbf43ae
		dataCategory: Uncategorized

	/// Betreft alle debetboekigen op doorbelastingrubrieken van het type "Winst & Verlies". Doorbelasting boekingen zijn niet projectgebonden.
	measure 'Doorbelasting projectopbrengsten' = EXTERNALMEASURE("Doorbelasting projectopbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise
		lineageTag: 42aaff9e-4aec-4839-82d3-ce1fc1be9103
		sourceLineageTag: 1b0b1aad-cb38-4b27-b08b-153a9efc4e79
		dataCategory: Uncategorized

	measure 'Melding filter op projecten\meerdere boekjaren' = EXTERNALMEASURE("Melding filter op projecten\meerdere boekjaren", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 226d4d40-9119-47a9-95ff-3748382aefe0
		sourceLineageTag: 61c704a0-9339-4074-ba35-3154bc85bd7e
		dataCategory: Uncategorized

	measure 'filter op projecten' = EXTERNALMEASURE("filter op projecten", INTEGER, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 48bbf48e-f1d4-46cd-acf1-124ebc6702ee
		sourceLineageTag: 71fd464e-57a8-4662-b6f7-a2301113f5e0
		dataCategory: Uncategorized

	measure 'Melding periode YTD' = EXTERNALMEASURE("Melding periode YTD", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 004c45a4-da42-4bde-9425-5e19518bd9b4
		sourceLineageTag: dadbef67-c80e-4314-932b-b33f471e106f
		dataCategory: Uncategorized

	/// Reservering van dekking t.b.v. overhead vanuit projectkosten. Betreft de werkelijke journaalregels; deze hebben geen verwijzing naar projecten.
	measure Dekkingen = EXTERNALMEASURE("Dekkingen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise
		lineageTag: 6b1f6e1a-d822-47b7-9323-ec6e5f6a2604
		sourceLineageTag: 76a10091-158f-4914-a353-9019c170e34e
		dataCategory: Uncategorized

	/// [OHW eindstand]-[OHW beginstand]
	measure 'OHW mutatie in balans' = EXTERNALMEASURE("OHW mutatie in balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 21da2e75-c665-449f-a5e6-fb7c3fa19058
		sourceLineageTag: 2a215832-865e-4893-8ce7-dbfe18db2482
		dataCategory: Uncategorized

	measure 'Definitieve verrekenprijs' = EXTERNALMEASURE("Definitieve verrekenprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 68aa3f0d-837d-477d-97ab-3338ef15c668
		sourceLineageTag: b6032249-0b0a-4628-a9ff-144370cc79fb
		dataCategory: Uncategorized

	/// Telt het aantal unieke Administraties.
	measure 'aantal geselecteerde administraties' = EXTERNALMEASURE("aantal geselecteerde administraties", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: f4189144-7994-4f97-a8e2-438dd0fca546
		sourceLineageTag: 56f96c84-aa6e-40b3-95ed-768226b35fa6
		dataCategory: Uncategorized

	measure 'Verschil opbrengsten' = EXTERNALMEASURE("Verschil opbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\aansluiting hoofd- en subadministratie
		lineageTag: 547fbec7-b0a4-4f2b-91fa-f04e4b8ca073
		sourceLineageTag: e38a53b6-01fc-47be-a1f5-534cf6d262bc
		dataCategory: Uncategorized

	measure 'Verschil kosten' = EXTERNALMEASURE("Verschil kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\aansluiting hoofd- en subadministratie
		lineageTag: a9ec698f-5558-4f6e-8417-6c927a1158df
		sourceLineageTag: 61d562e3-a4ae-420b-89e4-8db5eb769476
		dataCategory: Uncategorized

	measure 'Verschil totaal' = EXTERNALMEASURE("Verschil totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\aansluiting hoofd- en subadministratie
		lineageTag: 08b15560-7bb6-4909-a0e2-f08ff8b9c54b
		sourceLineageTag: 37e33f49-57b8-4093-9d62-35153560f143
		dataCategory: Uncategorized

	/// Doorbelasting van kosten en opbrengsten naar balans.
	measure 'OHW doorbelasting' = EXTERNALMEASURE("OHW doorbelasting", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 96601ecb-ac5b-4db1-a742-bf8b7f3b11d8
		sourceLineageTag: 6fd840ae-d8e1-46ba-a98f-5b0d4cd3974c
		dataCategory: Uncategorized

	measure 'Project resultaat historisch' = EXTERNALMEASURE("Project resultaat historisch", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 10f906f2-1be4-4768-95a5-3c50952b000a
		sourceLineageTag: 1bd811ea-a3d9-4ff6-8b49-58e2aa467446
		dataCategory: Uncategorized

	measure 'Geselecteerde standdatum' = EXTERNALMEASURE("Geselecteerde standdatum", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: fecbfa37-4a9f-4d0a-ac10-dbf65a7aec5e
		sourceLineageTag: 80d990fd-6b89-407d-972e-d41380aaf776
		dataCategory: Uncategorized

	/// [%gefactureerd/budget omzet] - [%NC/ calculatie kosten]. Hiermee kan de voortgang van de facturatie t.o.v. gemaakte kosten worden bepaald. 
	measure 'Voortgang facturatie o.b.v. budget' = EXTERNALMEASURE("Voortgang facturatie o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 558b3efc-d995-4435-b8cd-e6cf675d4c3d
		sourceLineageTag: 2f86aada-eda6-41b8-93be-2787b5fad548
		dataCategory: Uncategorized

	/// [%gefactureerd/prognose omzet] - [%NC/ calculatie kosten]. Hiermee kan de voortgang van de facturatie t.o.v. gemaakte kosten worden bepaald. 
	measure 'Voortgang facturatie o.b.v. prognose' = EXTERNALMEASURE("Voortgang facturatie o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 076289f9-5c70-4b70-98a2-990d2cb2a4b8
		sourceLineageTag: b6020459-c59c-4db7-b015-461b64bc299c
		dataCategory: Uncategorized

	measure 'Budget kostprijs o.b.v. geselecteerde verwachte marge' = EXTERNALMEASURE("Budget kostprijs o.b.v. geselecteerde verwachte marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: 27bcba93-68e8-4a9d-99bb-6138a2b815e4
		sourceLineageTag: 454f572f-94dc-486e-99fb-bef4b278c850
		dataCategory: Uncategorized

	measure 'Budget kostprijs inkoop' = EXTERNALMEASURE("Budget kostprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 82364622-6495-4615-9a6e-a42e337ad820
		sourceLineageTag: d1eb662c-6753-4888-9479-bb7cb20dbc39
		dataCategory: Uncategorized

	measure 'Budget kostprijs inkoop cum.' = EXTERNALMEASURE("Budget kostprijs inkoop cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 8940d098-6798-472a-bc29-eaa712eb4564
		sourceLineageTag: c2e693f9-4ae3-4b6f-bbeb-3edfcac4f917
		dataCategory: Uncategorized

	measure 'Budget montage uren' = EXTERNALMEASURE("Budget montage uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 8dcf6eba-ee06-45ec-941b-e1a6f55e1bb1
		sourceLineageTag: fb0e1547-be96-4f86-bf5c-6f7d5671942d
		dataCategory: Uncategorized

	measure 'Budget montage uren cum.' = EXTERNALMEASURE("Budget montage uren cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 77fff630-14cf-41da-849b-fd1312bc9cd9
		sourceLineageTag: 99e1be49-d511-4bf5-8ed0-65f8d1ca8dd5
		dataCategory: Uncategorized

	measure 'Budget projectgebonden uren' = EXTERNALMEASURE("Budget projectgebonden uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 1863b3b3-cb4c-4852-81e4-dcab60472528
		sourceLineageTag: a630880b-efa7-46f8-b29d-322f2fb74635
		dataCategory: Uncategorized

	measure 'Budget projectgebonden uren cum.' = EXTERNALMEASURE("Budget projectgebonden uren cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: bc99aa85-601e-4b7f-81a1-6407ed7e4cd6
		sourceLineageTag: 1ca62329-6ab0-48a0-a12c-ce8283d95adf
		dataCategory: Uncategorized

	measure 'Budget uren' = EXTERNALMEASURE("Budget uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 1abaf370-ebd0-4d4e-8c1c-891dcd15896a
		sourceLineageTag: 3f7a0aca-5155-440c-9787-8f7ff0f0ed38
		dataCategory: Uncategorized

	measure 'Melding laatste verversdatum/-tijd' = EXTERNALMEASURE("Melding laatste verversdatum/-tijd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: e8a1a94c-edc6-4f83-92de-c0ca8bf0d28f
		sourceLineageTag: 3f008437-8090-4951-8b76-df8aabdbe958
		dataCategory: Uncategorized

	measure 'Project marge historisch' = EXTERNALMEASURE("Project marge historisch", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 9b04084e-f547-46a1-b6df-848874d2c9f0
		sourceLineageTag: 19028d12-acc0-46dc-9711-11acd8bb3c37
		dataCategory: Uncategorized

	measure Projectsoort = EXTERNALMEASURE("Projectsoort", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 9870a3ab-9f44-4637-b6d5-9f77baa85e6f
		sourceLineageTag: 9866cdc5-31fd-4a4c-9e03-38d0718604fc
		dataCategory: Uncategorized

	measure 'Test filter projecten' = EXTERNALMEASURE("Test filter projecten", INTEGER, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 45b9b885-33b9-4a9e-b24a-bccf89d83074
		sourceLineageTag: 59c9b967-1bb3-47f2-8548-84b15dcdcb88
		dataCategory: Uncategorized

	measure 'Service order' = EXTERNALMEASURE("Service order", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Periodieke orders
		lineageTag: 8cef4240-bbe7-47dc-86c8-b54bb7ab5475
		sourceLineageTag: 8e009a92-2011-4a28-ac95-257cec0128e8
		dataCategory: Uncategorized

	measure 'Verzoek Kostprijs (kosten en omzet)' = EXTERNALMEASURE("Verzoek Kostprijs (kosten en omzet)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: b9dd420e-1559-4d5d-8029-4a571ece4719
		sourceLineageTag: c77b778c-484c-4ae0-a440-9984fcb17d60
		dataCategory: Uncategorized

	measure 'Prognose uren' = EXTERNALMEASURE("Prognose uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 26811adb-2aba-4d63-9fe0-05011c7b34f0
		sourceLineageTag: db94bd2e-742a-4b8c-9c53-cf18938f9934
		dataCategory: Uncategorized

	measure 'Prognose uren NOT BLANK' = EXTERNALMEASURE("Prognose uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 43e7131d-ead0-4309-a7c3-ddaa54ef474a
		sourceLineageTag: 09ad1b8a-2d8c-44cb-ab40-5c5a9a8cc275
		dataCategory: Uncategorized

	/// --Omschrijving--
	/// Gerealiseerde uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     [Montage uren]
	///     ,'Geboekte Uren'[Arbeid uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Montage uren historisch' = EXTERNALMEASURE("Montage uren historisch", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: fa55b96b-658f-4803-a5f6-eecd2ff100be
		sourceLineageTag: 90694539-bece-403a-bce5-03d2b9543827
		dataCategory: Uncategorized

	/// --Omschrijving--
	/// Gerealiseerde support uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     [Supporturen]
	///     ,'Geboekte Uren'[Arbeid uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Projectgebonden uren historisch' = EXTERNALMEASURE("Projectgebonden uren historisch", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 82b8e38a-5566-4189-8d83-385dabe9d1b1
		sourceLineageTag: 683d5a24-654b-49a9-9c9e-5abeb62d48b3
		dataCategory: Uncategorized

	measure 'Hide Visual' = EXTERNALMEASURE("Hide Visual", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: da07c131-b145-4640-84f3-84fb3c10867a
		sourceLineageTag: fe857167-80d4-4213-a05f-99c77e730010
		dataCategory: Uncategorized

	measure 'Verzoek Kosten arbeid' = EXTERNALMEASURE("Verzoek Kosten arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 3f7e4eb8-5272-429c-afcd-0a68d9d27be5
		sourceLineageTag: 3a93cfa8-8a51-404c-a6cc-014156f8155e
		dataCategory: Uncategorized

	measure 'Verzoek Kosten inkoop' = EXTERNALMEASURE("Verzoek Kosten inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: c9da233e-dfcf-494a-802f-ed56f57550e5
		sourceLineageTag: e56308f8-ec82-4c91-a347-0e1fe87b6ffd
		dataCategory: Uncategorized

	measure 'Verzoek Kosten materiaal' = EXTERNALMEASURE("Verzoek Kosten materiaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: fd51836b-1c70-42bb-a2a2-f18910cc3310
		sourceLineageTag: 86a6b6a5-2958-4f0d-b1e7-859d4e54fec5
		dataCategory: Uncategorized

	measure 'Verzoek Kosten materieel' = EXTERNALMEASURE("Verzoek Kosten materieel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 0479b5e4-eb68-44be-807a-bd5fefa8f9d4
		sourceLineageTag: 3b63d041-b9c6-44ef-896d-d9ffc37d90e2
		dataCategory: Uncategorized

	measure 'Verzoek Kosten overig' = EXTERNALMEASURE("Verzoek Kosten overig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: c9a30494-6359-4e14-afc9-44a3bfd3c33a
		sourceLineageTag: bf535dc0-04c1-4afa-924f-c6a0b675b801
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs arbeid' = EXTERNALMEASURE("Calculatie kostprijs arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: d3c95227-c7ec-4d0e-85f2-7380fbfedb62
		sourceLineageTag: eb3cd45c-49b8-4fea-acfa-15de0aa5568b
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs materiaal' = EXTERNALMEASURE("Calculatie kostprijs materiaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 130592f5-b95b-4a68-b266-631fdfa34f41
		sourceLineageTag: 571aea45-3e2c-4b11-a398-0e2e139993bf
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs materieel' = EXTERNALMEASURE("Calculatie kostprijs materieel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 0e4396a4-4b95-4d16-a5a6-7fd9ef896532
		sourceLineageTag: 88677493-440f-45ee-af89-219bb6e64eb3
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs overig' = EXTERNALMEASURE("Calculatie kostprijs overig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: b32108ff-670b-43ee-ad17-fdb16b6520df
		sourceLineageTag: 417ff62f-44fc-4419-97bd-0754dea87bf4
		dataCategory: Uncategorized

	measure 'Budget kostprijs arbeid' = EXTERNALMEASURE("Budget kostprijs arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 3af89c2f-1adc-4b6a-b2ea-1374a7cae8e9
		sourceLineageTag: 5a87bd28-52b9-4829-b4fe-51e108d5efc5
		dataCategory: Uncategorized

	measure 'Budget kostprijs materiaal' = EXTERNALMEASURE("Budget kostprijs materiaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 6cdc41a9-fb00-4e3f-9a3b-7a8722d87a79
		sourceLineageTag: ce462c1e-007c-4256-8d13-e13a8b25feb8
		dataCategory: Uncategorized

	measure 'Budget kostprijs materieel' = EXTERNALMEASURE("Budget kostprijs materieel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: dd5c919f-b4d2-4b80-9ee0-4f0259fc9d2d
		sourceLineageTag: 6930c91b-d6b2-4a34-8c64-a5fc728c6daf
		dataCategory: Uncategorized

	measure 'Budget kostprijs overig' = EXTERNALMEASURE("Budget kostprijs overig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: dd207aec-aafb-4b32-a031-76e687188208
		sourceLineageTag: f1c08236-d1e2-4c8d-9d71-29e8fa92d2dc
		dataCategory: Uncategorized

	measure 'Prognose kostprijs arbeid' = EXTERNALMEASURE("Prognose kostprijs arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 8602abbb-2919-42b5-8b9c-ad35a9e42b6c
		sourceLineageTag: f2d4945c-fd40-4999-b726-74033554f86a
		dataCategory: Uncategorized

	measure 'Prognose kostprijs inkoop' = EXTERNALMEASURE("Prognose kostprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 2bbc432c-4112-46d1-964f-181ed4daea05
		sourceLineageTag: 97c24aae-c5fa-4311-8959-ed67b42ac340
		dataCategory: Uncategorized

	measure 'Prognose kostprijs materiaal' = EXTERNALMEASURE("Prognose kostprijs materiaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 20e945e3-206a-4fca-a795-98b3f38bf1fa
		sourceLineageTag: 44180bfa-4599-4722-b95c-fa27407c53b4
		dataCategory: Uncategorized

	measure 'Prognose kostprijs materieel' = EXTERNALMEASURE("Prognose kostprijs materieel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: c676d34f-46b2-4c40-bc68-e8aeada57a14
		sourceLineageTag: a4040b01-eab5-40c1-ba8d-09936b928764
		dataCategory: Uncategorized

	measure 'Prognose kostprijs overig' = EXTERNALMEASURE("Prognose kostprijs overig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: d76ee373-82f1-4c03-ba28-94b84155d751
		sourceLineageTag: 00677f77-9562-4ea8-93e1-91e53600b844
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs materiaal' = EXTERNALMEASURE("Definitieve kostprijs materiaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 7c217dac-7807-4faa-8d18-d45d86267d01
		sourceLineageTag: 2a9aa6e2-0d77-4cdb-8cda-741ce7afd5b6
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs materieel' = EXTERNALMEASURE("Definitieve kostprijs materieel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 76a2cb02-07c6-40d7-b2bc-2269ff1092a3
		sourceLineageTag: 90d1a367-2992-4750-ac0a-f2367f62cce1
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs overig' = EXTERNALMEASURE("Definitieve kostprijs overig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: d409fb3c-62af-45d0-a506-f3420f0148e4
		sourceLineageTag: 3b4f7878-6eaf-4bcb-ba83-4ae571a72a31
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op prognose (TWP)' = EXTERNALMEASURE("Toegevoegde Waarde op prognose (TWP)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 60f3291c-f7f7-4e8a-9d17-1d38bc3b9be4
		sourceLineageTag: 10a7c13c-e113-40d4-bbaa-3454fe2251a6
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op prognose per uur (TWP\u)' = EXTERNALMEASURE("Toegevoegde Waarde op prognose per uur (TWP\u)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: deabd385-eeb0-40b3-af7a-007b3fb73b4d
		sourceLineageTag: 7def5ec6-8ecf-478a-8c25-63ad1db5188e
		dataCategory: Uncategorized

	measure Startdatum = EXTERNALMEASURE("Startdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yyyy
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 00ae796e-a8ec-4c23-96e8-fbf87daf355c
		sourceLineageTag: 6ae67542-e5bf-4aec-8b71-a8617c7cea11
		dataCategory: Uncategorized

	measure Einddatum = EXTERNALMEASURE("Einddatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yyyy
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 44bfcdb4-324f-4d53-aada-89cd605f6e20
		sourceLineageTag: 35dd5df9-b348-4d4d-95a9-2e8708e3f2a3
		dataCategory: Uncategorized

	measure EBIT = EXTERNALMEASURE("EBIT", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 2333c0bf-8c7e-4138-b2e7-f79a267dcea4
		sourceLineageTag: 37993b3d-4122-4892-ad9c-377d7c23038a
		dataCategory: Uncategorized

	measure 'Verschil opbrengsten - kosten eliminatie' = EXTERNALMEASURE("Verschil opbrengsten - kosten eliminatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 280a09c6-a3ce-4956-bd1f-c540afd0e28a
		sourceLineageTag: 826bbd40-6c90-41f5-b89b-bbe77ef0b9f8
		dataCategory: Uncategorized

	measure 'Debet eliminatie Resultaatrekening' = EXTERNALMEASURE("Debet eliminatie Resultaatrekening", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 3878f326-07af-4a2f-8316-c34d6d83d6f9
		sourceLineageTag: 21809d27-3f91-4f33-bfcc-702b6d064088
		dataCategory: Uncategorized

	measure 'Debet eliminatie Balans' = EXTERNALMEASURE("Debet eliminatie Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 943b547b-0b34-456c-9b1b-94828b0418ee
		sourceLineageTag: 7b1a50ed-63bb-4eb0-972e-f69b7dc5e7b1
		dataCategory: Uncategorized

	measure 'Debet eliminatie' = EXTERNALMEASURE("Debet eliminatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 15f46cad-b030-43f1-a940-8e66063ab7d9
		sourceLineageTag: aa0239ba-3107-4997-80ad-380f1ef210dd
		dataCategory: Uncategorized

	measure 'Credit eliminatie Resultaatrekening' = EXTERNALMEASURE("Credit eliminatie Resultaatrekening", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 2abe057a-9371-4121-afa4-c8f32d1f94f3
		sourceLineageTag: d090d3c9-8fea-469c-98a1-d6dae52c9231
		dataCategory: Uncategorized

	measure 'Credit eliminatie Balans' = EXTERNALMEASURE("Credit eliminatie Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 25011234-fcb9-425e-9af6-ea4537cbaa9c
		sourceLineageTag: 4f99de88-c037-4862-80fb-185f9a1fe718
		dataCategory: Uncategorized

	measure 'Credit eliminatie' = EXTERNALMEASURE("Credit eliminatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten
		lineageTag: 8bc8f129-21a2-44d8-bbdc-f8c69646945f
		sourceLineageTag: 2369e631-9121-4d60-b7e3-08416212ee87
		dataCategory: Uncategorized

	measure 'Titel verkoopfacturen' = EXTERNALMEASURE("Titel verkoopfacturen", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: e3621473-9fbb-4426-927b-7bcd44dc5626
		sourceLineageTag: 23174d9a-10f8-4f34-a131-377b0b8cf1b8
		dataCategory: Uncategorized

	measure 'Melding gekoppelde inkoopfactuur' = EXTERNALMEASURE("Melding gekoppelde inkoopfactuur", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 092103e4-2cf5-4366-a631-9cf1b1556859
		sourceLineageTag: c05f146e-df2f-4a96-a183-1b572d330099
		dataCategory: Uncategorized

	measure 'Eliminatie opbrengsten' = EXTERNALMEASURE("Eliminatie opbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Opbrengsten
		lineageTag: 8d3f1af5-8339-4620-8e1e-db867091faa0
		sourceLineageTag: 82d9d4cb-cc6b-4706-ac50-0e83849ec723
		dataCategory: Uncategorized

	measure 'Eliminatie inkoopkosten van de opbrengsten' = EXTERNALMEASURE("Eliminatie inkoopkosten van de opbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Opbrengsten
		lineageTag: ca7f56ee-8d8a-4cdd-a4ba-6a04e2b5974b
		sourceLineageTag: 76d33a97-d285-476a-9fff-1d4aa0b3d96c
		dataCategory: Uncategorized

	measure 'Controle opbrengsten gelijk aan gekoppelde inkoopkosten' = EXTERNALMEASURE("Controle opbrengsten gelijk aan gekoppelde inkoopkosten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: ce7d9b4f-446d-4879-a5e8-d46f57cd71f9
		sourceLineageTag: b30a67c4-eada-4bd2-9f49-2f7404587591
		dataCategory: Uncategorized

	measure 'Verkoopfactuur buiten datumselectie' = EXTERNALMEASURE("Verkoopfactuur buiten datumselectie", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: fec7b975-b000-4469-b6da-f8b7895e8410
		sourceLineageTag: 6e846994-8285-42e0-b005-b64e5f6f295e
		dataCategory: Uncategorized

	measure 'Titel inkoopfacturen' = EXTERNALMEASURE("Titel inkoopfacturen", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: f8a5c225-bdd4-4baf-bcd4-433176e31d1b
		sourceLineageTag: f2c4b7aa-f0ee-4182-bf6b-2d8520837337
		dataCategory: Uncategorized

	measure 'Melding gekoppelde verkoopfactuur' = EXTERNALMEASURE("Melding gekoppelde verkoopfactuur", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 38f51709-d3df-410c-9cb4-3bca55c2455a
		sourceLineageTag: 1ed0adc2-4277-4af7-9e5f-4fb4a92c2830
		dataCategory: Uncategorized

	measure 'Eliminatie opbrengsten van de inkoopkosten' = EXTERNALMEASURE("Eliminatie opbrengsten van de inkoopkosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Inkoopkosten
		lineageTag: c32603b4-1bca-4031-950a-38d19677f0bd
		sourceLineageTag: 52ecec27-f20a-440e-998b-6d9d50d559bd
		dataCategory: Uncategorized

	measure 'Eliminatie inkoopkosten' = EXTERNALMEASURE("Eliminatie inkoopkosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Eliminatie posten\Inkoopkosten
		lineageTag: 29d2a67d-925c-4a48-a6d1-64eaa81bd212
		sourceLineageTag: 46112da0-5564-4e41-9cfa-02fef11266ff
		dataCategory: Uncategorized

	measure 'Controle inkoopkosten gelijk aan gekoppelde opbrengsten' = EXTERNALMEASURE("Controle inkoopkosten gelijk aan gekoppelde opbrengsten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 4a14d980-a267-49c8-a1f9-b6f99ebd6cd7
		sourceLineageTag: 6693990a-6849-4285-baf2-725318e1facf
		dataCategory: Uncategorized

	measure 'Mutatie budget per dag' = EXTERNALMEASURE("Mutatie budget per dag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess
		lineageTag: 8dc5f7e4-d5bf-4908-830b-272404007001
		sourceLineageTag: 76f7e1e0-19a8-4e89-ab76-251121c03481
		dataCategory: Uncategorized

	measure 'Budget YTD' = EXTERNALMEASURE("Budget YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess
		lineageTag: 8f718466-2023-49de-bb0c-96abd3877137
		sourceLineageTag: 3a1a70c0-8853-4084-8cca-2dcfb60a782b
		dataCategory: Uncategorized

	measure '% YTD t.o.v. YTD budget' = EXTERNALMEASURE("% YTD t.o.v. YTD budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: 9a5a8bd5-3b69-4d3d-af26-eb6d54701790
		sourceLineageTag: a60a9ebf-78a2-4b28-a787-817c4531cafb
		dataCategory: Uncategorized

	measure '% YTD t.o.v. YTD LY' = EXTERNALMEASURE("% YTD t.o.v. YTD LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 829331c8-17ad-45d3-a40c-f03ba4e0ca1a
		sourceLineageTag: 78fec33c-4805-4a56-8246-b425892b8319
		dataCategory: Uncategorized

	measure 'CoA Actual LY' = EXTERNALMEASURE("CoA Actual LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 59f18412-f314-4ad5-ad41-66a5b1312b01
		sourceLineageTag: e37f2b81-4f26-46ce-ac31-c55e2fa2d966
		dataCategory: Uncategorized

	measure 'CoA lege regel' = EXTERNALMEASURE("CoA lege regel", INTEGER, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: a8e4f9cb-84f4-4970-9888-c7f8857ecdac
		sourceLineageTag: e0e60c39-60ea-4130-834d-8922d53c5d0b
		dataCategory: Uncategorized

	measure 'CoA mutatie' = EXTERNALMEASURE("CoA mutatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: aa90fb5d-f4cf-4688-be07-d25368af4804
		sourceLineageTag: 244d7059-1405-4db0-a722-c34b6fec07b5
		dataCategory: Uncategorized

	measure 'CoA mutatie budget' = EXTERNALMEASURE("CoA mutatie budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget
		lineageTag: fef59ae9-1cf9-4521-a9a4-89fa77e2882a
		sourceLineageTag: f0680ca1-ca0a-4bf0-92b0-2dad5e2895a4
		dataCategory: Uncategorized

	measure 'CoA resultaat' = EXTERNALMEASURE("CoA resultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 06c4966d-1db3-4190-a397-5ceadb9adeeb
		sourceLineageTag: d61618ed-7e11-4f3e-91b1-5ad9a48a5d4e
		dataCategory: Uncategorized

	measure 'CoA subtotaal waardes' = EXTERNALMEASURE("CoA subtotaal waardes", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 2fe370cb-f877-40b2-a3ac-ef99ba30542c
		sourceLineageTag: 142de4eb-7bc2-4a19-95b2-df8cbd5b9a20
		dataCategory: Uncategorized

	measure 'CoA YTD rendement' = EXTERNALMEASURE("CoA YTD rendement", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 625a719e-3543-468a-9af5-16c70b66af98
		sourceLineageTag: c17f996b-0a41-45d1-9a2c-fe6e973d88c5
		dataCategory: Uncategorized

	measure 'CoA YTD rendement budget' = EXTERNALMEASURE("CoA YTD rendement budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget
		lineageTag: 87170ce1-3aa6-4718-a2f4-b8aa4a00f482
		sourceLineageTag: fa1b6fea-3e82-4b52-bfc7-0250bf90a2f7
		dataCategory: Uncategorized

	measure 'CoA YTD rendement LY' = EXTERNALMEASURE("CoA YTD rendement LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: c5d5522f-93cd-46cb-af75-3a36e3fc0ecb
		sourceLineageTag: 7b48b9cb-acbb-4365-9f7b-b025bff910e6
		dataCategory: Uncategorized

	measure 'Delta actual - actual-LY' = EXTERNALMEASURE("Delta actual - actual-LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: f7da821a-c847-4aa9-82ba-73d50f1f3641
		sourceLineageTag: ef15c529-a5c1-4407-a67a-5d91c83230df
		dataCategory: Uncategorized

	measure 'Delta actual - budget' = EXTERNALMEASURE("Delta actual - budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: 4973e61e-e863-4b6c-b7ad-64820609d108
		sourceLineageTag: 5e3ba073-e210-47f4-beff-65638964256c
		dataCategory: Uncategorized

	measure 'Geselecteerde classificatie' = EXTERNALMEASURE("Geselecteerde classificatie", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 15faee50-0dc4-44f6-8d01-bd4c5b1ec269
		sourceLineageTag: 7726db8d-1d2b-4728-a625-4300b7f4cedc
		dataCategory: Uncategorized

	measure 'Melding resultaat rubrieken zijn niet gekoppeld' = EXTERNALMEASURE("Melding resultaat rubrieken zijn niet gekoppeld", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: d6587fbf-e398-41f1-a9b1-a54a9a3c7742
		sourceLineageTag: f7e3a582-6173-40e7-8c5a-eaff2ab66dde
		dataCategory: Uncategorized

	measure 'Mutatie resultaat' = EXTERNALMEASURE("Mutatie resultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 01d82011-ca85-4ef9-adb0-69b0d1129760
		sourceLineageTag: a824f6b4-0bce-406c-8374-fb9cade480ff
		dataCategory: Uncategorized

	measure 'Mutatie resultaat budget' = EXTERNALMEASURE("Mutatie resultaat budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget
		lineageTag: 281e2c07-aeb8-4c13-b6b4-d3538d386175
		sourceLineageTag: 8183d59a-398f-4015-b0b0-a63f45b69d43
		dataCategory: Uncategorized

	measure 'Mutatie resultaat LY' = EXTERNALMEASURE("Mutatie resultaat LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 78c475a2-b7d7-41fd-9a4e-a394741791ad
		sourceLineageTag: e04e145f-3d10-4662-9447-cb95a82de745
		dataCategory: Uncategorized

	measure 'Mutatie resultaat met mapping' = EXTERNALMEASURE("Mutatie resultaat met mapping", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 9d3f8005-f9de-4115-9310-22b57870e154
		sourceLineageTag: 03f18d84-32a1-47d4-8853-5b12db3d8cae
		dataCategory: Uncategorized

	measure 'Mutatie resultaat zonder mapping' = EXTERNALMEASURE("Mutatie resultaat zonder mapping", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 1d7f2886-6c9b-4447-b9d5-2af8f0d7d712
		sourceLineageTag: e0fa9d34-1dd4-4e04-be2d-e4063579de43
		dataCategory: Uncategorized

	measure 'Waardemelding resultaat rubrieken zijn niet gekoppeld' = EXTERNALMEASURE("Waardemelding resultaat rubrieken zijn niet gekoppeld", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 9eae779d-9b95-44fd-a350-128202a03ca1
		sourceLineageTag: 58e749f1-500f-48dd-be49-f8a2ac0adcde
		dataCategory: Uncategorized

	measure 'Actual YTD exploitatierekening' = EXTERNALMEASURE("Actual YTD exploitatierekening", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 8a327f71-2dee-4353-817a-c48eff1f19bf
		sourceLineageTag: ec057129-72c0-4661-8d36-6848439b3ce9
		dataCategory: Uncategorized

	measure 'Actual mutatie exploitatierekening' = EXTERNALMEASURE("Actual mutatie exploitatierekening", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 4b2a8d9f-b191-4829-b0da-e750c9fa563d
		sourceLineageTag: 2edf90dd-7ae9-46c0-a145-bed95274a824
		dataCategory: Uncategorized

	measure 'Mutatie Balans YTD (debet-credit)' = EXTERNALMEASURE("Mutatie Balans YTD (debet-credit)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: b79df2b8-2d35-4ae5-ae2f-f5bb45977c41
		sourceLineageTag: cfc3bfd7-e593-4b6c-b9a7-f362e0b24828
		dataCategory: Uncategorized

	measure 'Mutatie Balans (debet-credit)' = EXTERNALMEASURE("Mutatie Balans (debet-credit)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: 3fefcd47-6ef6-4339-9ff5-c51b5bcfa832
		sourceLineageTag: e74e0a8d-5c32-46a4-b619-cb06cf5ad4ed
		dataCategory: Uncategorized

	/// [Actual debet-YTD Balans]-[Actual credit-YTD Balans] indien groter dan 1 andere leeg.
	measure 'Debet balans' = EXTERNALMEASURE("Debet balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: 701c73d5-1a58-4ead-b0f0-1a8312dfbb25
		sourceLineageTag: 1ae82302-4a38-4ada-ba3e-9c6bf4cbc49b
		dataCategory: Uncategorized

	/// [Actual credit-YTD Balans]- [Actual debet-YTD Balans] indien groter dan 1 andere leeg.
	measure 'Credit balans' = EXTERNALMEASURE("Credit balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: b5a589d0-33ca-44d3-b724-e38bc835b260
		sourceLineageTag: 3c87c264-1973-4d3e-8c65-1d2159d96c61
		dataCategory: Uncategorized

	/// Debet boekingen op balans rekeningen vanaf 1 januari (van het jaar van de geselecteerde einddatum) tot en met  geselecteerde einddatum.
	measure 'Actual debet-YTD Balans' = EXTERNALMEASURE("Actual debet-YTD Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: eac57fb4-d1ca-45e1-afa5-590c42835c99
		sourceLineageTag: 2f15c103-b090-4156-9740-d69ac7a30779
		dataCategory: Uncategorized

	/// Debet boekingen op balans rekeningen in geselecteerde periode.
	measure 'Actual debet-mutatie Balans' = EXTERNALMEASURE("Actual debet-mutatie Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: cb6ff0aa-7ff0-4c65-9fe5-c54a04aaf30f
		sourceLineageTag: ba6e2c9c-97c7-4ba4-bd21-f79338a0eb40
		dataCategory: Uncategorized

	/// Credit boekingen op balans rekeningen vanaf 1 januari (van het jaar van de geselecteerde einddatum) tot en met  geselecteerde einddatum.
	measure 'Actual credit-YTD Balans' = EXTERNALMEASURE("Actual credit-YTD Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: 07e1b20a-bbaa-4cad-b3fa-4e504202e029
		sourceLineageTag: 4a862e77-72a0-4048-8174-ad51c9931268
		dataCategory: Uncategorized

	/// Credit boekingen op balans rekeningen in geselecteerde periode.
	measure 'Actual credit-mutatie Balans' = EXTERNALMEASURE("Actual credit-mutatie Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans
		lineageTag: 884be62d-a36c-4817-9ddd-4b958a882353
		sourceLineageTag: a58e5319-7a1c-4bd6-8bfc-9afd3b7c3a15
		dataCategory: Uncategorized

	measure 'Actual credit-mutatie Balans CoA' = EXTERNALMEASURE("Actual credit-mutatie Balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 8729a9c3-4977-4629-bbe5-37da2adc0ce0
		sourceLineageTag: 97049361-8bcc-4715-8666-bbceaa298b2a
		dataCategory: Uncategorized

	measure 'Actual credit-YTD Balans CoA' = EXTERNALMEASURE("Actual credit-YTD Balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 9dbb4726-42a4-4092-8b0b-a39291408e00
		sourceLineageTag: 06d422f5-2cd5-4d0c-bd46-9df33870a28c
		dataCategory: Uncategorized

	measure 'Actual debet-mutatie Balans CoA' = EXTERNALMEASURE("Actual debet-mutatie Balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 1650a2b4-2a78-4172-88d1-ef814b2a215a
		sourceLineageTag: 2be6108d-2a42-498c-a4e7-85189089f13f
		dataCategory: Uncategorized

	measure 'Actual debet-YTD Balans CoA' = EXTERNALMEASURE("Actual debet-YTD Balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 559e2ef3-6737-4b30-84d6-099704e30e53
		sourceLineageTag: 9d1832c3-c467-4721-8b31-bbcc48e9c5bb
		dataCategory: Uncategorized

	measure 'CoA balans YTD' = EXTERNALMEASURE("CoA balans YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;("€"\ #,0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: ef7c070c-8fd1-48ff-ae09-ef7b035e15f7
		sourceLineageTag: 30199af5-0e71-4fe3-8858-5b6002581a02
		dataCategory: Uncategorized

	measure 'Credit balans YTD CoA' = EXTERNALMEASURE("Credit balans YTD CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: ddabde27-a50c-4b98-9034-7b89af0461a4
		sourceLineageTag: a86caa04-f763-450d-a210-9f9bd6b9e65f
		dataCategory: Uncategorized

	measure 'Debet balans YTD CoA' = EXTERNALMEASURE("Debet balans YTD CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: e57f0c1f-a96b-496a-adad-33efcccbb528
		sourceLineageTag: ed88e485-9ed1-4e9a-ae93-c2294c1a3815
		dataCategory: Uncategorized

	measure 'Melding balans rubrieken zijn niet gekoppeld' = EXTERNALMEASURE("Melding balans rubrieken zijn niet gekoppeld", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 50b77ae6-51b1-41d1-a1bf-fdefcd3ae6be
		sourceLineageTag: 31654ca0-1799-440d-a9f2-0740851adedf
		dataCategory: Uncategorized

	measure 'Mutatie balans met mapping' = EXTERNALMEASURE("Mutatie balans met mapping", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: e5f48388-c2a6-4655-a28e-8908bdd4a3d5
		sourceLineageTag: c9c19e9d-c11d-4ed3-b4e2-f210bf4be9bb
		dataCategory: Uncategorized

	measure 'Mutatie balans zonder mapping' = EXTERNALMEASURE("Mutatie balans zonder mapping", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: b073b954-95ec-4f1f-a7f7-f2733a380416
		sourceLineageTag: 31dea313-9798-4eda-a239-24d1d82ca566
		dataCategory: Uncategorized

	measure 'resultaat W&V CoA Balans' = EXTERNALMEASURE("resultaat W&V CoA Balans", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 4002f9e3-b71f-48fb-b18f-87439e7ab963
		sourceLineageTag: 24006fcf-0fab-403f-bf37-73522d85ce2b
		dataCategory: Uncategorized

	measure 'Selected classificatie type subtotaal' = EXTERNALMEASURE("Selected classificatie type subtotaal", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: a265802f-268f-4202-9ca0-059fae5623a3
		sourceLineageTag: 6ad355f6-7535-4a68-bc13-fcb741365fc7
		dataCategory: Uncategorized

	measure 'Stand Balans CoA' = EXTERNALMEASURE("Stand Balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: d43e5b35-07b1-4265-86de-c4553b835039
		sourceLineageTag: 9b6385a9-fec7-49d2-9a32-e832e761926c
		dataCategory: Uncategorized

	measure 'Verschil credit-debet balans CoA' = EXTERNALMEASURE("Verschil credit-debet balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: b341fbd6-00a8-4a04-85ec-868bfbc38b2c
		sourceLineageTag: 3d0d48dc-b029-4a54-bf52-0d4c79deb368
		dataCategory: Uncategorized

	measure 'Verschil debet-credit balans CoA' = EXTERNALMEASURE("Verschil debet-credit balans CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 01f1e557-0ca6-45da-b56c-85c728604cd0
		sourceLineageTag: 123763ac-fb43-40cb-bd82-2f773219f2ac
		dataCategory: Uncategorized

	measure 'Waardemelding balans rubrieken zijn niet gekoppeld' = EXTERNALMEASURE("Waardemelding balans rubrieken zijn niet gekoppeld", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: cb99f178-3a60-4351-913c-fe6d7b52048e
		sourceLineageTag: 27bb0b1f-d055-490e-8538-81e38a6ffe1e
		dataCategory: Uncategorized

	measure 'Projectjournalisering projectwaarderingen' = EXTERNALMEASURE("Projectjournalisering projectwaarderingen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 1c3c1788-bb5d-4455-a495-f3fad00094e5
		sourceLineageTag: 391edf74-fc61-4398-b377-4449d0f45333
		dataCategory: Uncategorized

	measure 'Projectjournalisering werkresultaat' = EXTERNALMEASURE("Projectjournalisering werkresultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: c79861d7-f5a1-4401-a3f0-7ea6ff5d9716
		sourceLineageTag: 92a9642c-eef7-4a0f-b398-9300ab9055fc
		dataCategory: Uncategorized

	measure 'Projectjournalisering projectwaarderingen en werkresultaat' = EXTERNALMEASURE("Projectjournalisering projectwaarderingen en werkresultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 88ffc437-e4cd-4d1b-b1dd-6890851dc424
		sourceLineageTag: 0687d129-aba6-4eea-b751-c460e5f68ca9
		dataCategory: Uncategorized

	measure 'Project resultaat incl. omzet correctie' = EXTERNALMEASURE("Project resultaat incl. omzet correctie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 12d6bd40-508c-4abb-a6c3-a44299a84136
		sourceLineageTag: 8570e946-bb56-4a6a-bebd-3736a532e13f
		dataCategory: Uncategorized

	measure 'Montage en reis uren incl. inleen via inkoopdactuur' = EXTERNALMEASURE("Montage en reis uren incl. inleen via inkoopdactuur", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: e736cd0f-9ef0-44a8-8cfd-5c383e0bc757
		sourceLineageTag: 8225a01a-3c52-44bd-b6be-dec407f84d50
		dataCategory: Uncategorized

	measure 'Reis uren op projecten' = EXTERNALMEASURE("Reis uren op projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 4d8b3e4c-818c-4188-a8f9-a8e8d5f98ed4
		sourceLineageTag: 8babc6a4-cf1d-469f-8ba5-5cca37da86a0
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op realisatie per montage + reis uur (TWR\u)' = EXTERNALMEASURE("Toegevoegde Waarde op realisatie per montage + reis uur (TWR\u)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 98c03d23-c6aa-4b65-9d10-cddb933afe80
		sourceLineageTag: 82f9a065-2399-4a30-8272-4abdc8280957
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren MPS monteurs' = EXTERNALMEASURE("Gerealiseerde uren MPS monteurs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: 126fc463-e05c-48dc-ad3b-e3a633fb9610
		sourceLineageTag: d6c4ffa9-8ef0-4129-a0b2-d973fce0d9f8
		dataCategory: Uncategorized

	measure 'Montage uren t.o.v. totale uren eigen MPS monteurs (projecten en S&O)' = EXTERNALMEASURE("Montage uren t.o.v. totale uren eigen MPS monteurs (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: a0372255-f33d-4da9-a76d-2b3c50820146
		sourceLineageTag: 05a58f14-6c1f-4df2-9595-f8634ec3151b
		dataCategory: Uncategorized

	measure 'Montage uren MPS functie monteurs (projecten en S&O)' = EXTERNALMEASURE("Montage uren MPS functie monteurs (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 7c38195b-63ce-4f9c-91d7-6b8f8fd44084
		sourceLineageTag: 64e1480f-47fb-424a-a481-c585ca931a68
		dataCategory: Uncategorized

	measure 'Montage uren niet MPS functie monteurs (projecten en S&O)' = EXTERNALMEASURE("Montage uren niet MPS functie monteurs (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: e2d6c67c-58c1-4392-b8fa-4a3956be77be
		sourceLineageTag: 1512b377-a71c-4b36-b089-9b1d07707877
		dataCategory: Uncategorized

	measure 'Inleenuren via inkoop' = EXTERNALMEASURE("Inleenuren via inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 8d1e308a-c170-48b0-8d24-63628e7b79c3
		sourceLineageTag: cb7fdee5-27e4-4122-aa5e-2c06d2036ff4
		dataCategory: Uncategorized

	measure 'Projectjournalisering werkresultaat opbrengsten' = EXTERNALMEASURE("Projectjournalisering werkresultaat opbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 1da70f5f-c886-4b8d-b52a-b574e6ae2f0a
		sourceLineageTag: 1cf676c5-cd1a-4f50-b062-d51d73ff85e3
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren eigen MPS monteurs' = EXTERNALMEASURE("Gerealiseerde uren eigen MPS monteurs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: ce6033c5-664b-47d2-8941-7b55097bd7ef
		sourceLineageTag: 28bb8b82-3fb5-4ee2-bde8-36ded531fb09
		dataCategory: Uncategorized

	measure 'Montage uren eigen personeel' = EXTERNALMEASURE("Montage uren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 1920d3dc-728a-4a4c-bd00-fe96fc6ddb13
		sourceLineageTag: 15ece63f-74d0-4736-b99e-fb20508f3f46
		dataCategory: Uncategorized

	measure 'Montage uren eigen MPS monteurs (projecten en S&O)' = EXTERNALMEASURE("Montage uren eigen MPS monteurs (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 6a378622-41ec-4863-a133-cef578e58d59
		sourceLineageTag: 2bdf1dbc-5de5-474e-81ad-7dac8c657a00
		dataCategory: Uncategorized

	measure 'Montage uren niet eigen MPS monteurs (projecten en S&O)' = EXTERNALMEASURE("Montage uren niet eigen MPS monteurs (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 8a604bab-5609-4af9-b71c-34d261c1570c
		sourceLineageTag: 4d611338-4ea0-464c-8eb4-98b950db0c49
		dataCategory: Uncategorized

	measure 'Voortgang facturatie actuele projecten' = EXTERNALMEASURE("Voortgang facturatie actuele projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: a7976bd1-7053-4e71-9250-d523fc83f39f
		sourceLineageTag: 624c122b-e426-4734-b5d0-8dda944ba58d
		dataCategory: Uncategorized

	measure Inkoopkorting = EXTERNALMEASURE("Inkoopkorting", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: c8c46c6f-d0c3-432e-9200-a4b1623e8ee1
		sourceLineageTag: 73b2f860-2d30-41be-a5bd-1dbefc4a3907
		dataCategory: Uncategorized

	measure 'Inkoopkorting %' = EXTERNALMEASURE("Inkoopkorting %", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA rekeningschema
		lineageTag: 48a548f1-1805-4b91-98f6-9631d1ea2282
		sourceLineageTag: 199bdaa0-4a82-4a43-ac7d-defaaa04e27b
		dataCategory: Uncategorized

	measure 'Inleenuren via inkoop zonder datumfilter' = EXTERNALMEASURE("Inleenuren via inkoop zonder datumfilter", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 32ca28cd-6bac-4eec-bcf2-3e811c718c18
		sourceLineageTag: 005fff79-0208-4ace-b364-9042b280f412
		dataCategory: Uncategorized

	measure 'Montage uren zonder datumfilter' = EXTERNALMEASURE("Montage uren zonder datumfilter", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: d07b9914-0d2b-4e84-87ae-ffc7b2b4f9da
		sourceLineageTag: b8db88c0-fc4e-4bf7-80ea-552ffc196075
		dataCategory: Uncategorized

	measure 'Montage en reis uren zonder datumfilter' = EXTERNALMEASURE("Montage en reis uren zonder datumfilter", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 724db6f6-8b95-451c-8ecf-763d404bb786
		sourceLineageTag: 4f033444-fb03-4bb0-9d2b-f0c2abf5111d
		dataCategory: Uncategorized

	measure 'minimale productiviteit' = EXTERNALMEASURE("minimale productiviteit", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 7e8060ab-cf19-4769-931c-1d5065c88ae6
		sourceLineageTag: bb1cb10f-c6a0-494b-a88f-a0c00b214660
		dataCategory: Uncategorized

	measure 'Norm productiviteit eigen monteurs' = EXTERNALMEASURE("Norm productiviteit eigen monteurs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 1fe561d7-62fb-4006-aea4-e58078782f6d
		sourceLineageTag: 347ee896-49bd-45e7-b092-d008dfa4e1db
		dataCategory: Uncategorized

	measure 'Controle productiviteit t.o.v. norm eigen monteurs' = EXTERNALMEASURE("Controle productiviteit t.o.v. norm eigen monteurs", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 95a7932d-a91e-48e6-b5ef-1020dfb1dd58
		sourceLineageTag: 1cce83b0-24c8-4240-ba60-8b77545f71f7
		dataCategory: Uncategorized

	measure 'Calculatie projectgebonden uren' = EXTERNALMEASURE("Calculatie projectgebonden uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: b0fffb56-16ff-430a-933b-06d057b404bf
		sourceLineageTag: 190e620b-b0bc-47ab-a8b2-9de30b210da8
		dataCategory: Uncategorized

	measure 'Project marge incl. omzetcorrectie' = EXTERNALMEASURE("Project marge incl. omzetcorrectie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: c3c575f7-358b-43c5-bfeb-edddaf2ee664
		sourceLineageTag: fc58c3e0-a76b-4e24-a996-2cfe27aa3c7d
		dataCategory: Uncategorized

	measure FTE = EXTERNALMEASURE("FTE", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE
		lineageTag: 9c58e453-825d-4a44-8b44-666d931046ec
		sourceLineageTag: b3d48a7e-d1f9-4271-bddf-ca85b7dc7785
		dataCategory: Uncategorized

	measure 'FTE monteurs' = EXTERNALMEASURE("FTE monteurs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE
		lineageTag: 0b5a25a3-9291-4e5b-be98-86f33e153d8e
		sourceLineageTag: 8204a9cb-0006-4dca-b4c7-fb25b439ce6c
		dataCategory: Uncategorized

	measure 'FTE projectgebonden' = EXTERNALMEASURE("FTE projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE
		lineageTag: ca3c2190-fc61-49dc-a985-6888584781ad
		sourceLineageTag: 6f662cf7-3d76-48c5-b4b9-4aef8a15e54a
		dataCategory: Uncategorized

	measure 'FTE Staf' = EXTERNALMEASURE("FTE Staf", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE
		lineageTag: 1dc6794e-fdbb-4019-94e7-81a32156655e
		sourceLineageTag: 66e44b19-e43a-49c5-8f0d-ac5b1d9216fc
		dataCategory: Uncategorized

	measure 'FTE monteurs t.o.v. totaal' = EXTERNALMEASURE("FTE monteurs t.o.v. totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 3a3bb74e-c5b4-4ce9-b995-d4449862f229
		sourceLineageTag: 969e165e-28ee-43d9-8cae-b1e0a5ce006c
		dataCategory: Uncategorized

	measure 'FTE eigen personeel' = EXTERNALMEASURE("FTE eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0
		displayFolder: 1. Semantisch model\1.02 HR\FTE
		lineageTag: 6d260563-be6e-4edc-ae76-b6d83d2670b9
		sourceLineageTag: bdf31725-56ac-4b32-8aca-d4361cbcff10
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren eigen personeel' = EXTERNALMEASURE("Gerealiseerde uren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: 2869dbb6-cd22-44cc-a26e-14c5b07bd170
		sourceLineageTag: 481c03cb-cc61-440d-bff9-da0e5738dea3
		dataCategory: Uncategorized

	measure 'Ziekte uren eigen personeel' = EXTERNALMEASURE("Ziekte uren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: aaa701e2-5263-4cb8-8a79-1917d5179eaa
		sourceLineageTag: 03111bdd-979b-4674-ad17-db00aa013517
		dataCategory: Uncategorized

	measure 'Ziekteverzuim eigen personeel' = EXTERNALMEASURE("Ziekteverzuim eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 437a2167-b37b-4bd9-b3cc-5b753adbd78c
		sourceLineageTag: d5a72922-09a6-4786-9fcd-2d17c561beab
		dataCategory: Uncategorized

	measure 'Ziekte uren kort eigen personeel' = EXTERNALMEASURE("Ziekte uren kort eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: d63f0dc8-6d49-49af-af9e-18be67589323
		sourceLineageTag: e7157c8c-e6bb-42d4-b05a-77bfd36af481
		dataCategory: Uncategorized

	measure 'Ziekte uren langdurig eigen personeel' = EXTERNALMEASURE("Ziekte uren langdurig eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: 334ac661-bd96-4dec-9e70-7feb2b94e320
		sourceLineageTag: b75f9f04-4096-4081-aae7-539455903dfe
		dataCategory: Uncategorized

	measure 'Ziekteverzuim kort eigen personeel' = EXTERNALMEASURE("Ziekteverzuim kort eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: b8cca937-b47e-41c4-b6f0-df5d46786532
		sourceLineageTag: 14940d9d-7445-4016-9773-ee33fd32378d
		dataCategory: Uncategorized

	measure 'Productieve uren per eigen FTE MPS monteur' = EXTERNALMEASURE("Productieve uren per eigen FTE MPS monteur", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 15494c53-75d9-4586-bfa5-cbc82d88e932
		sourceLineageTag: 76d1089d-b1ff-4f9a-8595-c08ff5f37471
		dataCategory: Uncategorized

	measure 'Productieve uren per eigen FTE MPS projectgebonden' = EXTERNALMEASURE("Productieve uren per eigen FTE MPS projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 02843d69-8650-496f-b74e-2130d86503ee
		sourceLineageTag: 6372266b-9e4f-438e-8be3-05f197dd0f36
		dataCategory: Uncategorized

	measure 'Montage uren t.o.v. totale uren eigen projectgebonden personeel (projecten en S&O)' = EXTERNALMEASURE("Montage uren t.o.v. totale uren eigen projectgebonden personeel (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: d3e5c2a5-0f02-46cf-bbc7-463ee52fd01c
		sourceLineageTag: 6483eedd-a2b5-46fe-a966-dfef75e96656
		dataCategory: Uncategorized

	measure 'Montage uren eigen MPS projectgebonden personeel (projecten en S&O)' = EXTERNALMEASURE("Montage uren eigen MPS projectgebonden personeel (projecten en S&O)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 08c141c3-e1a7-433c-a2f8-a7ea66ae0e96
		sourceLineageTag: 34ac15bf-ffbf-4d33-809b-774969d4b98e
		dataCategory: Uncategorized

	measure 'Ondergrens orderwaarde' = EXTERNALMEASURE("Ondergrens orderwaarde", INTEGER, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen
		lineageTag: f949da10-4941-4bdd-a1ec-eeed18e36613
		sourceLineageTag: 27da34e0-e6fe-4651-b497-ac3358588479
		dataCategory: Uncategorized

	measure 'Aantal budgetverzoeken met order filter' = EXTERNALMEASURE("Aantal budgetverzoeken met order filter", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectbewaking\Budgetverzoeken actuele projecten
		lineageTag: 7df65309-157f-45b1-ab12-79a4da72d4b0
		sourceLineageTag: 61a7dd57-f7cc-4a15-b7e6-93addc352531
		dataCategory: Uncategorized

	measure 'Aantal budgetverzoeken Aantal budgetverzoeken met order filter met 0' = EXTERNALMEASURE("Aantal budgetverzoeken Aantal budgetverzoeken met order filter met 0", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectbewaking\Budgetverzoeken actuele projecten
		lineageTag: bd23c2f2-e9c8-4121-9c95-530b060a9c58
		sourceLineageTag: ccfff8e9-a73c-4573-a91d-73d14da31ed8
		dataCategory: Uncategorized

	measure Productiviteit = EXTERNALMEASURE("Productiviteit", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: babc1959-a2f2-43c2-997c-03de37d5e9c5
		sourceLineageTag: 9e46a38a-458e-4b9e-b3a1-afd532959163
		dataCategory: Uncategorized

	measure Omzet/kosten = EXTERNALMEASURE("Omzet/kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 9164fed8-495e-42ee-94bd-e97a20bda48e
		sourceLineageTag: d9638a7d-125b-4714-a507-07bbb0597b32
		dataCategory: Uncategorized

	measure 'Totaal budgetverzoek/Projectwaarde' = EXTERNALMEASURE("Totaal budgetverzoek/Projectwaarde", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 34442e32-0d08-473a-996d-1c40f4d05c2e
		sourceLineageTag: f5d254ca-67ef-4cc4-9f35-44b652f12154
		dataCategory: Uncategorized

	measure OHW = EXTERNALMEASURE("OHW", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\CoA Balans
		lineageTag: 9566f817-95a6-4e5b-ad97-12edf28bedb3
		sourceLineageTag: c404785e-d3ba-4a8a-a3d2-e46327ce9a11
		dataCategory: Uncategorized

	measure 'Prognose vs budget' = EXTERNALMEASURE("Prognose vs budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 0fbfe20a-06b5-4d5c-9fcf-a4b4f245576d
		sourceLineageTag: a7e30734-874d-47c6-9885-5a1e7777331b
		dataCategory: Uncategorized

	measure 'Aantal werkbonnen' = EXTERNALMEASURE("Aantal werkbonnen", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonnen
		lineageTag: c3e696dc-1b9b-413e-864c-3b009a01c3df
		sourceLineageTag: 96567c36-08ee-4dd5-b1eb-005594a44b32
		dataCategory: Uncategorized

	measure 'Aantal hoofdwerkbonnen' = EXTERNALMEASURE("Aantal hoofdwerkbonnen", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonnen
		lineageTag: caec70ff-98e2-4f32-b17f-d7df9f84f8e9
		sourceLineageTag: ef2ce3e6-a07d-47e8-9294-4d60168c6acb
		dataCategory: Uncategorized

	measure 'Aantal werkbonparagrafen onderhoud' = EXTERNALMEASURE("Aantal werkbonparagrafen onderhoud", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 04236893-a481-4497-bcaf-d3e36cc15a7f
		sourceLineageTag: a71cc206-5001-4d61-aad3-a9ca85e7ab22
		dataCategory: Uncategorized

	measure 'Aantal unieke installaties op bestekparagraaf' = EXTERNALMEASURE("Aantal unieke installaties op bestekparagraaf", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: a28b624d-6d65-4830-a37e-aca8221e1a2e
		sourceLineageTag: 8cfd7b01-2a4f-4b1d-8e4b-e1b30e7464f9
		dataCategory: Uncategorized

	measure 'Aantal installaties op bestekparagraaf' = EXTERNALMEASURE("Aantal installaties op bestekparagraaf", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: ca5be337-ed46-49be-abb7-a346670ee3e0
		sourceLineageTag: e2e9a0ae-de64-452d-a1ae-2ba59c1e5403
		dataCategory: Uncategorized

	measure 'Aantal unieke installaties op bestekparagraaf onderhoud' = EXTERNALMEASURE("Aantal unieke installaties op bestekparagraaf onderhoud", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: eb07ba6e-b6e6-402b-a8b8-ecbd95a2ba83
		sourceLineageTag: f48b6e12-d273-46aa-93d5-8068e5596c2e
		dataCategory: Uncategorized

	measure 'Aantal unieke installaties op bestekparagraaf storing' = EXTERNALMEASURE("Aantal unieke installaties op bestekparagraaf storing", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: 6888bd95-d8c2-4624-8ec7-2635bd6bcc89
		sourceLineageTag: cc541564-b35a-416e-9d29-dc25da6d515a
		dataCategory: Uncategorized

	measure 'Aantal objecten op bestekparagraaf' = EXTERNALMEASURE("Aantal objecten op bestekparagraaf", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten
		lineageTag: 6a47f62f-3696-4413-bbec-db259985fd61
		sourceLineageTag: 1c630f06-9a9d-4c2a-8028-3ea80c3406d2
		dataCategory: Uncategorized

	measure 'Aantal unieke objecten op bestekparagraaf' = EXTERNALMEASURE("Aantal unieke objecten op bestekparagraaf", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten
		lineageTag: de82ac9f-1587-4989-809c-19903315dec3
		sourceLineageTag: 68541f61-9635-4d19-999f-d9be71070bdb
		dataCategory: Uncategorized

	measure 'Aantal installaties in database' = EXTERNALMEASURE("Aantal installaties in database", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: 84a65154-3357-49c2-b99f-740ab0bf83e8
		sourceLineageTag: 16f742ee-f773-4b48-91f4-602675df5cf6
		dataCategory: Uncategorized

	measure 'Aantal objecten' = EXTERNALMEASURE("Aantal objecten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten
		lineageTag: 1b390c65-a287-4e3f-b26f-9d7a73e5127d
		sourceLineageTag: 69b26822-6ee2-4904-b858-db468abd3f5d
		dataCategory: Uncategorized

	measure 'Aantal unieke objecten op bestekparagraaf onderhoud' = EXTERNALMEASURE("Aantal unieke objecten op bestekparagraaf onderhoud", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten
		lineageTag: f3a3d6ff-c5e6-4364-b8bb-e98005231792
		sourceLineageTag: 5e7abf3b-07c2-4c59-936b-0d9484eb0249
		dataCategory: Uncategorized

	measure 'Aantal unieke objecten op bestekparagraaf storing' = EXTERNALMEASURE("Aantal unieke objecten op bestekparagraaf storing", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Objecten
		lineageTag: 9b08a939-71a5-4039-98dc-4f8d3517b6bb
		sourceLineageTag: 40dfee4a-0666-41bb-b4c3-7b4b858bac13
		dataCategory: Uncategorized

	measure 'Aantal installaties' = EXTERNALMEASURE("Aantal installaties", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: c005a5bb-3f67-4851-b9ed-f074ecfb459a
		sourceLineageTag: 49cd86af-fe71-481e-99f1-4a61e9db5b8e
		dataCategory: Uncategorized

	measure 'Aantal unieke installaties op bestekparagraaf storing zonder einddatum of einddatum in toekomst' = EXTERNALMEASURE("Aantal unieke installaties op bestekparagraaf storing zonder einddatum of einddatum in toekomst", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: c5790b6a-48af-46d7-a93e-e666c775fc83
		sourceLineageTag: 9355c7d0-ac6e-45de-bd59-ffdd0ac78a42
		dataCategory: Uncategorized

	measure 'Aantal installaties met bouwjaar' = EXTERNALMEASURE("Aantal installaties met bouwjaar", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Installaties
		lineageTag: af593a66-783a-47a7-a228-db67144acf65
		sourceLineageTag: 323d89b6-0b1e-464d-8738-641d1ab8c1d1
		dataCategory: Uncategorized

	measure '% urenstaat projectboekingen t.o.v. salaris' = EXTERNALMEASURE("% urenstaat projectboekingen t.o.v. salaris", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Ratios en verschillen
		lineageTag: af5e1c46-7937-4a9f-9a96-8baf2876c82a
		sourceLineageTag: d1dcf1f8-d0b1-4454-a677-29373c323b61
		dataCategory: Uncategorized

	measure '% urenstaat totaal t.o.v. salaris' = EXTERNALMEASURE("% urenstaat totaal t.o.v. salaris", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren
		lineageTag: 0af74d93-8140-49d6-955c-48dc66cbc684
		sourceLineageTag: a26f292c-34fa-4d44-8e73-20e0af524a09
		dataCategory: Uncategorized

	measure 'Aantal openstaande documenten' = EXTERNALMEASURE("Aantal openstaande documenten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.01 Financieel\Algemeen
		lineageTag: e4f0982c-6513-4bf3-a6a2-ecbbbcc17a7d
		sourceLineageTag: 47dc8f7d-5b0b-4e8b-9dfc-e382bedf951f
		dataCategory: Uncategorized

	measure 'Achtergrond kleur melding geselecteerde rekeningschemas' = EXTERNALMEASURE("Achtergrond kleur melding geselecteerde rekeningschemas", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: ad0a4004-e70e-4f95-af9b-a707b19d5be8
		sourceLineageTag: ae9c34dd-0911-48cb-aea0-c1045925c6bf
		dataCategory: Uncategorized

	measure 'Achtergrond kleur waarschuwing niet compleet rekeningschema balans' = EXTERNALMEASURE("Achtergrond kleur waarschuwing niet compleet rekeningschema balans", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 601501ab-63e3-44fc-92f5-b536ea5a9a0d
		sourceLineageTag: 81cbeb07-81be-46e8-96c6-cb590b7e322f
		dataCategory: Uncategorized

	measure 'Achtergrond kleur waarschuwing niet compleet rekeningschema W&V' = EXTERNALMEASURE("Achtergrond kleur waarschuwing niet compleet rekeningschema W&V", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: f2344bd8-09b0-4558-ae71-3fb204668832
		sourceLineageTag: 1d97be28-6d2a-4525-8cde-31ceca247de3
		dataCategory: Uncategorized

	measure Bank = EXTERNALMEASURE("Bank", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank
		lineageTag: d05fc652-a48c-4cb2-8f17-29ba6b004093
		sourceLineageTag: bf265082-d1c0-4f7e-8882-055a69ff39b3
		dataCategory: Uncategorized

	measure 'Bank met voorfinanciering' = EXTERNALMEASURE("Bank met voorfinanciering", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 88053080-0e73-4a0c-82ca-011174096eff
		sourceLineageTag: 89678dcc-3e19-43c4-aa5a-322c34ad7f97
		dataCategory: Uncategorized

	measure 'Boekdatum bijgewerkt tot' = EXTERNALMEASURE("Boekdatum bijgewerkt tot", DATETIME, "DirectQuery to AS - SSM")
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: ea8fa841-63ff-4930-ac90-b96120f3a41d
		sourceLineageTag: 8d233b2c-b69e-49e2-bf10-226b094702ce
		dataCategory: Uncategorized

	measure 'Controle einddatum - type 1' = EXTERNALMEASURE("Controle einddatum - type 1", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 770da271-7b08-49c0-8a69-3fde2cab250d
		sourceLineageTag: 5742ccac-9785-4b87-873b-ac91d85a8218
		dataCategory: Uncategorized

	measure 'Controle einddatum - type 3' = EXTERNALMEASURE("Controle einddatum - type 3", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 59a707ea-9c9e-4a1f-a317-76ff53c87167
		sourceLineageTag: 3cb04f95-0a21-4f91-b215-d70174b91bf6
		dataCategory: Uncategorized

	measure 'Controle einddatum - type 4' = EXTERNALMEASURE("Controle einddatum - type 4", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: d41d2ed4-8b85-44a3-b58b-ad6e8cd938f5
		sourceLineageTag: b4c067d2-f27b-46c1-9c12-0c75b6d99c70
		dataCategory: Uncategorized

	measure 'Controle einddatum rekeningschema - goed' = EXTERNALMEASURE("Controle einddatum rekeningschema - goed", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 3871423f-b948-48c3-bb51-e419bae95095
		sourceLineageTag: 3857ada4-0d8e-4536-95ca-bcc55d326867
		dataCategory: Uncategorized

	measure 'Controle einddatum rekeningschema - slecht' = EXTERNALMEASURE("Controle einddatum rekeningschema - slecht", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 0584b63f-72a7-481e-bb83-19167ba3b8eb
		sourceLineageTag: cd3642f1-2e43-469e-9357-10b5a813a3eb
		dataCategory: Uncategorized

	measure 'Controle einddatum rekeningschema - slecht - achtergrond' = EXTERNALMEASURE("Controle einddatum rekeningschema - slecht - achtergrond", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 12b1c95c-7925-4ed8-b680-785595d7aaf2
		sourceLineageTag: d98f6fc1-c13c-4a04-9580-09864a5a039b
		dataCategory: Uncategorized

	measure 'Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema' = EXTERNALMEASURE("Controle niet gekoppelde balans rubrieken geselecteerd rekeningschema", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: bc895b8d-5df5-4c34-829c-f609559593bf
		sourceLineageTag: 0b30994f-6f70-4658-9bf7-9f0ae4819898
		dataCategory: Uncategorized

	measure 'Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema' = EXTERNALMEASURE("Controle niet gekoppelde W&V rubrieken geselecteerd rekeningschema", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 1226f342-1e7a-4903-99ab-6a63b150ed2f
		sourceLineageTag: 19fc008a-a100-4097-a910-a628c5ccead0
		dataCategory: Uncategorized

	measure 'Credit Balans ongeacht rekeningschema' = EXTERNALMEASURE("Credit Balans ongeacht rekeningschema", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: e6ef4788-fdc1-41a2-b898-76982a029aef
		sourceLineageTag: 196fd3da-b185-4771-a088-f22e1d0cc262
		dataCategory: Uncategorized

	measure Crediteuren = EXTERNALMEASURE("Crediteuren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 9ce0d804-51f5-4c38-97de-dafdf2d9ef24
		sourceLineageTag: 2a8c9f58-0753-4ba6-a76d-e191ec6cb7b2
		dataCategory: Uncategorized

	measure 'Crediteuren neg' = EXTERNALMEASURE("Crediteuren neg", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 918792f1-ee75-4a56-9f41-4127c0b02e71
		sourceLineageTag: a957d891-6233-473a-acc2-860eefd58e54
		dataCategory: Uncategorized

	measure 'Current ratio' = EXTERNALMEASURE("Current ratio", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 6a0d766c-0134-4149-9a67-4ddc14d0caa1
		sourceLineageTag: 22aa0df9-cda5-44bc-ad28-e0ae41d72e78
		dataCategory: Uncategorized

	measure 'Debet Balans ongeacht rekeningschema' = EXTERNALMEASURE("Debet Balans ongeacht rekeningschema", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: ed71fd7f-e54a-4917-be04-1991da419cad
		sourceLineageTag: df2d68a6-4ae9-487d-b2ba-6db60610606f
		dataCategory: Uncategorized

	measure Debiteuren = EXTERNALMEASURE("Debiteuren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 53034d8e-1390-4304-82ef-3e896e1b03b6
		sourceLineageTag: eb0dec69-682a-4fad-98b2-70362a51592d
		dataCategory: Uncategorized

	measure 'Eerste datum afgesloten periode' = EXTERNALMEASURE("Eerste datum afgesloten periode", DATETIME, "DirectQuery to AS - SSM")
		formatString: d\-m\-yyyy
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: 116409da-e53f-4c4b-bce9-a5b6f52ec195
		sourceLineageTag: ee305f68-2696-407a-a84a-93322efd9cc1
		dataCategory: Uncategorized

	measure 'Goal Current ratio' = EXTERNALMEASURE("Goal Current ratio", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.00
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 6e35d23a-c1dd-4dd0-bf27-95f297cde9e0
		sourceLineageTag: 4ca031b4-eb8a-45eb-8903-2f27512c6ed4
		dataCategory: Uncategorized

	measure 'Jaar bijgewerkt tot' = EXTERNALMEASURE("Jaar bijgewerkt tot", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: 08c6e5b6-223a-408f-aaf1-0fe03c83ae14
		sourceLineageTag: 597f32d0-3ec5-456c-8a2c-9fdee8ee1444
		dataCategory: Uncategorized

	measure 'Jaar en einddatum laatste afgesloten periode' = EXTERNALMEASURE("Jaar en einddatum laatste afgesloten periode", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: 012cdc9e-dd78-4978-bae7-d8cd23be7107
		sourceLineageTag: eb3814ba-146c-476e-82a1-a4cfc4f93a25
		dataCategory: Uncategorized

	measure 'Jaar LY en einddatum LY laatste afgesloten periode' = EXTERNALMEASURE("Jaar LY en einddatum LY laatste afgesloten periode", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: d228e6e0-df0d-4b7a-bb81-a0cd90371ae4
		sourceLineageTag: 41801a7e-e2f5-40bc-bf5f-41fb3516d724
		dataCategory: Uncategorized

	measure 'Laatste facturatie datum' = EXTERNALMEASURE("Laatste facturatie datum", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: 8e6a157c-3477-43a6-8324-6e5a2f9fc5f0
		sourceLineageTag: 964cfd99-8b44-4b73-8415-0799fb534ca8
		dataCategory: Uncategorized

	measure 'Maand laatste afgesloten periode' = EXTERNALMEASURE("Maand laatste afgesloten periode", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: 24a0e119-355d-407c-bedc-bdd37863d6f5
		sourceLineageTag: 56b78b18-71f3-48ea-a0cf-10f72b55f3bb
		dataCategory: Uncategorized

	measure 'Melding aantal geselecteerde rekeningschemas' = EXTERNALMEASURE("Melding aantal geselecteerde rekeningschemas", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 98c6f1c1-d4b6-499b-8ce0-d396f4b46adc
		sourceLineageTag: 6e859e2f-882d-42f0-89d6-012900532325
		dataCategory: Uncategorized

	measure 'Melding periode YTDLY' = EXTERNALMEASURE("Melding periode YTDLY", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: ef4ceb9e-e515-4d58-8491-eabda7e7da79
		sourceLineageTag: 1ce2a9e7-e633-4a7a-a44c-add5be67762d
		dataCategory: Uncategorized

	measure 'melding resultaat cumulatief' = EXTERNALMEASURE("melding resultaat cumulatief", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 329d40a5-bbc6-4a9c-a314-42477677de16
		sourceLineageTag: 11f9c7c5-b15a-4e86-a800-3d8aa523ef23
		dataCategory: Uncategorized

	measure 'melding resultaat cumulatief LY' = EXTERNALMEASURE("melding resultaat cumulatief LY", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: d75cdfc4-7793-4233-bfdd-34a6c8c534cd
		sourceLineageTag: ba2b4577-4529-427d-9346-9b954d48225c
		dataCategory: Uncategorized

	measure 'melding resultaat per boekingsperiode' = EXTERNALMEASURE("melding resultaat per boekingsperiode", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: cd7c4719-53cc-4937-83b2-795bc593597d
		sourceLineageTag: bfa54834-9225-43a7-9025-26bf4ac1abb6
		dataCategory: Uncategorized

	measure 'melding resultaat per boekingsperiode LY' = EXTERNALMEASURE("melding resultaat per boekingsperiode LY", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 0c4eca0c-6973-4e96-8347-a04cfc64bc30
		sourceLineageTag: 0a43e3b4-758b-479f-9d42-55d6a85f562c
		dataCategory: Uncategorized

	measure 'Quick ratio' = EXTERNALMEASURE("Quick ratio", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: 55b28a41-2c72-4bf9-ad2e-35699558cd49
		sourceLineageTag: 73ca2cd0-05c3-4c15-a30c-c693b74ee61d
		dataCategory: Uncategorized

	measure 'resultaat W&V ongeacht rekeningschema' = EXTERNALMEASURE("resultaat W&V ongeacht rekeningschema", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: 614ea697-e2b4-4420-97eb-fbcf7ef62c23
		sourceLineageTag: d06a8112-c7f0-4a74-9a8a-2058ea83c632
		dataCategory: Uncategorized

	measure Salarissen = EXTERNALMEASURE("Salarissen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren
		lineageTag: 5ab28415-f294-4a4e-859c-9b3274c28be4
		sourceLineageTag: 8e5926d7-73e3-43ad-8d9a-76fc91f5734f
		dataCategory: Uncategorized

	measure tussenkop_1 = EXTERNALMEASURE("tussenkop_1", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 92f20c36-479e-4924-bdbe-8191ea17cde9
		sourceLineageTag: 7fdc3f81-69b3-4b4c-900c-2f69e152bca3
		dataCategory: Uncategorized

	measure tussenkop_2 = EXTERNALMEASURE("tussenkop_2", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 04df91e7-6ff0-4685-b5bb-b60e6f336705
		sourceLineageTag: 7aad163e-aa48-4529-b0fa-04d24e5ea840
		dataCategory: Uncategorized

	measure tussenkop_3 = EXTERNALMEASURE("tussenkop_3", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 21ec33e3-9dcc-495d-bf2e-f3c90e9fbbac
		sourceLineageTag: a9b22628-025b-4f03-887d-d8bb45365180
		dataCategory: Uncategorized

	measure 'Urenstaat kosten niet op project' = EXTERNALMEASURE("Urenstaat kosten niet op project", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren
		lineageTag: c75cf345-471f-4d92-9dda-985a9f2167d1
		sourceLineageTag: d0b82be2-5ce8-4492-b470-21d7b05a32aa
		dataCategory: Uncategorized

	measure 'Urenstaat kosten op project' = EXTERNALMEASURE("Urenstaat kosten op project", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren
		lineageTag: 59ce9a4e-bfdc-4106-8091-db725472455f
		sourceLineageTag: de06de6c-da07-4b19-ae83-06c3859b7d5e
		dataCategory: Uncategorized

	measure 'Urenstaat tegenboeking' = EXTERNALMEASURE("Urenstaat tegenboeking", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Salarissen en uren
		lineageTag: 9668821e-7a7d-45ac-83f3-6243fba6e1db
		sourceLineageTag: a1899ca5-6049-410b-a247-a5e27a996e0f
		dataCategory: Uncategorized

	measure Voorfinanciering = EXTERNALMEASURE("Voorfinanciering", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering
		lineageTag: e0fd054f-c845-4f74-a412-238745d6e34c
		sourceLineageTag: b410a0e2-8389-4748-ad05-54eca1c2a17a
		dataCategory: Uncategorized

	measure Voorraad = EXTERNALMEASURE("Voorraad", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Balans\Liquiditeit
		lineageTag: d9e4d942-3167-4162-a69c-5969fad1a2ea
		sourceLineageTag: c41b7830-efd9-4a05-8bdc-360a21c13cf0
		dataCategory: Uncategorized

	measure 'Waarschuwing niet compleet rekeningschema Balans' = EXTERNALMEASURE("Waarschuwing niet compleet rekeningschema Balans", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 504c5086-e818-4914-a3ab-35bde5880f11
		sourceLineageTag: cae77281-57a7-4b0e-99f9-73ced23a0478
		dataCategory: Uncategorized

	measure 'Waarschuwing niet compleet rekeningschema W&V' = EXTERNALMEASURE("Waarschuwing niet compleet rekeningschema W&V", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 1ff558c3-ed15-4834-9259-1739c642007c
		sourceLineageTag: e3dbc6b9-4263-452b-9c9b-db58719d069c
		dataCategory: Uncategorized

	measure 'Week bijgewerkt tot' = EXTERNALMEASURE("Week bijgewerkt tot", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Algemeen
		lineageTag: 421538e2-ed84-4f3a-8123-eaa85c2f0546
		sourceLineageTag: 1c291ed8-0e42-4f12-90ef-0b4a12687418
		dataCategory: Uncategorized

	measure '% overuren' = EXTERNALMEASURE("% overuren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 391965b7-41cf-4629-8155-c43064869868
		sourceLineageTag: 6aa08b92-8cb3-4a6c-9c93-cf9a364267da
		dataCategory: Uncategorized

	measure '% reistijd direct' = EXTERNALMEASURE("% reistijd direct", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 6a167b77-c464-4edc-a48d-595401411273
		sourceLineageTag: 9bf9167e-0c9d-4abd-8818-44ee0eb384cd
		dataCategory: Uncategorized

	measure '% reistijd indirect' = EXTERNALMEASURE("% reistijd indirect", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: a3a7b6d8-f57a-444f-aa43-38b2c88350aa
		sourceLineageTag: 1000e1b7-260e-48eb-96fb-e5fe90db8a9b
		dataCategory: Uncategorized

	measure 'Bron contracturen' = EXTERNALMEASURE("Bron contracturen", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.02 HR
		lineageTag: 35283ee5-9b08-4706-aea3-350a0fcb1ee0
		sourceLineageTag: 94d4629e-93ab-4dfb-8b99-7dcdf54942af
		dataCategory: Uncategorized

	measure 'Contracturen excl. saldo uren' = EXTERNALMEASURE("Contracturen excl. saldo uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 3ff65150-80aa-4467-b3f5-3c67c34a3cc0
		sourceLineageTag: aa190111-dfb4-4905-97a6-cc860e8b4645
		dataCategory: Uncategorized

	measure 'Directe (productieve) uren totaal' = EXTERNALMEASURE("Directe (productieve) uren totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 1241541e-be91-4bdb-a9ea-311ebcde3b1f
		sourceLineageTag: da8fd2d1-cd23-4625-be0c-db0dfec2986d
		dataCategory: Uncategorized

	measure 'Directe reisuren eigen personeel' = EXTERNALMEASURE("Directe reisuren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 51b9c38a-467d-46d5-b783-df9235de66e0
		sourceLineageTag: 05f6b669-aaa1-48e1-b135-557f78a36a56
		dataCategory: Uncategorized

	measure 'Directe uren eigen personeel' = EXTERNALMEASURE("Directe uren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: d4180844-564f-49a5-8847-d1db4e6a0669
		sourceLineageTag: 7410ceb2-0cb0-4448-9dc2-55ab686b9822
		dataCategory: Uncategorized

	measure 'Directe uren ingeleend personeel' = EXTERNALMEASURE("Directe uren ingeleend personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: d9116601-6812-4124-8737-09b19ed87692
		sourceLineageTag: d8f89ae4-bd32-48ff-93ac-da5355fa361e
		dataCategory: Uncategorized

	measure 'Directe werkuren zonder reizen eigen personeel' = EXTERNALMEASURE("Directe werkuren zonder reizen eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: f7895ba7-22d5-45a4-9db1-7b84942c3d7f
		sourceLineageTag: 946fb02a-2a10-4b59-ad82-d0ba6ad103b8
		dataCategory: Uncategorized

	measure 'Doel ziekteverzuim' = EXTERNALMEASURE("Doel ziekteverzuim", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: c7031a36-2402-40d8-a1c9-52ad47e981b8
		sourceLineageTag: 57d3a12d-f695-4c4c-8f5e-cc3670a300b7
		dataCategory: Uncategorized

	measure Feestdagen = EXTERNALMEASURE("Feestdagen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: b80b6f8c-f98e-4cf2-a95d-245dd8340068
		sourceLineageTag: e81ef6e5-05dd-4b2b-bd16-58b7416c7922
		dataCategory: Uncategorized

	measure 'FTE beginstand' = EXTERNALMEASURE("FTE beginstand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: a45e2020-e763-48e6-9249-9b2fc69b88af
		sourceLineageTag: acff92bb-c7d2-46d9-a4ae-5c9611c54df5
		dataCategory: Uncategorized

	measure 'FTE eindstand' = EXTERNALMEASURE("FTE eindstand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: e75080f5-4d1b-4c4f-aac9-5e722b7b6c8f
		sourceLineageTag: adfafdb9-17d2-41b1-aae3-ff23f5803579
		dataCategory: Uncategorized

	measure 'FTE uren per week' = EXTERNALMEASURE("FTE uren per week", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: d9a7f3c3-b93f-4244-8fd6-8244b01f42f7
		sourceLineageTag: e7287dba-1733-464b-b798-7234b0f342eb
		dataCategory: Uncategorized

	measure 'Gerealiseerde Contracturen' = EXTERNALMEASURE("Gerealiseerde Contracturen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 4db50f32-3248-4d08-aabe-9c285a6257fe
		sourceLineageTag: 488369f3-535a-4d07-8e69-3565fcd61988
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren excl. saldo-uren' = EXTERNALMEASURE("Gerealiseerde uren excl. saldo-uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 1eedf96e-bf5d-4b0c-b090-d278691f2315
		sourceLineageTag: 885bf4d0-c1b8-4266-8e9a-ac5eb6e2aa47
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren excl. saldo-uren eigen personeel' = EXTERNALMEASURE("Gerealiseerde uren excl. saldo-uren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 3509cbc9-cc85-45f0-b0c4-440578fe4bca
		sourceLineageTag: 3c3c546c-bcc9-4588-a791-353300778c45
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren totaal incl. verlofsaldo uren' = EXTERNALMEASURE("Gerealiseerde uren totaal incl. verlofsaldo uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 5d954c50-e837-4e23-83c0-26b00152cbe1
		sourceLineageTag: 4b6f4d76-6f80-435f-bb2c-d344e27c97f8
		dataCategory: Uncategorized

	measure 'Headcount beginstand' = EXTERNALMEASURE("Headcount beginstand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: 5c733e80-01f2-43af-888c-59f656cbcd92
		sourceLineageTag: 1a47985e-04fc-4600-b6a3-1b5f3c843669
		dataCategory: Uncategorized

	measure 'Headcount eindstand' = EXTERNALMEASURE("Headcount eindstand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: c9137579-ba6e-49b2-b051-b7ae9c55b038
		sourceLineageTag: 2cc34a99-0e7d-40c4-93a1-7fdb815de91e
		dataCategory: Uncategorized

	measure 'Indirect % tov direct' = EXTERNALMEASURE("Indirect % tov direct", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 842ece27-0c4b-437d-a354-b855594c8ec4
		sourceLineageTag: ab986e48-160f-489e-9d2c-cb8a72e568a1
		dataCategory: Uncategorized

	measure 'Indirecte reisuren eigen personeel' = EXTERNALMEASURE("Indirecte reisuren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 8873b86e-3906-4d9d-b617-037187bcb153
		sourceLineageTag: 87566ce3-bd8a-4111-bb0e-c0fd047e8f16
		dataCategory: Uncategorized

	measure 'Indirecte uren eigen personeel' = EXTERNALMEASURE("Indirecte uren eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 2696edb5-4073-443d-aa1f-43ba02bb733d
		sourceLineageTag: de754491-a2b7-4d7d-852a-1866bf63b8c3
		dataCategory: Uncategorized

	measure 'Indirecte uren ingeleend personeel' = EXTERNALMEASURE("Indirecte uren ingeleend personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 0ce8615e-12b1-4da2-9f32-399cac1d70e8
		sourceLineageTag: f74b0e28-ff09-4d51-84b6-bd14ac44e396
		dataCategory: Uncategorized

	measure 'Indirecte uren totaal' = EXTERNALMEASURE("Indirecte uren totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 5528af89-1393-4df3-9a3c-fa0a601063df
		sourceLineageTag: 944e69a1-3f48-40ee-b6bc-a2a846817955
		dataCategory: Uncategorized

	measure 'Medewerker mutatie' = EXTERNALMEASURE("Medewerker mutatie", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Medewerkers
		lineageTag: d2b518dd-9ad4-4db4-b438-44acc19ad7a2
		sourceLineageTag: 5e0cc25b-dc0f-4ee7-baea-02de1062d736
		dataCategory: Uncategorized

	measure 'Medewerkers in dienst' = EXTERNALMEASURE("Medewerkers in dienst", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Medewerkers
		lineageTag: a654fc78-36c0-4c78-98da-7648ccb25021
		sourceLineageTag: 79bd7818-a805-44d3-955d-f2a82ff61553
		dataCategory: Uncategorized

	measure 'Medewerkers uit dienst' = EXTERNALMEASURE("Medewerkers uit dienst", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Medewerkers
		lineageTag: cd28a0ec-3510-4ca8-a3e0-6d5c5bd64e20
		sourceLineageTag: 4ca726d7-0375-4afe-9350-73f48176c453
		dataCategory: Uncategorized

	measure 'Melding gerealiseerde uren' = EXTERNALMEASURE("Melding gerealiseerde uren", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: b5170e82-3b4e-4d7c-b07c-53c1975dc00c
		sourceLineageTag: e66e5ccb-7883-46e6-8eb8-17bbe1f218b0
		dataCategory: Uncategorized

	measure 'Melding Headcount' = EXTERNALMEASURE("Melding Headcount", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 0f0c33ba-f5fe-46ec-b779-31ecb3e084cb
		sourceLineageTag: 77a15116-5929-4357-a185-e84d4ccaadb8
		dataCategory: Uncategorized

	measure 'Melding ingeleend personeel niet geselecteerd' = EXTERNALMEASURE("Melding ingeleend personeel niet geselecteerd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 88649a7b-c9e9-42ab-a7e9-fe07d170f023
		sourceLineageTag: 60793e22-6d74-4404-9728-f2452fc1aea3
		dataCategory: Uncategorized

	measure 'Melding ingeleend personeel wel geselecteerd' = EXTERNALMEASURE("Melding ingeleend personeel wel geselecteerd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: bf587860-9400-4da0-98aa-8f518573987e
		sourceLineageTag: 222c4b9d-a23b-4672-a06f-27b6b6ae1724
		dataCategory: Uncategorized

	measure 'Melding medewerkers in en uit dienst' = EXTERNALMEASURE("Melding medewerkers in en uit dienst", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 39d58434-8e47-4132-8d70-45a6b8c93de4
		sourceLineageTag: a6860abd-602c-48b4-9b81-4f995cbd9601
		dataCategory: Uncategorized

	measure 'Melding productiviteit eigen personeel' = EXTERNALMEASURE("Melding productiviteit eigen personeel", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: f12bf92d-f3c7-4345-b0f3-ff3b4fd02a4d
		sourceLineageTag: 17d846ee-c83c-43cd-b5b4-14b58717c2f2
		dataCategory: Uncategorized

	measure 'Melding verlofsaldo' = EXTERNALMEASURE("Melding verlofsaldo", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: 21290bca-7c18-461f-904f-a091171aa6b7
		sourceLineageTag: cdd2f2e1-28e3-4d5b-bf6d-c0b4894f3389
		dataCategory: Uncategorized

	measure 'Melding ziekteverzuim' = EXTERNALMEASURE("Melding ziekteverzuim", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.99 Overig\Meldingen
		lineageTag: ce576b20-2d1b-440b-92bc-cd3b0108f1bc
		sourceLineageTag: 6b885e7a-30b4-417c-81fe-7aef889cac26
		dataCategory: Uncategorized

	measure Overuren = EXTERNALMEASURE("Overuren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 1931c2ce-93f4-4973-865b-d2fae9e6ed5a
		sourceLineageTag: 198333a4-9a0a-4e39-85fd-438e47189a8b
		dataCategory: Uncategorized

	measure 'Productiviteit Eigen personeel' = EXTERNALMEASURE("Productiviteit Eigen personeel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: b1a7d1a5-8163-4ff6-a13f-f46c4e3a0cff
		sourceLineageTag: e7028231-ba56-44f1-9ff4-e3df30c34108
		dataCategory: Uncategorized

	measure 'Productiviteit totaal' = EXTERNALMEASURE("Productiviteit totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: a4e3143f-6d8b-425e-bc2f-a831b8f1ffe9
		sourceLineageTag: d52f9b17-ba8a-4e73-99c7-bb5ee9e16eed
		dataCategory: Uncategorized

	measure 'Verlof %' = EXTERNALMEASURE("Verlof %", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 307aaa6c-495d-4ae7-8dac-869e17e06880
		sourceLineageTag: d2cfa66d-90fa-4cda-8b58-eec134f3a9ef
		dataCategory: Uncategorized

	measure Verlofsaldo = EXTERNALMEASURE("Verlofsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: 696bfc8b-54ac-4ea6-bf94-b917d542b1b2
		sourceLineageTag: 1229a827-15c2-49fd-adc3-a553ef614ef5
		dataCategory: Uncategorized

	measure 'Verlofsaldo beginstand' = EXTERNALMEASURE("Verlofsaldo beginstand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: 4af931da-3e34-4ba0-abd7-cb8df55264e7
		sourceLineageTag: 02c4fdf1-442c-442c-9020-e8cb093200e4
		dataCategory: Uncategorized

	measure 'Verlofsaldo beginstand variabel format' = EXTERNALMEASURE("Verlofsaldo beginstand variabel format", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: cf10649e-a3c2-4ebd-bb79-c4633bbfebf1
		sourceLineageTag: 6c29f51a-a68d-448d-89f7-4487bd135c29
		dataCategory: Uncategorized

	measure 'Verlofsaldo eindstand' = EXTERNALMEASURE("Verlofsaldo eindstand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: 029f4357-7115-4805-acb3-15de151b287c
		sourceLineageTag: ce416c7e-3957-48a1-a5a7-980130445306
		dataCategory: Uncategorized

	measure 'Verlofsaldo eindstand variabel format' = EXTERNALMEASURE("Verlofsaldo eindstand variabel format", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.02 Best practice HR
		lineageTag: fa133ed7-de07-43ba-b5a1-6bbfc6bfe145
		sourceLineageTag: da58902f-2801-4ef4-b647-26aaeae501c1
		dataCategory: Uncategorized

	measure Verlofuren = EXTERNALMEASURE("Verlofuren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 724c930f-76b7-4eca-9cec-6b12cd568c7a
		sourceLineageTag: f1cb5317-4a51-45d7-bf7b-c85da0fc469f
		dataCategory: Uncategorized

	measure 'Ziekte uren' = EXTERNALMEASURE("Ziekte uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: 2ac86ae5-d2e1-44a0-98a2-f029abbe137f
		sourceLineageTag: 599d5db0-e5d1-4f7a-8b07-f21e6625a9f3
		dataCategory: Uncategorized

	measure 'Ziekte verzuim - Rolling Average 12 maanden' = EXTERNALMEASURE("Ziekte verzuim - Rolling Average 12 maanden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: b7e95b64-b9e9-44de-9fbc-182a33d5d406
		sourceLineageTag: 1a9f5d05-0622-44bd-9bef-bb51d5760f44
		dataCategory: Uncategorized

	measure Ziekteverzuim = EXTERNALMEASURE("Ziekteverzuim", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: 074da1e1-9070-4119-aba9-1cdb5497d317
		sourceLineageTag: d2ea7cc2-f30a-442b-8c04-d3b25a9b0f03
		dataCategory: Uncategorized

	measure 'Ziekteverzuim zonder blank' = EXTERNALMEASURE("Ziekteverzuim zonder blank", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Semantisch model\1.02 HR\Ratios
		lineageTag: fd0c66c2-fa60-4df7-9401-923ad2f0633d
		sourceLineageTag: a9e0074e-e649-4d76-b7fb-40916035e970
		dataCategory: Uncategorized

	measure 'openstaande bankmutaties' = EXTERNALMEASURE("openstaande bankmutaties", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Openstaande bankafschriften
		lineageTag: fea9496c-51c2-4030-ae37-c07781147d8c
		sourceLineageTag: 984f135e-ee92-429e-9535-e2e0d1ffc1b7
		dataCategory: Uncategorized

	measure 'openstaande bankmutaties te betalen' = EXTERNALMEASURE("openstaande bankmutaties te betalen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Openstaande bankafschriften
		lineageTag: 229c415a-bc69-4271-ab3b-20f64fa2aad7
		sourceLineageTag: 6d442b14-747e-408b-8300-f82757b4d4f9
		dataCategory: Uncategorized

	measure 'openstaande bankmutaties te ontvangen' = EXTERNALMEASURE("openstaande bankmutaties te ontvangen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Openstaande bankafschriften
		lineageTag: ca3fbe8d-8f32-4f0f-a871-85b40279262a
		sourceLineageTag: 4a2416be-be40-4c4c-8796-4cc0d8bc9b59
		dataCategory: Uncategorized

	measure 'BTW af te dragen' = EXTERNALMEASURE("BTW af te dragen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\BTW
		lineageTag: 9ffa6e33-ab26-4744-bd5d-9ac604488fab
		sourceLineageTag: 6fb1cfd4-d226-4fae-aec4-21dd809b5377
		dataCategory: Uncategorized

	measure 'BTW prognose (huidige inkoop- en verkoopfacturen)' = EXTERNALMEASURE("BTW prognose (huidige inkoop- en verkoopfacturen)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\BTW
		lineageTag: 34d6fa8e-c21a-485c-b7dc-0469ef40bc4f
		sourceLineageTag: 24d3b8fc-ac4e-4543-8971-cda59f6bf8e3
		dataCategory: Uncategorized

	measure 'BTW te vorderen' = EXTERNALMEASURE("BTW te vorderen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\BTW
		lineageTag: b1eaf28e-2a7b-4d85-bd5e-4b0d1401eb59
		sourceLineageTag: f83c368d-4f6b-412d-9681-971217a49518
		dataCategory: Uncategorized

	measure 'Bank beginsaldo' = EXTERNALMEASURE("Bank beginsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank
		lineageTag: cbd12cf7-0f24-4d30-9efc-fad72024e8bc
		sourceLineageTag: d0e4a205-fd11-44f5-add1-22622c495b69
		dataCategory: Uncategorized

	measure 'Bank Credit' = EXTERNALMEASURE("Bank Credit", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank
		lineageTag: c18403a5-9c7a-4ae1-8c16-c853c70e6b8c
		sourceLineageTag: 377e76f0-558d-41e2-b0c8-b91b207304ff
		dataCategory: Uncategorized

	measure 'Bank Debet' = EXTERNALMEASURE("Bank Debet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank
		lineageTag: 4330b560-ad1d-4cf0-89d1-0e99403d4d0c
		sourceLineageTag: cef3f952-c9ce-4d70-ba75-5c93ceee11d6
		dataCategory: Uncategorized

	measure 'Bank eindsaldo' = EXTERNALMEASURE("Bank eindsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank
		lineageTag: aecd8eb4-e355-4c25-b165-d710b562e2c3
		sourceLineageTag: 39b2251a-82cb-43e9-b529-3ceebe8df580
		dataCategory: Uncategorized

	measure 'Mutatie totaal' = EXTERNALMEASURE("Mutatie totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank
		lineageTag: 48d241f8-14b7-4c64-ae4a-aa11f55494d3
		sourceLineageTag: ed19cfdf-51c6-4ae1-9c86-a3ee0e6b58b5
		dataCategory: Uncategorized

	measure 'Mutatie Debet' = EXTERNALMEASURE("Mutatie Debet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank
		lineageTag: 115a1841-34a9-4cb9-ba77-354dc289fb3c
		sourceLineageTag: d5213e05-8d6e-4095-bb0a-4b63f0cafff5
		dataCategory: Uncategorized

	measure 'Mutatie Credit - Debet' = EXTERNALMEASURE("Mutatie Credit - Debet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank
		lineageTag: 41c03bc7-0c3c-40ad-b914-af7c9f451cbc
		sourceLineageTag: 75f2303b-0bc3-4259-b862-870b0c1175d3
		dataCategory: Uncategorized

	measure 'Mutatie Credit' = EXTERNALMEASURE("Mutatie Credit", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Mutatie op bank
		lineageTag: 4facfcf0-327d-43f4-9953-68b40785f53d
		sourceLineageTag: ee5edcbb-f962-43da-b385-3ee3fd33e96a
		dataCategory: Uncategorized

	measure 'Laatst beschikbare standdatum' = EXTERNALMEASURE("Laatst beschikbare standdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: General Number
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 28ae3ede-4fbf-42bb-bad6-a5351f31e5ce
		sourceLineageTag: 95adb497-5a07-4240-9a51-243ae112b39e
		dataCategory: Uncategorized

	measure 'Laatste standdatum geselecteerd' = EXTERNALMEASURE("Laatste standdatum geselecteerd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: ada7425f-e1fd-4c8c-9304-42ec33c6af2d
		sourceLineageTag: e251dc8a-95ad-41d8-82f0-cb5ef11e4837
		dataCategory: Uncategorized

	measure Inkopen = EXTERNALMEASURE("Inkopen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.###############;-"€"\ #,0.###############;"€"\ #,0.###############
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: ee585460-ba9b-4bde-96dc-a8a176cd8bad
		sourceLineageTag: 711a1200-be76-4d32-9975-6658caf88cec
		dataCategory: Uncategorized

	measure 'openstaande inkoopfacturen' = EXTERNALMEASURE("openstaande inkoopfacturen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: 1a68ab14-2b31-491a-89ef-e513bd3c6c7d
		sourceLineageTag: e84dfd64-b4c8-43f9-bdee-9ee132003526
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen niet vervallen' = EXTERNALMEASURE("Openstaande inkoopfacturen niet vervallen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: fcdfbb35-6ef4-4e68-bd22-9c34737d8c34
		sourceLineageTag: aafa139e-835a-406b-b5a8-5fee4519c9f2
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen per categorie' = EXTERNALMEASURE("Openstaande inkoopfacturen per categorie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: 94337fd2-4ea0-4b2e-8f50-b49bccde73db
		sourceLineageTag: f4b7e518-3402-48ec-99d6-6765da48d46f
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen vervallen' = EXTERNALMEASURE("Openstaande inkoopfacturen vervallen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: 437f52c4-8538-4a7f-8f7b-7fe306341275
		sourceLineageTag: d587b40e-7112-4e89-8519-e70fe1062c54
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen vervallen  0-30' = EXTERNALMEASURE("Openstaande inkoopfacturen vervallen  0-30", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: f8561a52-4ea3-4c8f-b550-4d9a69075f97
		sourceLineageTag: 1aee3871-5154-4d3b-9e7c-bdaf008746cf
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen vervallen  31-60' = EXTERNALMEASURE("Openstaande inkoopfacturen vervallen  31-60", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: fef20416-4c9c-4677-8ad0-fefabc4f0b7a
		sourceLineageTag: f3724cce-4fa8-44c9-a702-80f85dbfe74c
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen vervallen  61-90' = EXTERNALMEASURE("Openstaande inkoopfacturen vervallen  61-90", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: 99cf7e44-e73a-4650-85b5-775896754327
		sourceLineageTag: b5fc549a-93a6-4980-9263-0e6179dadf33
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen vervallen  91-120' = EXTERNALMEASURE("Openstaande inkoopfacturen vervallen  91-120", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: 5270b535-70da-4cce-b12a-c15aaf0e67d6
		sourceLineageTag: dc73044e-22c0-45bf-a9f5-2ae2b29c34e1
		dataCategory: Uncategorized

	measure 'Openstaande inkoopfacturen vervallen 120+' = EXTERNALMEASURE("Openstaande inkoopfacturen vervallen 120+", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Inkoop
		lineageTag: 5c81f44f-5c03-4dbf-9c45-1e989ae0aa23
		sourceLineageTag: 1b7da617-0219-4cda-a196-88c4286d649c
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen' = EXTERNALMEASURE("Openstaande verkoopfacturen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 430cdce8-6f74-4d89-b226-02fd98ee4b97
		sourceLineageTag: 1f9cc2c0-d641-4d15-8d55-bf54761de232
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen niet vervallen' = EXTERNALMEASURE("Openstaande verkoopfacturen niet vervallen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 4bb93ec8-ef8b-4b30-96b9-d04f25c81e10
		sourceLineageTag: af114f68-2e40-46de-83a8-7d5183e745e0
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen per categorie' = EXTERNALMEASURE("Openstaande verkoopfacturen per categorie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 610ecc0f-5f7e-40b9-a3ec-2acc47ffeb9c
		sourceLineageTag: cbfd15c4-ae2e-465c-9870-eda9bc5630a1
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen vervallen' = EXTERNALMEASURE("Openstaande verkoopfacturen vervallen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 96ffb0bb-b6af-42a4-8692-7bd760fafd92
		sourceLineageTag: ba3f4430-eaa6-49f0-b33f-fd3e52857902
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen vervallen  0-30' = EXTERNALMEASURE("Openstaande verkoopfacturen vervallen  0-30", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 19ed3a2e-c0c1-4d24-adbc-79e8eb1e356f
		sourceLineageTag: c4bc6728-c67e-492b-9d87-c9220f07f830
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen vervallen  31-60' = EXTERNALMEASURE("Openstaande verkoopfacturen vervallen  31-60", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 03bbfa83-b592-4ab2-b3d1-5dfff3509010
		sourceLineageTag: 946883cd-520c-4e2a-9df1-87ad3c7c5366
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen vervallen  61-90' = EXTERNALMEASURE("Openstaande verkoopfacturen vervallen  61-90", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: ede44024-277d-40fd-8c2d-eab96bb5e038
		sourceLineageTag: c347828f-8446-4f5f-bc68-d3be690dff2e
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen vervallen  91-120' = EXTERNALMEASURE("Openstaande verkoopfacturen vervallen  91-120", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 4095afb7-53f6-4942-ad7c-4fd889be990a
		sourceLineageTag: 59357ce1-09f9-4ba7-b089-9316f95ca12e
		dataCategory: Uncategorized

	measure 'Openstaande verkoopfacturen vervallen 120+' = EXTERNALMEASURE("Openstaande verkoopfacturen vervallen 120+", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 685009ad-6a06-4305-9687-5cc71f4f270b
		sourceLineageTag: 19bcef01-0f09-4e54-9015-ed1147451f02
		dataCategory: Uncategorized

	measure Verkopen = EXTERNALMEASURE("Verkopen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Verkoop
		lineageTag: 3a79f768-ff3e-414d-a8c2-eb22e0c84f48
		sourceLineageTag: 89cbb704-97e4-455c-bc59-fd516942d335
		dataCategory: Uncategorized

	measure 'Target voorfinanciering' = EXTERNALMEASURE("Target voorfinanciering", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering
		lineageTag: 85ce282d-fd61-4d62-8451-415a918edba2
		sourceLineageTag: f9ece42a-f055-4853-9acb-f463f9f83a72
		dataCategory: Uncategorized

	measure 'voorfinanciering negatief' = EXTERNALMEASURE("voorfinanciering negatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.0;-"€"\ #,0.0;"€"\ #,0.0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering
		lineageTag: 43797aa3-90e1-4d26-b661-8281a5a4bcda
		sourceLineageTag: 63613047-ea93-4cef-8781-964ff301736e
		dataCategory: Uncategorized

	measure 'voorfinanciering postitief' = EXTERNALMEASURE("voorfinanciering postitief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Openstaande banktermijnen\Voorfinanciering
		lineageTag: ad31a82d-bd14-47fa-a7bd-cf51b552bbe3
		sourceLineageTag: f0899a1c-06c7-42ad-b026-6ed89563d676
		dataCategory: Uncategorized

	measure 'Verzoek kosten  (Projectbudgetregels)' = EXTERNALMEASURE("Verzoek kosten  (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)
		lineageTag: 6aa2585b-bc01-407b-8145-8c397cf7f5bf
		sourceLineageTag: c0835202-ae08-4a43-b96d-f240c07ecbce
		dataCategory: Uncategorized

	/// Verzoek extra omzet aangevraagd via Budget Verzoek App.
	measure 'Verzoek omzet  (Projectbudgetregels)' = EXTERNALMEASURE("Verzoek omzet  (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)
		lineageTag: af107865-07f2-4e99-b850-e16e20454079
		sourceLineageTag: 35bc8daf-23b0-4596-ad5f-6fa77835fd6b
		dataCategory: Uncategorized

	measure 'Verzoek uren (Projectbudgetregels)' = EXTERNALMEASURE("Verzoek uren (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)
		lineageTag: e6ec57b1-72f7-490c-a0a1-f3080d53cff7
		sourceLineageTag: 36f07c37-5883-478a-96c5-22daa401800c
		dataCategory: Uncategorized

	measure 'Verzoek uren (Projectbudgetregels) NOT BLANK ' = EXTERNALMEASURE("Verzoek uren (Projectbudgetregels) NOT BLANK ", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)
		lineageTag: 32139a42-78d5-43e1-902b-770f464eaa2d
		sourceLineageTag: cfe33b2d-7345-4cf5-97b3-b20b5b831335
		dataCategory: Uncategorized

	measure 'Verzoek omzet (Projectbudgetregels) NOT BLANK ' = EXTERNALMEASURE("Verzoek omzet (Projectbudgetregels) NOT BLANK ", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)
		lineageTag: 6b7a65a8-5896-46bb-8f7c-03f08cb404ae
		sourceLineageTag: ab96db6a-c672-4a56-bcab-c31c0b73d508
		dataCategory: Uncategorized

	measure 'Verzoek kosten (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Verzoek kosten (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget verzoek (impliciet via Projectbudgetregels)
		lineageTag: 21b811e5-d016-4845-b195-ab3c2af3d503
		sourceLineageTag: 667438bb-85dd-4edb-a949-ec2b6be64cae
		dataCategory: Uncategorized

	measure 'Budget kosten (Projectbudgetregels)' = EXTERNALMEASURE("Budget kosten (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: ee92f18f-ef2b-44af-b4f2-61a62f02f234
		sourceLineageTag: 96538bce-53a7-47a1-bb08-68601d602503
		dataCategory: Uncategorized

	measure 'Budget kosten (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Budget kosten (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: 0bb66545-6d08-445a-a8e1-67733d110ab9
		sourceLineageTag: 79b9fdc5-7eb7-45e6-9b14-f007d9ef6275
		dataCategory: Uncategorized

	measure 'Budget kosten inkoop (Projectbudgetregels)' = EXTERNALMEASURE("Budget kosten inkoop (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: 5d076671-3d24-4356-a121-96494a7e72d8
		sourceLineageTag: c15c9554-0ee9-4e0b-9c1d-94944287f9b5
		dataCategory: Uncategorized

	measure 'Budget omzet (Projectbudgetregels)' = EXTERNALMEASURE("Budget omzet (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: ab79f5a1-e921-46c5-a4be-269d634fa5b4
		sourceLineageTag: 01592325-bc14-447c-89d5-53f5d7494838
		dataCategory: Uncategorized

	measure 'Budget omzet (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Budget omzet (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: bb11e20d-e640-48e2-bdaf-31ce73e0902a
		sourceLineageTag: f4fd55ac-6b87-4474-849b-12ad7a4da8da
		dataCategory: Uncategorized

	measure 'Budget uren (Projectbudgetregels)' = EXTERNALMEASURE("Budget uren (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: 3bcb9b69-5d8e-41c0-8fd2-f8d93f0f6356
		sourceLineageTag: 3d68aa67-0d1c-48f1-8dab-0373d79018fb
		dataCategory: Uncategorized

	measure 'Budget uren (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Budget uren (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Budget (via projectbudgetregels)
		lineageTag: 8b8064bf-7e0f-4926-aad8-129e66e00280
		sourceLineageTag: eb0e8597-13f9-4cdd-9951-fa6ac832e0e0
		dataCategory: Uncategorized

	measure 'Prognose kosten (Projectbudgetregels)' = EXTERNALMEASURE("Prognose kosten (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)
		lineageTag: 86135693-8db1-448b-8378-07d713eb7658
		sourceLineageTag: e811348e-f720-4fb7-9254-a006a03b53ce
		dataCategory: Uncategorized

	/// [Budget omzet] + [Verzoek omzet]. 
	measure 'Prognose omzet (Projectbudgetregels)' = EXTERNALMEASURE("Prognose omzet (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)
		lineageTag: 498a49f3-1d62-4d6a-9b0d-8b55ab0f96e0
		sourceLineageTag: 656f9e48-ff2b-4f15-8974-6957a5765313
		dataCategory: Uncategorized

	measure 'Prognose uren (Projectbudgetregels)' = EXTERNALMEASURE("Prognose uren (Projectbudgetregels)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)
		lineageTag: 26386aa4-38e9-4a5b-8309-47e17c98ee84
		sourceLineageTag: fb77e6d5-a3ff-45e0-ac9a-7f3d5db4c0ea
		dataCategory: Uncategorized

	measure 'Prognose uren (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Prognose uren (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)
		lineageTag: 1f02af6c-c893-4e2d-ab48-745906ec6973
		sourceLineageTag: d29dcc5f-4ea6-4125-9588-3c98f1b5f7c3
		dataCategory: Uncategorized

	measure 'Prognose omzet (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Prognose omzet (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)
		lineageTag: 2064e2b8-16bf-4867-bb54-9d503218059e
		sourceLineageTag: 5c5bb194-aea5-46ca-8ec2-7edf564dfb28
		dataCategory: Uncategorized

	measure 'Prognose kosten (Projectbudgetregels) NOT BLANK' = EXTERNALMEASURE("Prognose kosten (Projectbudgetregels) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Syntess Projectbudget en opname regels\Prognose (via projectbudgetregels)
		lineageTag: e5f89b5c-8c74-4b89-a17e-4ead26283370
		sourceLineageTag: 5017d752-69d1-47be-b620-7cfb566ee153
		dataCategory: Uncategorized

	measure '% actual en forecast t.o.v. budget' = EXTERNALMEASURE("% actual en forecast t.o.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: 9912559b-63ff-4db9-b1b3-7fd265de4390
		sourceLineageTag: a42fe7a0-28e6-40c0-b558-07d91548214e
		dataCategory: Uncategorized

	measure 'CoA actual en forecast' = EXTERNALMEASURE("CoA actual en forecast", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema
		lineageTag: d7f54ca5-d486-4939-83aa-3fbea30b4779
		sourceLineageTag: 1e873cae-5307-45de-8c0d-d7894bb3e181
		dataCategory: Uncategorized

	measure 'Controle Coa actual en forecast' = EXTERNALMEASURE("Controle Coa actual en forecast", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: c25de2cc-4ba1-49b4-814b-76402ced120f
		sourceLineageTag: 59791337-9819-4aaf-9e66-29846ec7f31d
		dataCategory: Uncategorized

	measure 'Delta actual en forecast - budget' = EXTERNALMEASURE("Delta actual en forecast - budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: 8cd084d5-7053-4d4b-b36a-84250bb9c4c1
		sourceLineageTag: c8f01c1c-2962-48ff-aa4b-4c4e97ec491d
		dataCategory: Uncategorized

	measure 'CoA Forecast mutatie' = EXTERNALMEASURE("CoA Forecast mutatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast
		lineageTag: ca4024ad-2fa7-4315-bac3-50d3b3ba44f0
		sourceLineageTag: 611c6568-1845-45d8-8538-78d6c64fa798
		dataCategory: Uncategorized

	measure 'CoA mutatie notifica budget in de standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA mutatie notifica budget in de standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget
		lineageTag: bde91d77-0bcb-482e-b07d-bdfce40b6f89
		sourceLineageTag: b2cad8f6-68c3-4031-92bc-801ad14fcbe0
		dataCategory: Uncategorized

	measure 'Budget YTD (notifica)' = EXTERNALMEASURE("Budget YTD (notifica)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Notifica
		lineageTag: 7d484fa2-97ba-4db2-90a4-4db4ff05043e
		sourceLineageTag: 98dbba47-7477-49a4-96b9-0e8009a89b7d
		dataCategory: Uncategorized

	measure 'Mutatie budget (notifica)' = EXTERNALMEASURE("Mutatie budget (notifica)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Notifica
		lineageTag: be1e2771-997e-4fa8-82a3-54d027f1d571
		sourceLineageTag: ac3ef23b-5d2f-486c-bdb3-914477c117f0
		dataCategory: Uncategorized

	measure 'Delta actual - budget (notifica)' = EXTERNALMEASURE("Delta actual - budget (notifica)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: ec0167d4-2287-4044-b9bd-dbcb838a1e69
		sourceLineageTag: 8057da90-14d7-427e-88c2-191047347d17
		dataCategory: Uncategorized

	measure 'Delta actual en forecast - budget (notifica)' = EXTERNALMEASURE("Delta actual en forecast - budget (notifica)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: ba654a52-7baa-4870-92c1-4003aae974a1
		sourceLineageTag: 035af7d0-668e-4388-8540-3baf183182b1
		dataCategory: Uncategorized

	measure '% actual en forecast t.o.v. budget (notifica)' = EXTERNALMEASURE("% actual en forecast t.o.v. budget (notifica)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: 1244295a-4757-4822-8031-fd56768cd450
		sourceLineageTag: 47b0f7ce-4960-4680-8470-62012a94106f
		dataCategory: Uncategorized

	measure '% YTD t.o.v. YTD budget (notifica)' = EXTERNALMEASURE("% YTD t.o.v. YTD budget (notifica)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: 80357d97-5708-44e4-a874-6f9357d068f7
		sourceLineageTag: b2bc3ab2-6485-40c8-98b1-c3c0252d6f81
		dataCategory: Uncategorized

	measure 'CoA YTD rendement notifica budget' = EXTERNALMEASURE("CoA YTD rendement notifica budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget
		lineageTag: 11fbd17f-8eb8-49a7-baac-c9ea6d2fdc9a
		sourceLineageTag: 14adda69-d646-4847-b408-f7c9b2c32aaa
		dataCategory: Uncategorized

	measure 'Mutatie resultaat notifica budget' = EXTERNALMEASURE("Mutatie resultaat notifica budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget
		lineageTag: 6e39ed98-d7f9-4de6-98e8-d70a4758e74c
		sourceLineageTag: a91977c3-658d-4fe4-8913-b9266fc9c5fb
		dataCategory: Uncategorized

	measure 'Controle project selectie' = EXTERNALMEASURE("Controle project selectie", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie
		lineageTag: a58e89d0-6d05-4890-9c76-77f8f01b4190
		sourceLineageTag: bd8b8ff9-3e21-44ad-9915-1793712149bb
		dataCategory: Uncategorized

	measure 'Gerealiseerde marge incl onverwerkte kosten' = EXTERNALMEASURE("Gerealiseerde marge incl onverwerkte kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 08ff2a00-1036-4c45-9c77-c47380d9d838
		sourceLineageTag: ad3d5912-25d7-48c5-929d-7390803abf35
		dataCategory: Uncategorized

	measure 'Gerealiseerd project rendement' = EXTERNALMEASURE("Gerealiseerd project rendement", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: bcf39934-83ae-4174-8566-1140d8e6415f
		sourceLineageTag: 74b262c0-80de-41d4-81c6-a69ff7931510
		dataCategory: Uncategorized

	measure 'Geselecteerd project' = EXTERNALMEASURE("Geselecteerd project", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie
		lineageTag: 012ac88c-33d0-476d-8576-b9b3359ee210
		sourceLineageTag: c116fce1-4e2a-47ce-bc2b-9d461bf0c4cd
		dataCategory: Uncategorized

	measure KostenplaatsKey = EXTERNALMEASURE("KostenplaatsKey", INTEGER, "DirectQuery to AS - SSM")
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp
		lineageTag: 292a27a7-a3e4-44e3-88c2-e68c25a1dd7f
		sourceLineageTag: dd716571-1367-4330-b3c3-3828ba0fdd19
		dataCategory: Uncategorized

	measure 'Melding geselecteerde budget omzet methode' = EXTERNALMEASURE("Melding geselecteerde budget omzet methode", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 680ed840-6857-415f-9be8-925cf0aea8d9
		sourceLineageTag: 262475ef-1e73-4fce-a955-2a82a9731d98
		dataCategory: Uncategorized

	measure Niveau = EXTERNALMEASURE("Niveau", INTEGER, "DirectQuery to AS - SSM")
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie
		lineageTag: fbb6d53f-1a4d-41e5-a567-0c3a253ff07a
		sourceLineageTag: 0b7a774f-7277-498f-822c-15eb86dfdec3
		dataCategory: Uncategorized

	measure 'Orderbedrag Cumulative' = EXTERNALMEASURE("Orderbedrag Cumulative", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Eenmalige orders
		lineageTag: cd112c17-f40a-4ee8-84bd-ba101f26d968
		sourceLineageTag: 56f7ba3b-0f52-4516-894f-a24cd44b6e9c
		dataCategory: Uncategorized

	measure Project = EXTERNALMEASURE("Project", STRING, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie
		lineageTag: 46b94822-0034-4850-9caf-cde1121afc03
		sourceLineageTag: b0f7afa4-92c4-4ef0-be4b-7f2f7ced1f1c
		dataCategory: Uncategorized

	measure 'Project Percentage gereed' = EXTERNALMEASURE("Project Percentage gereed", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie
		lineageTag: 78f7efe0-cd8b-48f0-85b1-473f37ea81c8
		sourceLineageTag: c6db6092-3853-48f2-bdbf-6943dff2751b
		dataCategory: Uncategorized

	measure ProjectKey = EXTERNALMEASURE("ProjectKey", INTEGER, "DirectQuery to AS - SSM")
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp
		lineageTag: 392a3f00-8776-48ed-b1ea-cc6e81124034
		sourceLineageTag: 5ef5cfbd-30c7-4a64-9cce-a4121e321bcf
		dataCategory: Uncategorized

	measure 'Type selectie' = EXTERNALMEASURE("Type selectie", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie
		lineageTag: efd10f86-066e-47e9-9e02-a7f4fb6bf814
		sourceLineageTag: 3ee6b026-8498-441a-abfc-935f4d4139fe
		dataCategory: Uncategorized

	measure 'Verschil budget - realisatie' = EXTERNALMEASURE("Verschil budget - realisatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: a42eeba0-446b-47fa-8c77-a186113464f7
		sourceLineageTag: 8960158c-48c8-45c4-b724-d346375dbb87
		dataCategory: Uncategorized

	measure 'Verschil budget - realisatie definitief' = EXTERNALMEASURE("Verschil budget - realisatie definitief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 67b0dd09-5f6d-44dc-bf8c-48be1ecd8e33
		sourceLineageTag: 17304550-8005-49fa-a81a-a7882e0e2b53
		dataCategory: Uncategorized

	measure 'Verschil calculatie - realisatie definitief' = EXTERNALMEASURE("Verschil calculatie - realisatie definitief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 63724fb5-8743-4340-a866-02f363ca2bc8
		sourceLineageTag: 665c63e8-429f-47b8-92ff-e19d32e1fff8
		dataCategory: Uncategorized

	measure 'Verschil calculatie aantal - realisatie aantal' = EXTERNALMEASURE("Verschil calculatie aantal - realisatie aantal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 2694ee3a-7f97-4411-bea0-f8193aac9dae
		sourceLineageTag: 490af44f-81ac-454a-a74e-c6239cfd8381
		dataCategory: Uncategorized

	measure 'Verschil prognose - realisatie' = EXTERNALMEASURE("Verschil prognose - realisatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 3796434d-5b49-471b-909c-787915899779
		sourceLineageTag: a02b9856-69e0-43c3-ad10-2c261f80ec71
		dataCategory: Uncategorized

	measure 'Verschil prognose - realisatie definitief' = EXTERNALMEASURE("Verschil prognose - realisatie definitief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 558ab4ec-ef7e-42ed-96f2-c49160803b26
		sourceLineageTag: 1b876134-0df3-48b9-a2a4-9642bdbc3f54
		dataCategory: Uncategorized

	measure 'Verschil prognose - realisatie uren' = EXTERNALMEASURE("Verschil prognose - realisatie uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 55cf6ae9-56a4-4fac-ad9f-6def41a8c557
		sourceLineageTag: 6ecaf65b-021b-4c26-866b-faf8e13f7407
		dataCategory: Uncategorized

	measure 'Verschil VC - NC prijs per eenheid' = EXTERNALMEASURE("Verschil VC - NC prijs per eenheid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 88c059a2-c2ff-4134-81ba-d0229a263ed5
		sourceLineageTag: 95079517-36fc-4ec6-aaee-97034bb87158
		dataCategory: Uncategorized

	measure WerkgroepKey = EXTERNALMEASURE("WerkgroepKey", INTEGER, "DirectQuery to AS - SSM")
		formatString: ##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp
		lineageTag: 1f34ee8f-074f-4749-841b-a23fb20c7635
		sourceLineageTag: ea402cd2-5813-46e0-980f-14c31c7278fb
		dataCategory: Uncategorized

	measure 'Budget omzet o.b.v. orderbedrag' = EXTERNALMEASURE("Budget omzet o.b.v. orderbedrag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 1a0b5481-8614-404f-b739-2e2792b72be9
		sourceLineageTag: 85d214b1-fa79-47df-be8e-b5eefaaaf379
		dataCategory: Uncategorized

	measure 'Budget omzet o.b.v. calculatie verkoopprijs' = EXTERNALMEASURE("Budget omzet o.b.v. calculatie verkoopprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: 6522590c-e14d-4693-9972-53159276857f
		sourceLineageTag: 4604341c-8d99-4a7d-8665-4e29067f51ae
		dataCategory: Uncategorized

	measure 'Budget omzet o.b.v. geselecteerde generiek marge' = EXTERNALMEASURE("Budget omzet o.b.v. geselecteerde generiek marge", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: c9c85836-5d50-44c1-826d-25ff12ba1aaa
		sourceLineageTag: 25a0f6ab-596c-40f4-adc2-4e089750a160
		dataCategory: Uncategorized

	measure 'Budget omzet o.b.v. methode budgetomzet' = EXTERNALMEASURE("Budget omzet o.b.v. methode budgetomzet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: 8d1fb821-4c66-4330-b066-19a4717cd480
		sourceLineageTag: ea2d9326-f0c7-41ec-b64e-1fe35bffc0ae
		dataCategory: Uncategorized

	measure 'laatste budgetverzoek' = EXTERNALMEASURE("laatste budgetverzoek", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectbewaking
		lineageTag: 1556c5a9-ef40-4237-bccb-ee64ec10f9cb
		sourceLineageTag: 71fabf47-02fe-4260-93a1-b6a8eee389ad
		dataCategory: Uncategorized

	measure 'POC kostprijs o.b.v. budget' = EXTERNALMEASURE("POC kostprijs o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: a16fd180-9f39-4875-ae3b-d9fa7d5c8151
		sourceLineageTag: a748a602-5611-42b0-9dd7-45664b359347
		dataCategory: Uncategorized

	measure 'POC montage uren o.b.v. budget' = EXTERNALMEASURE("POC montage uren o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: ac722df4-d3a0-4085-a3d3-b31463ab7bed
		sourceLineageTag: b6a0e75c-3620-4617-8533-b1bb83ea9de5
		dataCategory: Uncategorized

	measure 'POC kostprijs o.b.v. prognose' = EXTERNALMEASURE("POC kostprijs o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 1071ba32-b45b-429d-8181-582593fff059
		sourceLineageTag: 157c7f03-be90-40cc-b0aa-d789b09eb05c
		dataCategory: Uncategorized

	measure 'POC montage uren o.b.v. prognose' = EXTERNALMEASURE("POC montage uren o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 101135a2-9d1d-4f43-98e8-d0381290d2d4
		sourceLineageTag: 51158ebb-915f-4891-b45a-df028737988a
		dataCategory: Uncategorized

	measure Voortgang = EXTERNALMEASURE("Voortgang", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 85ee588e-9a51-4523-8beb-50eaec0b2cf7
		sourceLineageTag: a182e8bc-c91d-41dd-b483-1af29e4fd230
		dataCategory: Uncategorized

	measure 'Historische POC kostprijs o.b.v. budget' = EXTERNALMEASURE("Historische POC kostprijs o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: b4b2d46c-ecf0-48e3-8a14-e738d160b451
		sourceLineageTag: 4061daa8-601d-4e00-b153-b2c2241a4772
		dataCategory: Uncategorized

	measure 'Historische POC kostprijs o.b.v. prognose' = EXTERNALMEASURE("Historische POC kostprijs o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 97eeb521-9b5a-4de7-852a-dbc102983cc1
		sourceLineageTag: ea6dbebc-e6e1-48cd-bf46-9df23dbfedfb
		dataCategory: Uncategorized

	measure 'Historische POC montage uren o.b.v. budget' = EXTERNALMEASURE("Historische POC montage uren o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 1927088e-2782-47c1-8ea9-c62cdea38853
		sourceLineageTag: 8a9a5000-beb6-4467-9aa4-935190dba571
		dataCategory: Uncategorized

	measure 'Historische POC montage uren o.b.v. prognose' = EXTERNALMEASURE("Historische POC montage uren o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 08db59c5-f54d-4981-b239-fdec8e99f708
		sourceLineageTag: eab80fd7-3a00-42bb-9633-9dd59d74e44d
		dataCategory: Uncategorized

	measure 'Historische POC uren o.b.v. budget' = EXTERNALMEASURE("Historische POC uren o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: fcd4e458-a8e4-4064-b182-9d57b81aa9bc
		sourceLineageTag: 85f2b9d4-f589-4d50-8959-06132759e2e1
		dataCategory: Uncategorized

	measure 'Historische POC uren o.b.v. prognose' = EXTERNALMEASURE("Historische POC uren o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 37dc26ce-622a-45a7-9a5d-fd0f91530445
		sourceLineageTag: 9c2359ce-f4c7-4ff6-bded-c68068ced0a6
		dataCategory: Uncategorized

	/// Voortgang facturatie t.o.v. [budget omzet]
	measure 'Historische POC omzet o.b.v. budget' = EXTERNALMEASURE("Historische POC omzet o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 907b7e0f-1b57-45ab-99d9-461c3cd64e4b
		sourceLineageTag: 22b77f2d-fde1-4650-971a-1479a4c24ab4
		dataCategory: Uncategorized

	/// Voortgang facturatie t.o.v. prognose omzet
	measure 'Historische POC omzet o.b.v. prognose' = EXTERNALMEASURE("Historische POC omzet o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: c5586119-9d65-431e-84b0-50868fea1fbc
		sourceLineageTag: 778c742f-4ea5-4705-84ea-339d020cebc9
		dataCategory: Uncategorized

	/// Voortgang facturatie t.o.v. [budget omzet]
	measure 'POC omzet o.b.v. budget' = EXTERNALMEASURE("POC omzet o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 5fcfd38e-d38f-46d3-839b-45f1d053c05a
		sourceLineageTag: a3213d1f-5126-4fcf-aef6-6d5d8933a56c
		dataCategory: Uncategorized

	/// Voortgang facturatie t.o.v. prognose omzet
	measure 'POC omzet o.b.v. prognose' = EXTERNALMEASURE("POC omzet o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 3f091ad0-be94-40d6-a680-f2e479337a17
		sourceLineageTag: 0bc3a871-550b-481b-a1a6-77b30dfe949f
		dataCategory: Uncategorized

	measure 'POC uren o.b.v. budget' = EXTERNALMEASURE("POC uren o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: cc9b2dc3-8b37-40ca-956e-bb453aa40486
		sourceLineageTag: 83ebedaf-8d93-4e9c-8d07-b4dad7a3d759
		dataCategory: Uncategorized

	measure 'POC uren o.b.v. prognose' = EXTERNALMEASURE("POC uren o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 08c223cf-5e11-46b0-8235-770b70db559b
		sourceLineageTag: afb4dc3b-9b0e-4136-8664-43bc40337e58
		dataCategory: Uncategorized

	measure 'POC projectgebonden uren o.b.v. prognose' = EXTERNALMEASURE("POC projectgebonden uren o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 884cf8d9-e3bc-42b2-a1d7-764819ce0e23
		sourceLineageTag: a299bccd-6396-4a2a-923e-53082bca5502
		dataCategory: Uncategorized

	measure 'POC projectgebonden uren  o.b.v. budget' = EXTERNALMEASURE("POC projectgebonden uren  o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 99712d5b-7d7e-436c-9b77-0c18de698f05
		sourceLineageTag: 60cb7341-518b-4f26-a6c0-be1871a330fa
		dataCategory: Uncategorized

	measure 'POC overig kostprijs o.b.v. prognose' = EXTERNALMEASURE("POC overig kostprijs o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 83d245c2-076e-4a12-8cb3-d47162264d25
		sourceLineageTag: 0e2255c2-0e43-4f5a-b52f-0b811244d58c
		dataCategory: Uncategorized

	measure 'POC overig kostprijs o.b.v. budget' = EXTERNALMEASURE("POC overig kostprijs o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: b5c244ff-2feb-4823-a83b-4899ab008012
		sourceLineageTag: 9b4d1ba2-56e8-4a0e-a8bd-6b3abf2a7e27
		dataCategory: Uncategorized

	measure 'POC materieel kostprijs o.b.v. prognose' = EXTERNALMEASURE("POC materieel kostprijs o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: a1dbc451-beb0-4690-86df-4730a629015a
		sourceLineageTag: f3296422-a15f-4c27-b12c-86be2f0927c3
		dataCategory: Uncategorized

	measure 'POC materieel kostprijs o.b.v. budget' = EXTERNALMEASURE("POC materieel kostprijs o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 964114d2-1d9b-4e78-a96a-ec8164d546b1
		sourceLineageTag: df892359-662b-409b-bbde-0474d87aca95
		dataCategory: Uncategorized

	measure 'POC materiaal kostprijs o.b.v. prognose' = EXTERNALMEASURE("POC materiaal kostprijs o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: e040a8ae-07f3-4a97-8e5f-0d96ee9c407d
		sourceLineageTag: 836f0165-8048-46d9-8fcd-2bb37b472a33
		dataCategory: Uncategorized

	measure 'POC materiaal kostprijs o.b.v. budget' = EXTERNALMEASURE("POC materiaal kostprijs o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 6a5aca53-a92f-4934-a248-65ef251883d9
		sourceLineageTag: 00113392-f44e-438c-b0e7-d0c869e04d84
		dataCategory: Uncategorized

	measure 'POC arbeid kostprijs o.b.v. budget' = EXTERNALMEASURE("POC arbeid kostprijs o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: bc907061-69ab-46a3-a8d6-1c89eaa96f0f
		sourceLineageTag: cd69bfc3-3cc3-474a-b5f5-40c2ad8d2bf7
		dataCategory: Uncategorized

	measure 'POC arbeid kostprijs o.b.v. prognose' = EXTERNALMEASURE("POC arbeid kostprijs o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 77e55ab1-5a5e-47ca-b820-3b29b7024380
		sourceLineageTag: 41f7506f-c74b-4932-95ae-49e23133a0a8
		dataCategory: Uncategorized

	measure 'Historische projectwaardering o.b.v. budget' = EXTERNALMEASURE("Historische projectwaardering o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: d199c3f9-4786-493f-a44d-b86061938ddf
		sourceLineageTag: b85a2d56-fe8a-41c1-88df-a5bf0ca6bbfd
		dataCategory: Uncategorized

	measure 'Historische projectwaardering o.b.v. prognose' = EXTERNALMEASURE("Historische projectwaardering o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 6c8c0a41-eea8-4c8c-8e78-14a34d47a592
		sourceLineageTag: f913341d-e55e-4912-99e7-37bc0c0f1c71
		dataCategory: Uncategorized

	measure 'Historische correctieboeking (berekend) projectwaardering o.b.v. prognose' = EXTERNALMEASURE("Historische correctieboeking (berekend) projectwaardering o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 42379dbf-6f30-4c1f-86d8-419a57bd4695
		sourceLineageTag: 4a08ee2e-b0b0-4d29-9ab6-ee55dec4644a
		dataCategory: Uncategorized

	measure 'Historische correctieboeking (berekend) projectwaardering o.b.v. budget' = EXTERNALMEASURE("Historische correctieboeking (berekend) projectwaardering o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: b601ca10-1ed8-4101-923e-afc7bc41c37f
		sourceLineageTag: f60ba536-cec9-4cac-af64-768188b3755d
		dataCategory: Uncategorized

	measure 'Historische omzetcorrectie o.b.v. budget' = EXTERNALMEASURE("Historische omzetcorrectie o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie
		lineageTag: 9e2523ad-3439-417f-a048-129f61ae779d
		sourceLineageTag: d6e7467b-f065-40f0-be0a-3dc600985527
		dataCategory: Uncategorized

	measure 'Historische omzet SOLL o.b.v. budget' = EXTERNALMEASURE("Historische omzet SOLL o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie
		lineageTag: 8648425a-22cc-4ecc-9ff9-bcaa2bf16023
		sourceLineageTag: fe69cd71-294d-4f43-8b11-c17e0b77c08e
		dataCategory: Uncategorized

	measure 'Historische omzet SOLL o.b.v. prognose' = EXTERNALMEASURE("Historische omzet SOLL o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie
		lineageTag: bd3b4a92-7daa-4405-b161-6fbf1e858c1a
		sourceLineageTag: c871d02a-20d2-4a52-bfde-39a03de9a5ab
		dataCategory: Uncategorized

	measure 'Historische omzetcorrectie o.b.v. prognose' = EXTERNALMEASURE("Historische omzetcorrectie o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie
		lineageTag: 9842d884-ba07-46d4-92df-598724ad4344
		sourceLineageTag: e6e951ec-8a5a-48e4-a07e-00f9806ecf34
		dataCategory: Uncategorized

	measure 'Opgeslagen omzetcorrectie' = EXTERNALMEASURE("Opgeslagen omzetcorrectie", INTEGER, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Omzetcorrectie
		lineageTag: 40ce9adf-7cec-449b-8edf-a32960318cf1
		sourceLineageTag: edd0539d-b670-4e00-ba01-4f3d8460bf35
		dataCategory: Uncategorized

	measure 'Werkelijk rendement o.b.v. prognose' = EXTERNALMEASURE("Werkelijk rendement o.b.v. prognose", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 6032170f-e7b0-4ad2-847b-4598708778ca
		sourceLineageTag: ce4e4a8b-4edc-4aad-9b34-28ceb27a556a
		dataCategory: Uncategorized

	measure 'Werkelijk rendement o.b.v. budget' = EXTERNALMEASURE("Werkelijk rendement o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: b956ec62-2d42-410d-8d68-1fd5902e1594
		sourceLineageTag: 4812acf8-a014-46c4-8237-da7934a1bc0d
		dataCategory: Uncategorized

	measure 'Methode ID voortgang geselecteerd' = EXTERNALMEASURE("Methode ID voortgang geselecteerd", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: f39606dd-1448-4592-9454-8f2a34c861db
		sourceLineageTag: c0c1d97a-f496-4cd6-bcec-6960bff2497f
		dataCategory: Uncategorized

	measure 'Methode ID verwachte marge geselecteerd' = EXTERNALMEASURE("Methode ID verwachte marge geselecteerd", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: db6814cb-e14b-430e-aead-2e70b88a21da
		sourceLineageTag: 2e80ea3c-b40c-477d-850c-3702fe4f2141
		dataCategory: Uncategorized

	measure 'Generieke marge geselecteerd' = EXTERNALMEASURE("Generieke marge geselecteerd", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.00\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: 1d0c674d-f1db-41dd-91d5-3f0dc3ec36a2
		sourceLineageTag: e51e22b4-06a1-47ac-98a5-9fd13adcc5a0
		dataCategory: Uncategorized

	measure 'Methode ID budget omzet geselecteerd' = EXTERNALMEASURE("Methode ID budget omzet geselecteerd", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: eac2f2ec-7a9b-4c2f-aa03-537efc286dda
		sourceLineageTag: 3fb650df-f8ea-482c-895d-652d9ca3408a
		dataCategory: Uncategorized

	measure 'Methode budget omzet geselecteerd' = EXTERNALMEASURE("Methode budget omzet geselecteerd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: 94b28c57-1bdd-48ef-8485-35bd8a7fb342
		sourceLineageTag: 7d97485e-d675-4ee8-a789-5c59d496bfdd
		dataCategory: Uncategorized

	measure 'Methode verwachte marge geselecteerd' = EXTERNALMEASURE("Methode verwachte marge geselecteerd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: 99395362-3b8e-4b8c-b8ac-6048f08672ad
		sourceLineageTag: 1c0b8e2f-ba6c-48fd-8304-10c313e09a5e
		dataCategory: Uncategorized

	measure 'Methode voortgang geselecteerd' = EXTERNALMEASURE("Methode voortgang geselecteerd", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Methodes
		lineageTag: 51466dbf-601b-4ff2-b218-1cce9174e655
		sourceLineageTag: 1b324226-fa0e-44e3-a32e-4b02f4c28a5b
		dataCategory: Uncategorized

	measure 'Melding geselecteerde methode voortgang' = EXTERNALMEASURE("Melding geselecteerde methode voortgang", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: c53534c9-ae5c-4c8f-9de7-c41901fc2d75
		sourceLineageTag: 27a7e357-9445-4605-a3ef-bf586182dec7
		dataCategory: Uncategorized

	measure 'Melding generieke marge' = EXTERNALMEASURE("Melding generieke marge", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: a73cd518-79bd-44da-9a0d-5d083569befb
		sourceLineageTag: 66b619f8-2f88-4414-ae17-f6c839234fb3
		dataCategory: Uncategorized

	measure 'Gemiddeld uurtarief projectgebonden uren' = EXTERNALMEASURE("Gemiddeld uurtarief projectgebonden uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 801eab5f-6ca1-46e1-a5fc-9c1ec4207a11
		sourceLineageTag: 8d1595ca-ecc5-4088-bcb4-dd31ae3d8dfa
		dataCategory: Uncategorized

	measure 'Gemiddeld uurtarief montage uren' = EXTERNALMEASURE("Gemiddeld uurtarief montage uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 40083e1f-9ead-4a41-99f4-e5a917b953b5
		sourceLineageTag: 84e026be-9840-4860-8e3f-190d4c189c58
		dataCategory: Uncategorized

	measure 'Inleen via inkoop' = EXTERNALMEASURE("Inleen via inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 7a0d09d5-be45-4ade-8ecf-c372d0b511c1
		sourceLineageTag: 72d7069a-8553-4731-9740-edf2279fef50
		dataCategory: Uncategorized

	measure 'inleen via inkoop cumulatief' = EXTERNALMEASURE("inleen via inkoop cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 05bccc37-8d91-48a2-935f-730e4f9aa054
		sourceLineageTag: 2f23a754-bb45-431f-9c75-b911bc8dddaa
		dataCategory: Uncategorized

	measure 'Montage arbeidskosten' = EXTERNALMEASURE("Montage arbeidskosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 76b4b32e-bc8f-4bca-acf2-2f99bff2a036
		sourceLineageTag: 7e44126d-a91e-4968-a079-6eac16fc3a68
		dataCategory: Uncategorized

	measure 'Projectgebonden arbeidskosten' = EXTERNALMEASURE("Projectgebonden arbeidskosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: e6c3d72f-17f3-4cb9-ac60-3ab710c766fe
		sourceLineageTag: 0d1679c7-29da-4f64-8284-6570edf2545d
		dataCategory: Uncategorized

	measure 'Montage uren NOT BLANK' = EXTERNALMEASURE("Montage uren NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 4e79631e-fd58-45d3-9fdc-774237e7fbc5
		sourceLineageTag: b7d36a37-3dac-49fc-8a3e-84cfd2e94fd8
		dataCategory: Uncategorized

	measure 'Gemiddeld uurtarief' = EXTERNALMEASURE("Gemiddeld uurtarief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 0028eaf9-b2c5-4f98-98f5-c2631a776d7b
		sourceLineageTag: fab8f0e8-7fc8-4d2f-8f31-e3e90e98decd
		dataCategory: Uncategorized

	measure Arbeidskosten = EXTERNALMEASURE("Arbeidskosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 709435fc-1089-4502-b78c-e2313a3d8a66
		sourceLineageTag: 241b1bf7-b677-4085-9157-cbbcfb398bb6
		dataCategory: Uncategorized

	measure 'Betaald bedrag via orderregel' = EXTERNALMEASURE("Betaald bedrag via orderregel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project
		lineageTag: e03f2c94-7796-46f6-a61c-a63182be8778
		sourceLineageTag: f12a28fd-bb26-4e8b-9664-90e5ad6efa57
		dataCategory: Uncategorized

	measure 'Betalingen en openstaand' = EXTERNALMEASURE("Betalingen en openstaand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Inkoopfactuur betalingen vanuit project
		lineageTag: 716a95c4-9c3b-4dfa-ab47-88b89947ac68
		sourceLineageTag: 2a5034fe-65e5-45c9-b5f6-92d9c9e1a610
		dataCategory: Uncategorized

	measure 'Betalingen op inkoopregels' = EXTERNALMEASURE("Betalingen op inkoopregels", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Inkoopfactuur betalingen vanuit project
		lineageTag: b12f660a-2d69-45b8-ba28-60cdb72a5fbe
		sourceLineageTag: be611d5e-df2a-4485-b070-6f09a9a4ada4
		dataCategory: Uncategorized

	measure 'Cash in' = EXTERNALMEASURE("Cash in", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project
		lineageTag: d620f599-1b75-47db-a367-e43bd3a63c8f
		sourceLineageTag: dc23c131-87e8-4155-812f-a1d127dd3836
		dataCategory: Uncategorized

	measure 'Cash in via order' = EXTERNALMEASURE("Cash in via order", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project
		lineageTag: 4f7c0cd1-835d-47e3-95a9-95c51f6d950f
		sourceLineageTag: c64a4df0-c38c-4cdd-b09c-626cda7dcefa
		dataCategory: Uncategorized

	measure 'Openstaand bedrag' = EXTERNALMEASURE("Openstaand bedrag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project
		lineageTag: 67c5e4fb-1f04-4b1b-8661-b150e06f599f
		sourceLineageTag: c0e4a1b9-2d3c-4eea-9c29-bc4e785c80b4
		dataCategory: Uncategorized

	measure 'Openstaand bedrag via orderregel' = EXTERNALMEASURE("Openstaand bedrag via orderregel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project
		lineageTag: 3ff4ef34-fb95-4255-9006-cdc884c89006
		sourceLineageTag: fd4b96a4-cc6d-4b93-8f83-70b668921e3e
		dataCategory: Uncategorized

	measure 'Openstaand op inkoopregels' = EXTERNALMEASURE("Openstaand op inkoopregels", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Inkoopfactuur betalingen vanuit project
		lineageTag: 76153180-6956-4175-892d-78da01b1a1a9
		sourceLineageTag: 21c69fc8-8d70-4cb8-b5c2-9c7d0a364496
		dataCategory: Uncategorized

	measure 'Vervallen betalingstermijnen' = EXTERNALMEASURE("Vervallen betalingstermijnen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Verkoopfactuur betalingen vanuit project
		lineageTag: 179d12b8-b826-4b18-94ce-9ad0d413db45
		sourceLineageTag: 2337ce9a-34af-4b00-8793-94975ce9a077
		dataCategory: Uncategorized

	measure 'Vervallen betalingstermijnen via orderregel' = EXTERNALMEASURE("Vervallen betalingstermijnen via orderregel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project
		lineageTag: 6f4c7cf5-9de8-4c6c-8361-dec17c37593d
		sourceLineageTag: 519caf98-de0c-4548-aa7d-114d046c9114
		dataCategory: Uncategorized

	measure 'Aantal gerealiseerd' = EXTERNALMEASURE("Aantal gerealiseerd", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 23c0e94b-0695-47d8-b385-6b0fc45b2759
		sourceLineageTag: 560b4132-2469-4e6a-b160-45d8f0cfb2be
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs cum.' = EXTERNALMEASURE("Definitieve kostprijs cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 13fda2ca-22dd-40aa-819d-5c440782306a
		sourceLineageTag: a95cefb3-b1a5-4fc1-94c0-b0f88941ffe4
		dataCategory: Uncategorized

	measure 'Gem. prijs per eenheid' = EXTERNALMEASURE("Gem. prijs per eenheid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: e26a6c76-2a63-4c8c-858f-2a2920027be9
		sourceLineageTag: 07efc070-4fe1-4a1d-bd89-5000a329a837
		dataCategory: Uncategorized

	measure 'Onverwerkte kostprijs inkoop' = EXTERNALMEASURE("Onverwerkte kostprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 67f3cee0-774a-420c-9e7b-0a2c5145d5c4
		sourceLineageTag: f0dfa394-efda-4041-a052-1497445a44e8
		dataCategory: Uncategorized

	measure 'Totaal kosten cum. (verrekenprijs onverwerkt, kostprijs definitief)' = EXTERNALMEASURE("Totaal kosten cum. (verrekenprijs onverwerkt, kostprijs definitief)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: ad090a73-117a-4ed5-b081-c9162e115969
		sourceLineageTag: 161bbbc6-9fd9-4124-93c0-1c3db3d054f3
		dataCategory: Uncategorized

	measure 'Totaal kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)' = EXTERNALMEASURE("Totaal kosten inkoop (verrekenprijs onverwerkt, kostprijs definitief)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 143d85a4-9f22-4b62-bec2-cc6f9e33f176
		sourceLineageTag: 21379fc5-ae3b-4d01-aff7-8ab6f172bed4
		dataCategory: Uncategorized

	measure 'Verrekenprijs inkoop' = EXTERNALMEASURE("Verrekenprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 497fdb32-59fc-4af8-a2a2-cdd909caf30d
		sourceLineageTag: 44d91cf4-57ec-42c8-a39f-e78b3b378821
		dataCategory: Uncategorized

	measure 'Verschil kostprijs tov verrekenprijs' = EXTERNALMEASURE("Verschil kostprijs tov verrekenprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: e9d26b83-9e9e-40ed-86a8-4f97cb05ade9
		sourceLineageTag: b6bc2970-f779-4c77-892b-a462d7f61928
		dataCategory: Uncategorized

	measure 'Nog niet betaald van orderregel' = EXTERNALMEASURE("Nog niet betaald van orderregel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Betalingen\Via orderregels vanuit project
		lineageTag: c49f2f41-f3d9-43ac-bc11-e89cd65c3796
		sourceLineageTag: a8177860-842c-420c-8a4b-d5de81f10b7a
		dataCategory: Uncategorized

	measure Waardering = EXTERNALMEASURE("Waardering", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 8bc5c4d0-822a-418f-829f-c7d7f842c131
		sourceLineageTag: 7bc55a68-1cf0-48cd-bdee-a998db6b0d60
		dataCategory: Uncategorized

	measure Vrijval/Werkresultaat = EXTERNALMEASURE("Vrijval/Werkresultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: 7e7e0d29-35fd-4b74-9de4-59a93cd8e9cd
		sourceLineageTag: 360cd1da-6d3e-44ad-8904-37348f3dc6fd
		dataCategory: Uncategorized

	measure 'Onderhanden werk' = EXTERNALMEASURE("Onderhanden werk", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.02 HR\Realisatie
		lineageTag: ffc1d79b-6d77-4b30-be9e-dd6d0f747930
		sourceLineageTag: df598fa6-b991-407a-bc1f-fd4c0c1f8406
		dataCategory: Uncategorized

	measure 'Calculatie montage uren cum.' = EXTERNALMEASURE("Calculatie montage uren cum.", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 376c6cfe-9c72-41f1-bf81-bc0601b30944
		sourceLineageTag: 5270389d-28d4-4024-ac60-86eac6ee2415
		dataCategory: Uncategorized

	measure 'Calculatie gem. prijs per eenheid' = EXTERNALMEASURE("Calculatie gem. prijs per eenheid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 182d6bb4-bbec-4ce2-9497-f4a141090e01
		sourceLineageTag: 28cb8d46-854b-4312-85e7-4c4ca96ba1a3
		dataCategory: Uncategorized

	measure 'Calculatie aantal' = EXTERNALMEASURE("Calculatie aantal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 2f4ba47d-d939-486a-9a31-996504e93ddc
		sourceLineageTag: 582a374f-9833-489f-b3ff-428ef023ed5a
		dataCategory: Uncategorized

	measure 'POC montage uren  o.b.v. budget' = EXTERNALMEASURE("POC montage uren  o.b.v. budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 548c81c3-7e07-46dc-9dcf-8b6fe22ce9f8
		sourceLineageTag: 8357d54a-afa5-496b-826c-f96f80d809cb
		dataCategory: Uncategorized

	measure 'POC uren o.b.v. calculatie' = EXTERNALMEASURE("POC uren o.b.v. calculatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: 717a4577-9d91-4b0a-aaa7-6d567941b606
		sourceLineageTag: bae96e67-f95a-4dca-83b7-52147324e509
		dataCategory: Uncategorized

	measure 'POC kostprijs o.b.v. calculatie' = EXTERNALMEASURE("POC kostprijs o.b.v. calculatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\POC
		lineageTag: a4aad4e7-212e-44c7-bf8c-aad9a0ab1612
		sourceLineageTag: 2a15e849-27fa-4ce2-8bd5-9d84e1571c40
		dataCategory: Uncategorized

	measure 'Verzoek omzet NOT BLANK ' = EXTERNALMEASURE("Verzoek omzet NOT BLANK ", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 2c78ba53-b39c-436d-be38-d851053d3a32
		sourceLineageTag: 7e74930c-4a78-4b28-a36c-77a38c144521
		dataCategory: Uncategorized

	measure 'Verzoek kosten NOT BLANK' = EXTERNALMEASURE("Verzoek kosten NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 18546af2-e8dc-4cc2-a110-6e6703cf316e
		sourceLineageTag: 4696abfd-1ded-4656-9374-970fedfe6d18
		dataCategory: Uncategorized

	measure 'Prognose omzet o.b.v. orderbedrag' = EXTERNALMEASURE("Prognose omzet o.b.v. orderbedrag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: ad6999ed-f257-43a0-b402-3afa27f169b3
		sourceLineageTag: f3ae8642-4f8b-4d07-99c7-07e9a77c7eaa
		dataCategory: Uncategorized

	measure 'Prognose omzet o.b.v. calculatie verkoopprijs' = EXTERNALMEASURE("Prognose omzet o.b.v. calculatie verkoopprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Prognose
		lineageTag: 97903c69-c408-45cc-9c06-16feabcaf043
		sourceLineageTag: 63623e48-e4d2-4607-8952-a6a385e8a255
		dataCategory: Uncategorized

	measure 'Prognose kostprijs' = EXTERNALMEASURE("Prognose kostprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Prognose o.b.v. calculatiekostprijs en order
		lineageTag: 74cf17a1-0b7e-4816-ad2c-5520e6374890
		sourceLineageTag: 030c73ac-26a1-46ea-8402-059c3bc37890
		dataCategory: Uncategorized

	measure 'Budget kostprijs' = EXTERNALMEASURE("Budget kostprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budget o.b.v. calculatiekostprijs en order
		lineageTag: 710500f0-5faa-4844-9bdb-5135af409106
		sourceLineageTag: 74c486f6-86f0-4183-adac-9ca51522425e
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs arbeid (regie)' = EXTERNALMEASURE("Definitieve kostprijs arbeid (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: c8651690-8dc8-4a8a-83e7-f6fb72c81c13
		sourceLineageTag: f61f0254-e492-49c0-a7f9-d264093745c5
		dataCategory: Uncategorized

	measure Boekjaar = EXTERNALMEASURE("Boekjaar", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 085e0fcc-042f-46ca-ac38-d9bf4c804662
		sourceLineageTag: 54e3f647-3624-4cb4-ae13-037c3a592d38
		dataCategory: Uncategorized

	measure 'Controle kosten verdeeld' = EXTERNALMEASURE("Controle kosten verdeeld", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 4d92e28c-45ed-42e3-8501-d5dec8bfd504
		sourceLineageTag: bc52566d-d2cd-48e5-a7a7-99438f8a9f4d
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs niet via werkbon' = EXTERNALMEASURE("Definitieve kostprijs niet via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 06bf31c7-59ce-42b1-95c0-6855362c4b06
		sourceLineageTag: bf14775d-b6fe-467b-a82e-4f00a9e0f3c3
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs niet via werkbon NOT BLANK' = EXTERNALMEASURE("Definitieve kostprijs niet via werkbon NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: e404c723-f3b1-40d3-ba86-b93f2f043ec9
		sourceLineageTag: 562d03cd-f746-43de-8e5c-b2f2964e2b54
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs NOT BLANK' = EXTERNALMEASURE("Definitieve kostprijs NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 3dadd4a0-de99-4cd0-ad85-bb97af1aa766
		sourceLineageTag: eed11fec-0377-4e2d-bf27-9792c0d46b3b
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via onderhoud (in contract)' = EXTERNALMEASURE("Definitieve Kosten via onderhoud (in contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 75ade937-5116-4545-84f6-bdab62107955
		sourceLineageTag: 1e8ea455-38d5-4dac-85e5-cb3a3cfea3ad
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via onderhoud (in contract) NOT BLANK' = EXTERNALMEASURE("Definitieve Kosten via onderhoud (in contract) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 48fc358b-8a8d-4366-9d1c-d638d962056b
		sourceLineageTag: df75a640-a614-4050-a712-48a70b8a0782
		dataCategory: Uncategorized

	measure 'Definitieve kosten via onderhoud (regie)' = EXTERNALMEASURE("Definitieve kosten via onderhoud (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: f8f31f98-e561-448d-8647-bc981adcc6dc
		sourceLineageTag: 0fa46b1d-1add-4d7e-b8bf-a2996571d928
		dataCategory: Uncategorized

	measure 'Definitieve kosten via onderhoud (regie) NOT BLANK' = EXTERNALMEASURE("Definitieve kosten via onderhoud (regie) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 47cf8bc8-25d7-4076-850b-d626ba1bda73
		sourceLineageTag: 59d998ae-ff45-4a8e-958f-c6b73e321585
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via Regiebon' = EXTERNALMEASURE("Definitieve Kosten via Regiebon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 9ddbe85b-54fd-42b5-bdda-885d463b72ae
		sourceLineageTag: 09c9b784-b96b-42ad-9344-100437be74a0
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via Regiebon NOT BLANK' = EXTERNALMEASURE("Definitieve Kosten via Regiebon NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: f0e7d682-4737-4a1e-956c-97bd1048da48
		sourceLineageTag: 722dfd25-d1ab-4ad4-a2bb-7e1ee50f47fb
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via storing (in contract)' = EXTERNALMEASURE("Definitieve Kosten via storing (in contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 41714d54-d38a-4802-9f28-c05d939ffe55
		sourceLineageTag: 496f467c-a31a-4f37-b22b-129302fafb18
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via storing (in contract) NOT BLANK' = EXTERNALMEASURE("Definitieve Kosten via storing (in contract) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: e8b40d6f-5fef-4e89-8d18-b462e4988ab3
		sourceLineageTag: a716a258-87a2-44da-b4b3-4ca4c90cfeb5
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via storing (regie)' = EXTERNALMEASURE("Definitieve Kosten via storing (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 7f164bb8-b877-46f3-8d66-80e28943ab10
		sourceLineageTag: ec9d30f6-1af0-4935-9487-9151b1fbdf68
		dataCategory: Uncategorized

	measure 'Definitieve Kosten via storing (regie) NOT BLANK' = EXTERNALMEASURE("Definitieve Kosten via storing (regie) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 89dd9c43-3eec-49e1-97bd-b3518cb68c84
		sourceLineageTag: 0d565d88-a6f3-4837-98d0-f66bc51f34bf
		dataCategory: Uncategorized

	measure 'Definitieve kosten via werkbon' = EXTERNALMEASURE("Definitieve kosten via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: df43702e-23af-4fb2-97a5-2f91a73238a7
		sourceLineageTag: e29bb240-33f2-4cb8-af2a-8a5b0b0c3a8a
		dataCategory: Uncategorized

	measure 'Project omzet o.b.v. onderdelen' = EXTERNALMEASURE("Project omzet o.b.v. onderdelen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Gefactureerd
		lineageTag: f185168f-81cc-4263-9666-da517a9a63cb
		sourceLineageTag: 2697da39-cd4e-42d6-9561-a0590f88c9b9
		dataCategory: Uncategorized

	measure 'Project omzet (niet via order)' = EXTERNALMEASURE("Project omzet (niet via order)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: def08216-aa3a-4473-b0d2-106b809317d5
		sourceLineageTag: ffed9ffb-dcec-49ea-bf94-e360a10c4691
		dataCategory: Uncategorized

	measure 'Project omzet o.b.v. onderdelen NOT BLANK' = EXTERNALMEASURE("Project omzet o.b.v. onderdelen NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Gefactureerd
		lineageTag: 6ad139cb-6d87-4d53-b827-39cd143f0fdf
		sourceLineageTag: a50313b5-1596-4660-bae5-748ca92f118e
		dataCategory: Uncategorized

	measure 'Project omzet (regie) NOT BLANK' = EXTERNALMEASURE("Project omzet (regie) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: f44f53f9-3458-48c9-902b-68d396dc285a
		sourceLineageTag: a01c076b-3fdb-4e71-863d-b283ab0b533e
		dataCategory: Uncategorized

	measure 'Project omzet (order) NOT BLANK' = EXTERNALMEASURE("Project omzet (order) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 92c75172-4a99-4887-96a8-fdaf7f0c1d36
		sourceLineageTag: 534cfb1b-d2f3-4087-a7fc-a846e3cf35e7
		dataCategory: Uncategorized

	measure 'Project omzet creditnotas' = EXTERNALMEASURE("Project omzet creditnotas", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: a896d60a-2de4-412f-a137-fc3f9aad07e7
		sourceLineageTag: 5f0a9472-6df6-4551-b0c6-cc1d47232dff
		dataCategory: Uncategorized

	measure 'Project omzet (voorschot op termijn)' = EXTERNALMEASURE("Project omzet (voorschot op termijn)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: ca3bc1b9-6fb1-48db-8b8d-45e79c966cc8
		sourceLineageTag: 996d9faf-9e83-4304-bfc8-895d01220434
		dataCategory: Uncategorized

	measure 'Project omzet (voorschot op termijn) NOT BLANK' = EXTERNALMEASURE("Project omzet (voorschot op termijn) NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 1d830837-f925-4e6f-815c-1f94e17215b6
		sourceLineageTag: 6c284d2f-acfa-4076-a02c-5e199f53808a
		dataCategory: Uncategorized

	measure 'Marge % VC resultaat Projecten' = EXTERNALMEASURE("Marge % VC resultaat Projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: fa8f2a3b-b3e9-431e-b077-891382e841ed
		sourceLineageTag: 7519e1c5-ce3a-460a-912b-6c311d5715d3
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs materiaal (regie)' = EXTERNALMEASURE("Definitieve kostprijs materiaal (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: cf69c311-6a49-44ec-85f8-aeb43650b44c
		sourceLineageTag: 872b7d75-38fc-47f4-b8b8-2725f63b219a
		dataCategory: Uncategorized

	measure 'Melding alle kosten verdeeld' = EXTERNALMEASURE("Melding alle kosten verdeeld", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: c90f36fc-ed88-4cad-b7f9-56a45bd1ed91
		sourceLineageTag: 82839da3-6726-41fd-a841-4551b3839be5
		dataCategory: Uncategorized

	measure 'Melding niet alle kosten verdeeld' = EXTERNALMEASURE("Melding niet alle kosten verdeeld", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 4fd0f50a-ec90-493c-a446-cedc768dd21f
		sourceLineageTag: 72331b37-8ca4-4cf8-a522-260f4b311577
		dataCategory: Uncategorized

	measure 'Nog te factureren' = EXTERNALMEASURE("Nog te factureren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 92a04940-1871-426e-8288-6de37f41df58
		sourceLineageTag: 8c1a9ed2-be44-47bb-9505-a29dea56e733
		dataCategory: Uncategorized

	measure 'Nog te verwachten kosten via werkbon' = EXTERNALMEASURE("Nog te verwachten kosten via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 405e0aaf-ed99-4102-95c7-174d8b7755fb
		sourceLineageTag: 676e577f-42e5-46ef-8693-3cc0e0bee222
		dataCategory: Uncategorized

	measure 'onverwerkte opbrengsten' = EXTERNALMEASURE("onverwerkte opbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 34ba4f31-e78f-4ac4-8d93-0fb484a094c6
		sourceLineageTag: 0b999acd-2ac4-4d50-8285-e6dd63f15613
		dataCategory: Uncategorized

	measure 'onverwerkte opbrengsten contract' = EXTERNALMEASURE("onverwerkte opbrengsten contract", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 84f63a51-69e7-4417-a5f4-3bec61ed3bb5
		sourceLineageTag: 977989e6-8d35-4797-ad53-7923e33ce826
		dataCategory: Uncategorized

	measure 'onverwerkte opbrengsten niet uitgevoerde werkbonnen' = EXTERNALMEASURE("onverwerkte opbrengsten niet uitgevoerde werkbonnen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: e39bc036-4104-4c53-a34b-5b79802b4733
		sourceLineageTag: 97036934-1e3a-4c6d-b8a3-694b1ce3e0e1
		dataCategory: Uncategorized

	measure 'onverwerkte opbrengsten NOT BLANK' = EXTERNALMEASURE("onverwerkte opbrengsten NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 5f81d744-2340-4d61-8fdd-3b11e4c1a43a
		sourceLineageTag: d5c86640-c9af-4caf-8e5c-98e28cd81d50
		dataCategory: Uncategorized

	measure 'onverwerkte opbrengsten uitgevoerde werkbonnen' = EXTERNALMEASURE("onverwerkte opbrengsten uitgevoerde werkbonnen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 9aad948e-ba14-41aa-a222-01a9dbf39aca
		sourceLineageTag: 40c1c2f3-bcbd-4468-a0e0-acf3ffd6d87c
		dataCategory: Uncategorized

	measure 'Project omzet (regie)' = EXTERNALMEASURE("Project omzet (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 7ec5658d-018a-427a-bd43-b8668aaa5cf6
		sourceLineageTag: ce76ec2f-406d-4c0b-a0d5-0ff8b70c201d
		dataCategory: Uncategorized

	measure 'opbrengsten via werkbon' = EXTERNALMEASURE("opbrengsten via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: b6fc03a9-72a1-4a8c-91e3-15bb56e5cedb
		sourceLineageTag: 332e4f8c-6203-4826-8491-a034d7be2439
		dataCategory: Uncategorized

	measure Opdrachtdatum = EXTERNALMEASURE("Opdrachtdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 83a413eb-d732-4ce0-be0f-24916729d37d
		sourceLineageTag: 86eb893b-3330-4872-98d8-e3d386ea72c0
		dataCategory: Uncategorized

	measure 'Openstaand over vervaldatum' = EXTERNALMEASURE("Openstaand over vervaldatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten
		lineageTag: 585ae44b-d386-484d-859d-b7e5944f6bad
		sourceLineageTag: f73233c7-26c2-48be-bf10-e79a13496273
		dataCategory: Uncategorized

	measure 'POC contract op basis van uren' = EXTERNALMEASURE("POC contract op basis van uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 5152b163-d95d-4793-824a-74cf566973b9
		sourceLineageTag: dc538269-638a-4de3-a8e2-55651644e5c7
		dataCategory: Uncategorized

	measure Rendement = EXTERNALMEASURE("Rendement", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 9c50d2fe-faae-4296-b4cc-a542f51ded68
		sourceLineageTag: c802f42f-fe20-46bf-9104-753b64b4f00e
		dataCategory: Uncategorized

	measure 'Rendement NOT BLANK' = EXTERNALMEASURE("Rendement NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: da80a05d-4a73-4709-9d00-804eb5f22d3e
		sourceLineageTag: 5ec5f738-48ef-4fc9-9db3-8e9ddada7780
		dataCategory: Uncategorized

	measure 'Rendement op service contract' = EXTERNALMEASURE("Rendement op service contract", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 92f98678-7929-4be6-a3bf-ad6ad8c43a98
		sourceLineageTag: 9a52e8ae-6187-4bd3-9de0-13ef5b9e9147
		dataCategory: Uncategorized

	measure 'Restant te verwachten onverwerkte kosten niet factureren (contract)' = EXTERNALMEASURE("Restant te verwachten onverwerkte kosten niet factureren (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 8f2d7c57-09f1-4665-b77f-1940cd6717ed
		sourceLineageTag: cb0fd2bf-cd4b-482c-a1e7-4df39bc9f168
		dataCategory: Uncategorized

	measure 'Resultaat op contract NOT BLANK' = EXTERNALMEASURE("Resultaat op contract NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 56671460-42db-4c39-9188-9976c5b002bc
		sourceLineageTag: bc928340-87d4-46ba-bbac-6ce748c95ad4
		dataCategory: Uncategorized

	measure 'Resultaat op contract via werkbon' = EXTERNALMEASURE("Resultaat op contract via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service
		lineageTag: 0a90fbe7-8194-4006-a51b-df8c393d7848
		sourceLineageTag: c2badcee-6f39-461e-a406-251f30f8192d
		dataCategory: Uncategorized

	measure 'Resultaat op regiewerkzaamheden' = EXTERNALMEASURE("Resultaat op regiewerkzaamheden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 4b8d0741-cc14-441f-93e6-d458cdba6cf1
		sourceLineageTag: 4c17e725-043d-450f-b8c9-58a35ab92058
		dataCategory: Uncategorized

	measure 'Resultaat op regiewerkzaamheden NOT BLANK' = EXTERNALMEASURE("Resultaat op regiewerkzaamheden NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 9577d903-321f-405c-b712-8de8c6cb3551
		sourceLineageTag: 87184f46-ef4c-4171-aa32-8fe5e487b5e9
		dataCategory: Uncategorized

	measure 'Project resultaat op service contract' = EXTERNALMEASURE("Project resultaat op service contract", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 1534ff0f-42b4-4be1-89bc-a015d5f0d401
		sourceLineageTag: f0caad83-3542-44c0-81f8-ffa40746436c
		dataCategory: Uncategorized

	measure 'Resultaat tot heden regie' = EXTERNALMEASURE("Resultaat tot heden regie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 8dfc7ba6-e733-4780-900a-5de6671d6c93
		sourceLineageTag: 34aacec1-b417-4642-acb1-1d21cf2e77c1
		dataCategory: Uncategorized

	measure 'Te verwachten kosten (storingen)' = EXTERNALMEASURE("Te verwachten kosten (storingen)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 15b731de-e3ea-4fa1-a8d0-46c4d78118c5
		sourceLineageTag: 5f47bc8e-a748-40c2-9a2e-6f120b8950d1
		dataCategory: Uncategorized

	measure 'Te verwachten kosten arbeid (onderhoud)' = EXTERNALMEASURE("Te verwachten kosten arbeid (onderhoud)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 1a11751b-da86-4b4b-ade5-34015cb9a6d8
		sourceLineageTag: 9ecf90d9-1d75-431d-8c48-d8d882ec5f5d
		dataCategory: Uncategorized

	measure 'Te verwachten kosten contract' = EXTERNALMEASURE("Te verwachten kosten contract", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 604e8d55-4e3a-41f4-b7e3-68a1703fcec3
		sourceLineageTag: 5bcd611e-0c4a-44b4-b261-6cb8089af223
		dataCategory: Uncategorized

	measure 'Te verwachten kosten materiaal (onderhoud)' = EXTERNALMEASURE("Te verwachten kosten materiaal (onderhoud)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 59ac8381-5025-42e9-8609-645dc87922c9
		sourceLineageTag: 3577ed26-e667-412b-ae4c-ab4af665f023
		dataCategory: Uncategorized

	measure 'Te verwachten kosten materieel (onderhoud)' = EXTERNALMEASURE("Te verwachten kosten materieel (onderhoud)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.###############;#,0.###############\ -"€";"€"\ #,0.###############
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: c811436b-d775-458f-a7b3-5705bcfe3c04
		sourceLineageTag: 0f4858c9-a50f-4105-bb4c-3b3fefd5ed39
		dataCategory: Uncategorized

	measure 'Te verwachten kosten onderaanneming (onderhoud)' = EXTERNALMEASURE("Te verwachten kosten onderaanneming (onderhoud)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: e5e53ed0-e65c-403f-9cb8-69d6a8c43e43
		sourceLineageTag: 203f5a7f-7877-4c73-955f-83cc31075909
		dataCategory: Uncategorized

	measure 'Te verwachten onverwerkte kosten' = EXTERNALMEASURE("Te verwachten onverwerkte kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 6cf56d4e-c857-42f0-b67f-fb91176539b9
		sourceLineageTag: 308ebbf5-fb4d-49e2-ae9a-e8106de36e44
		dataCategory: Uncategorized

	measure 'Te verwachten Opbrengst contract' = EXTERNALMEASURE("Te verwachten Opbrengst contract", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 498d9bfb-d6e5-4863-978a-157d8575af72
		sourceLineageTag: 2c6052de-64fb-414f-8d77-d4341027abcc
		dataCategory: Uncategorized

	measure 'Te verwachten uren arbeid (onderhoud)' = EXTERNALMEASURE("Te verwachten uren arbeid (onderhoud)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: d4f21f1f-6d00-4f96-a821-c950dc18ad1c
		sourceLineageTag: f987c3bc-6eea-4ce6-bbee-5929cf59b0ff
		dataCategory: Uncategorized

	measure 'Totale kosten' = EXTERNALMEASURE("Totale kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: c0798df7-97ee-47d0-b421-611a25193aae
		sourceLineageTag: 2bc52289-3361-49f5-9567-af1213b06435
		dataCategory: Uncategorized

	measure 'Totale kosten niet via werkbon' = EXTERNALMEASURE("Totale kosten niet via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 5033ac63-6593-493e-84b3-2d0f74deee29
		sourceLineageTag: 536b051f-6bde-4a3d-a892-bd6502d7993c
		dataCategory: Uncategorized

	measure 'Totale kosten via storing LY (in contract)' = EXTERNALMEASURE("Totale kosten via storing LY (in contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: dc810aa6-e08b-47fb-8d2c-9b9a8955cbfe
		sourceLineageTag: 94ff74cf-f16c-4eb6-9e2d-312846f435f7
		dataCategory: Uncategorized

	measure 'Totale kosten via werkbon' = EXTERNALMEASURE("Totale kosten via werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: ff323de0-62ad-41ae-92cb-a5555705e040
		sourceLineageTag: cd7d7703-ba99-4389-aa70-5deed245eada
		dataCategory: Uncategorized

	measure 'Uren contract gerealiseerd' = EXTERNALMEASURE("Uren contract gerealiseerd", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 10554229-71b9-4b6d-b4db-da13d05dd32e
		sourceLineageTag: 6f12a446-49b1-453b-b64e-7ae9fb4650ba
		dataCategory: Uncategorized

	measure 'Uren contract gerealiseerd tekst' = EXTERNALMEASURE("Uren contract gerealiseerd tekst", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 7b1097ad-72bc-43ed-8336-3fab4847a9f3
		sourceLineageTag: 6f9c06fe-96fb-496e-a9ea-eaefe1fec7b4
		dataCategory: Uncategorized

	measure 'Uren contract te verwachten tekst' = EXTERNALMEASURE("Uren contract te verwachten tekst", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.04 Service\nog te verwachten
		lineageTag: 31a745b2-95f8-42fc-b4c8-a4dda5d8b598
		sourceLineageTag: 015602d2-f4b9-4aec-be4c-ec3a0ecb356c
		dataCategory: Uncategorized

	measure 'VC resultaat projecten' = EXTERNALMEASURE("VC resultaat projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 18e7f902-cae2-4ffd-98e5-a7dc30adb711
		sourceLineageTag: 01a14182-6509-4167-bbc7-4cfe580b980a
		dataCategory: Uncategorized

	measure 'Verwacht rendement service project' = EXTERNALMEASURE("Verwacht rendement service project", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 05d6c7b8-67a5-48d9-a07d-83308e8d288a
		sourceLineageTag: c2108203-aee8-40ec-9d74-e289aef6116a
		dataCategory: Uncategorized

	measure 'Verwacht rendement service project (contract)' = EXTERNALMEASURE("Verwacht rendement service project (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0%;-#,0%;#,0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: af5c875c-d626-4b07-9d6e-264bff8a67db
		sourceLineageTag: da34cbe7-417e-41b0-8090-ebd7391fe414
		dataCategory: Uncategorized

	measure 'Verwacht resultaat service project' = EXTERNALMEASURE("Verwacht resultaat service project", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: cf78b9e9-3b22-4384-8599-6ffe8e2ab89d
		sourceLineageTag: ea835954-fab4-4e0d-a1f5-9fcfffa5a533
		dataCategory: Uncategorized

	measure 'Verwacht resultaat service project (contract)' = EXTERNALMEASURE("Verwacht resultaat service project (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 5f9775f5-c0ed-43ce-ae6c-9b4754194be0
		sourceLineageTag: c8bdd234-38a7-4dc7-be3b-c4c0e100bde3
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs overig (regie)' = EXTERNALMEASURE("Definitieve kostprijs overig (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 425f4a15-06db-466a-87df-b0d4e14116e6
		sourceLineageTag: ce0dc4c5-ce7c-4909-9217-3bd785426319
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs overig (contract)' = EXTERNALMEASURE("Definitieve kostprijs overig (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 9bee436f-226e-47ee-bc57-5eeca75e0133
		sourceLineageTag: 51c7c9b3-cdc0-4127-986e-12af0c98f3db
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs materiaal (contract)' = EXTERNALMEASURE("Definitieve kostprijs materiaal (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: bbabc23c-00ba-4818-9d68-c1bd333e45aa
		sourceLineageTag: 97031c7a-fca9-427e-abd4-f705a64602be
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs arbeid (contract)' = EXTERNALMEASURE("Definitieve kostprijs arbeid (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 020591c7-ea97-4001-90a4-892252097f7b
		sourceLineageTag: e0c80194-9695-42f4-9f6a-7fc8ae709e44
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs (contract)' = EXTERNALMEASURE("Definitieve kostprijs (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 26e2b179-5054-4f81-a3e7-360a943d907f
		sourceLineageTag: 81afce80-223b-4bac-a28b-41ac6d8804ea
		dataCategory: Uncategorized

	measure 'Project resultaat NOT BLANK' = EXTERNALMEASURE("Project resultaat NOT BLANK", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 80b8d293-3e1d-41bb-83c6-63984c9dd973
		sourceLineageTag: 838c7bdf-7063-4b72-b40d-47d30bc374f1
		dataCategory: Uncategorized

	measure 'Project resultaat service project' = EXTERNALMEASURE("Project resultaat service project", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Ratio en resultaat
		lineageTag: 59716dca-6f5f-439d-8a5c-bf0fa39184c5
		sourceLineageTag: 38aae0d9-a7d0-4730-8d0f-7b2bd476e464
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs (regie)' = EXTERNALMEASURE("Definitieve kostprijs (regie)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: d889b6f5-c34c-4c7e-87cd-be6557baf0ab
		sourceLineageTag: 784cc89c-1a21-4c37-8677-9d7448e596c1
		dataCategory: Uncategorized

	measure 'Project omzet (order)' = EXTERNALMEASURE("Project omzet (order)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project omzet
		lineageTag: 630c97f9-d9a1-4887-a9ac-29d51ba12a01
		sourceLineageTag: e3b296a1-61e7-4bc9-9096-8bbb7d1d43ba
		dataCategory: Uncategorized

	measure 'Projectjournalisering kosten' = EXTERNALMEASURE("Projectjournalisering kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 890582bb-208f-4ee5-a705-041c019b387a
		sourceLineageTag: 5a1328ae-a616-4418-a0e9-66b6bdb451a7
		dataCategory: Uncategorized

	measure 'Projectjournalisering opbrengsten' = EXTERNALMEASURE("Projectjournalisering opbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 46053b7a-65f8-4167-b9c7-f62a1a14ed92
		sourceLineageTag: a4fd0b92-1a3e-4c47-be18-7169dd475a58
		dataCategory: Uncategorized

	measure 'Projectjournalisering project resultaat' = EXTERNALMEASURE("Projectjournalisering project resultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 9cf494dc-4404-4e07-a0d0-9e1b3be86b92
		sourceLineageTag: d0f943fd-74b3-4abf-a11b-748d16a287e1
		dataCategory: Uncategorized

	measure 'Projectjournalisering projectwaarderingen regulierer boeking' = EXTERNALMEASURE("Projectjournalisering projectwaarderingen regulierer boeking", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 7c5326f8-c667-4ef5-9e3b-679db2e45600
		sourceLineageTag: 3c41b9d8-782e-4b57-a598-e047a763cc4a
		dataCategory: Uncategorized

	measure 'Projectjournalisering projectwaarderingen tegenboeking bij vrijval' = EXTERNALMEASURE("Projectjournalisering projectwaarderingen tegenboeking bij vrijval", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: a3a674be-e569-41d3-83ee-a16b61c57d81
		sourceLineageTag: 47641c39-61f0-4c50-96d8-6410c50ef75f
		dataCategory: Uncategorized

	/// Projectopbrengsten - projectkosten. Geeft inzicht in het effect van elk project op het resultaat in de exploitatierekening in de geselecteerde periode. Exclusief dekkingen.
	measure 'OHW mutatie in exploitatie' = EXTERNALMEASURE("OHW mutatie in exploitatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: ada488a5-15b9-4acc-81b3-6c32842da151
		sourceLineageTag: 6ef2d737-0403-4f46-adf9-b5be365ea32b
		dataCategory: Uncategorized

	measure 'Aantal definitieve inkoopfacturen' = EXTERNALMEASURE("Aantal definitieve inkoopfacturen", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 09c34bd0-9e51-40cb-bc10-bd3c2064b6fb
		sourceLineageTag: bcd8f413-769a-4a92-9870-cba5837d15f8
		dataCategory: Uncategorized

	measure 'Aantal inkoopfacturen' = EXTERNALMEASURE("Aantal inkoopfacturen", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: c195628d-9be3-4614-9960-0f0355235a90
		sourceLineageTag: f32da600-766d-4be2-807d-47940c850292
		dataCategory: Uncategorized

	measure 'Aantal openstaande inkoopfacturen' = EXTERNALMEASURE("Aantal openstaande inkoopfacturen", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: b6576731-9d4e-4268-a484-5527e42b2082
		sourceLineageTag: 32d2440d-875f-4fc6-b3c0-17c859d85753
		dataCategory: Uncategorized

	measure 'Aantal pakbonnen' = EXTERNALMEASURE("Aantal pakbonnen", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 88b47c64-8928-4253-aad8-cbc9fac430ef
		sourceLineageTag: 579570d6-9c5d-4e0e-8ae8-592154af6b8c
		dataCategory: Uncategorized

	measure 'Aantal uren' = EXTERNALMEASURE("Aantal uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: bf95564b-4bf5-421d-91e0-5954a6002874
		sourceLineageTag: 82a3dae3-aea1-4a94-89de-551a05abbef5
		dataCategory: Uncategorized

	measure 'Kosten niet factureren (contract)' = EXTERNALMEASURE("Kosten niet factureren (contract)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: a3c21666-0aef-4500-99c6-947a2841402c
		sourceLineageTag: 12a6fdf5-afbc-48cf-b646-0efcd64c9b02
		dataCategory: Uncategorized

	measure Crediteur = EXTERNALMEASURE("Crediteur", INTEGER, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 779ea724-6fca-40b1-be03-d1afb2c22920
		sourceLineageTag: 8b1be4a2-6966-4c92-899c-f720375fb859
		dataCategory: Uncategorized

	measure 'Kosten inkoopfactuur' = EXTERNALMEASURE("Kosten inkoopfactuur", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 7dfebb7b-a0d4-455b-ad72-fc03f5606df2
		sourceLineageTag: fd504cd2-e6e4-4d6e-ad6f-4334293f5c64
		dataCategory: Uncategorized

	measure 'Kosten Overig' = EXTERNALMEASURE("Kosten Overig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: ff61edcf-1f78-4adc-80f2-b92b8c07ae70
		sourceLineageTag: 870bdd58-c295-4d93-b1a0-0746809119b4
		dataCategory: Uncategorized

	measure 'Kosten pakbon' = EXTERNALMEASURE("Kosten pakbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 30232ec7-5c0c-4546-84ba-12eea4b50257
		sourceLineageTag: 43404d6b-6398-4d38-af50-d7c0ed89517e
		dataCategory: Uncategorized

	measure 'Kosten totaal' = EXTERNALMEASURE("Kosten totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 68bc8e63-7b92-4917-ac5a-dcedc5e9dc00
		sourceLineageTag: a8aeba6c-944b-4d48-8c4d-76bbce26fe25
		dataCategory: Uncategorized

	measure 'kosten uren' = EXTERNALMEASURE("kosten uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: cabc18bc-3097-4688-898c-d5c2be77cb73
		sourceLineageTag: e24ef49c-eb98-4063-b14c-7a87799f3b7a
		dataCategory: Uncategorized

	measure 'Periode openstaand (gemiddeld)' = EXTERNALMEASURE("Periode openstaand (gemiddeld)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonnen
		lineageTag: b1edcd1a-176b-49c8-845a-56245a3fd9be
		sourceLineageTag: b0730b56-ed49-4802-a7ae-b09b6a79dbec
		dataCategory: Uncategorized

	measure 'Regie kosten' = EXTERNALMEASURE("Regie kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 4edcced3-d5fc-4adc-894d-3582b33c9ed2
		sourceLineageTag: 84b6203f-c37c-4073-9de6-2d362a5592fe
		dataCategory: Uncategorized

	measure 'Melding verschil op dekking' = EXTERNALMEASURE("Melding verschil op dekking", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 39d77565-38cb-43b5-8e75-09fa3ce3a014
		sourceLineageTag: 71cc7262-9469-4110-89c8-503dc4c372f6
		dataCategory: Uncategorized

	/// Het percentage van de totale projectkosten dat via doorbelasting op de balans wordt geactiveerd als OHW.
	measure 'Ratio doorbelasting van projectkosten' = EXTERNALMEASURE("Ratio doorbelasting van projectkosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: f2c7ee48-fc37-4218-9841-00907689d715
		sourceLineageTag: 42de75d2-3a60-4d41-a258-af3fa024f585
		dataCategory: Uncategorized

	/// Het percentage van de totale projectkosten dat via doorbelasting op de balans wordt geactiveerd als OHW.
	measure 'Ratio doorbelasting van projectopbrengsten' = EXTERNALMEASURE("Ratio doorbelasting van projectopbrengsten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 86173a83-30c4-48c1-80e9-4b5a23b782e8
		sourceLineageTag: ed93ffe3-0e31-4624-aac0-0cdf61bfff53
		dataCategory: Uncategorized

	measure Boekingsbedrag = EXTERNALMEASURE("Boekingsbedrag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: 412ef648-45d7-40f9-9afb-862b977dbe3e
		sourceLineageTag: e879a552-6bd1-49a0-a916-a9b71f9391e6
		dataCategory: Uncategorized

	measure '% Omzet van totaal' = EXTERNALMEASURE("% Omzet van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 26110b66-3f27-4c95-a4de-35b568828280
		sourceLineageTag: 2c2506b3-f27e-4e48-b13d-b74daed5e907
		dataCategory: Uncategorized

	measure 'Bruto rendement' = EXTERNALMEASURE("Bruto rendement", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 41a035de-8792-4c15-b105-a1bc1da0fa90
		sourceLineageTag: 7f413bce-1bfa-4f58-af71-da6e1338ffa6
		dataCategory: Uncategorized

	measure 'Bruto rendement LY' = EXTERNALMEASURE("Bruto rendement LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 808f1dd4-1182-4d7c-b99d-2caffcbf4549
		sourceLineageTag: dde25623-f4e1-46b1-a468-4fa1d30ccd1d
		dataCategory: Uncategorized

	measure 'Bruto rendement YTD LY' = EXTERNALMEASURE("Bruto rendement YTD LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: c43ad923-a4c0-4eea-932e-769b5f5d729f
		sourceLineageTag: 7d4f70cd-ccee-453a-bddf-d43bd8f4546b
		dataCategory: Uncategorized

	measure Brutowinst = EXTERNALMEASURE("Brutowinst", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: ff10bc0f-653e-4d09-a0bf-cdba049d241f
		sourceLineageTag: 0dd5e4d4-06c1-487d-9b79-35429a08559e
		dataCategory: Uncategorized

	measure 'Brutowinst LY' = EXTERNALMEASURE("Brutowinst LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 9d60c33f-2c81-4270-9f3e-4ad440233f25
		sourceLineageTag: 5dcfae68-6b78-46ce-af1b-0add43f51f3d
		dataCategory: Uncategorized

	measure 'Brutowinst YTD' = EXTERNALMEASURE("Brutowinst YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 41fd38bb-e31a-4d47-80ca-494c8f68d331
		sourceLineageTag: 72995bda-a0c4-4feb-8103-b041740bff2e
		dataCategory: Uncategorized

	measure 'Brutowinst YTDLY' = EXTERNALMEASURE("Brutowinst YTDLY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 0902418b-fa7b-4f6e-8040-37385ba85ba4
		sourceLineageTag: cd8386cd-2757-4166-a891-cd5d9122b72b
		dataCategory: Uncategorized

	/// Zie [Directe kosten]. Betreft directe kosten over dezelfde periode vorig jaar.
	measure 'Directe kosten LY' = EXTERNALMEASURE("Directe kosten LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 4364648d-eb6f-4a33-a80f-2b44897f9a41
		sourceLineageTag: 09bfc08d-a281-4c09-aea4-c6746ffab5b6
		dataCategory: Uncategorized

	measure 'Directe kosten neg' = EXTERNALMEASURE("Directe kosten neg", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 6c24fde1-d36d-4f19-a3b5-b224b38fe25a
		sourceLineageTag: ddb3b978-76e5-4c04-bf80-37fe1b9b5438
		dataCategory: Uncategorized

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD' = EXTERNALMEASURE("Directe kosten YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 3645597a-dc73-4d3e-ac77-dbbaf32ce6b3
		sourceLineageTag: d9c8eabd-843b-4345-8556-fa2d61f76a35
		dataCategory: Uncategorized

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY' = EXTERNALMEASURE("Directe kosten YTDLY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 2c0d1795-6387-4788-af4f-5364edce3979
		sourceLineageTag: 3b012baa-9db2-4209-9d94-8fe75bff8eeb
		dataCategory: Uncategorized

	measure 'Indirecte kosten' = EXTERNALMEASURE("Indirecte kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: def6843e-9fc2-441f-b61a-1429f6e14fca
		sourceLineageTag: c407b5a8-cf88-4be7-b703-cfe5e256a79b
		dataCategory: Uncategorized

	measure 'Indirecte kosten LY' = EXTERNALMEASURE("Indirecte kosten LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: b84e8f35-04d9-44d5-b911-9cc97409fb5b
		sourceLineageTag: 12aaef36-f2be-4ace-868e-990f3a4d2690
		dataCategory: Uncategorized

	measure 'Indirecte kosten neg' = EXTERNALMEASURE("Indirecte kosten neg", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 8c64ca71-c519-48b5-b73c-0455a04eddf6
		sourceLineageTag: 89aea0ee-3aee-4ae9-8bd4-3be97332f6ef
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTD' = EXTERNALMEASURE("Indirecte kosten YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: a2cfc135-3870-45a1-be27-048714be4ee8
		sourceLineageTag: b3c4e702-396f-4ff0-8546-8f51859c7288
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTDLY' = EXTERNALMEASURE("Indirecte kosten YTDLY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: f3400bf2-f84c-4e4a-9b92-94e43692417b
		sourceLineageTag: d8372d50-143b-40d3-bc50-0d6a6f53442e
		dataCategory: Uncategorized

	measure 'Netto rendement' = EXTERNALMEASURE("Netto rendement", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: ef63b6c7-69aa-4a25-8ed8-bfb8a1b11d99
		sourceLineageTag: ec8f4cb3-efa8-42d9-b3b7-d831a4bbfd96
		dataCategory: Uncategorized

	measure 'Netto rendement 12 maanden' = EXTERNALMEASURE("Netto rendement 12 maanden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: db54435a-a8b5-4aa0-999c-4fd8cd72501f
		sourceLineageTag: 3bfd8fab-5ca8-49be-9307-41fe6009fca5
		dataCategory: Uncategorized

	measure 'Netto rendement LY' = EXTERNALMEASURE("Netto rendement LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: f6b845be-4fdd-4008-87e3-94df3b878c15
		sourceLineageTag: 3d90ebc1-7227-45e9-9adb-af7f0a3e10d1
		dataCategory: Uncategorized

	measure 'Netto rendement YTD' = EXTERNALMEASURE("Netto rendement YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 5dc7f675-8ce7-41bf-a8e6-6eff48bea1de
		sourceLineageTag: 38ceb8a8-262e-4f2b-bd7c-b2832cfdff34
		dataCategory: Uncategorized

	measure 'Netto rendement YTD LY' = EXTERNALMEASURE("Netto rendement YTD LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 0a56c986-f243-41a6-b6cc-f9db19241db9
		sourceLineageTag: 07ce0c35-fa62-4688-89e1-d06950475e97
		dataCategory: Uncategorized

	measure Nettowinst = EXTERNALMEASURE("Nettowinst", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 022fbee2-6beb-4ff6-b1b9-c27fac9646b2
		sourceLineageTag: b2082379-4db9-49f2-8135-d80a6378ab5f
		dataCategory: Uncategorized

	measure 'nettowinst 12 maanden' = EXTERNALMEASURE("nettowinst 12 maanden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 2fe4cb78-d369-4e90-a326-701fc0a08738
		sourceLineageTag: 1efc4e9c-1222-4881-9bf2-10b0bd8a2e9b
		dataCategory: Uncategorized

	measure 'Nettowinst LY' = EXTERNALMEASURE("Nettowinst LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 799379a9-7914-4580-95dd-b921bd4fa8c2
		sourceLineageTag: ceb1102c-abfc-4c86-b2fc-34f45940ad86
		dataCategory: Uncategorized

	measure 'Nettowinst YTD' = EXTERNALMEASURE("Nettowinst YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 872390e3-b9eb-464f-9e3b-42cec57ef39f
		sourceLineageTag: ebbfcb40-71c8-4563-971d-2948609e7f0e
		dataCategory: Uncategorized

	measure 'Nettowinst YTDLY' = EXTERNALMEASURE("Nettowinst YTDLY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 5442cfd9-c959-4bd9-a8a7-64453c10bbe0
		sourceLineageTag: c9d0f7b0-7477-46e6-b11c-d924eff4f9b4
		dataCategory: Uncategorized

	measure 'Omzet 12 maanden' = EXTERNALMEASURE("Omzet 12 maanden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 574955f5-18a1-4df8-bd93-34ea9fea4df8
		sourceLineageTag: 63a838ac-4a88-49fa-bfc2-5102a2e10744
		dataCategory: Uncategorized

	measure 'Omzet LY' = EXTERNALMEASURE("Omzet LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 957c48a0-4cae-43f2-b96e-b7e67c965241
		sourceLineageTag: 5cbc7f23-8fc5-4d4e-8080-76e81e953712
		dataCategory: Uncategorized

	measure 'Omzet YTD' = EXTERNALMEASURE("Omzet YTD", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 3e21b1fd-ecc7-4540-978b-3ac6e6842fe0
		sourceLineageTag: 0c453be9-4d61-42cd-a4ea-595bdf52ef82
		dataCategory: Uncategorized

	measure 'Omzet YTDLY' = EXTERNALMEASURE("Omzet YTDLY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: ece45504-5fad-4e9f-b687-71d0e5ed1640
		sourceLineageTag: 89464101-d50b-46a5-a4e6-bec7fc651d0c
		dataCategory: Uncategorized

	measure '% Directe kosten van totaal' = EXTERNALMEASURE("% Directe kosten van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: e304f62b-6626-4288-9691-dc20bec8b3cb
		sourceLineageTag: 81b55c84-1588-4517-859c-862436eee572
		dataCategory: Uncategorized

	measure '% Indirecte kosten van totaal' = EXTERNALMEASURE("% Indirecte kosten van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 7a569699-2dd1-4dd9-889d-e2833fa70e29
		sourceLineageTag: 6c00c98c-82c9-41e8-80b7-115534f23e91
		dataCategory: Uncategorized

	measure '% Omzet van totaal (benchmark schema)' = EXTERNALMEASURE("% Omzet van totaal (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 6843b5b2-00c2-4cc4-a41f-33954c974bca
		sourceLineageTag: 44371c11-39fd-43c0-ac50-db38bc0f897e
		dataCategory: Uncategorized

	measure 'Bruto rendement (benchmark schema)' = EXTERNALMEASURE("Bruto rendement (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 67c76adc-2c3e-41e4-8ecd-723d213faa19
		sourceLineageTag: ae8a03bf-86f9-4e75-b25d-704f2b23644a
		dataCategory: Uncategorized

	measure 'Bruto rendement LY (benchmark schema)' = EXTERNALMEASURE("Bruto rendement LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 873a6ca2-2b6b-4f25-b59b-a41e55a6103f
		sourceLineageTag: d22dd379-177e-4092-aeb5-170d5d7ff534
		dataCategory: Uncategorized

	measure 'Bruto rendement YTD LY (benchmark schema)' = EXTERNALMEASURE("Bruto rendement YTD LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 2adedfab-a655-4f14-8671-323b3af20604
		sourceLineageTag: 100ebebe-dc88-4157-ac53-c7a54f7a81f1
		dataCategory: Uncategorized

	measure 'Brutowinst (benchmark schema)' = EXTERNALMEASURE("Brutowinst (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 7c53ba31-eb02-40cb-95d6-1cff9649758d
		sourceLineageTag: 0f987273-7e76-4ce6-9ffc-c0029ff5258f
		dataCategory: Uncategorized

	measure 'Brutowinst LY (benchmark schema)' = EXTERNALMEASURE("Brutowinst LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: f64e9da2-5be0-4d54-90e1-d0a9e2b4536e
		sourceLineageTag: 74d3b113-3a53-4a03-90a8-ec5541b8d530
		dataCategory: Uncategorized

	measure 'Brutowinst YTD (benchmark schema)' = EXTERNALMEASURE("Brutowinst YTD (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 3e78a780-3b56-4c58-ac43-558205f9dd44
		sourceLineageTag: 44a39e15-8718-4d5a-b710-1f6380744b41
		dataCategory: Uncategorized

	measure 'Brutowinst YTDLY (benchmark schema)' = EXTERNALMEASURE("Brutowinst YTDLY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 64eeb42b-7cdc-4838-a843-b7af915a5da6
		sourceLineageTag: 53d69d77-39b1-40d4-9fdc-4549beffb4a1
		dataCategory: Uncategorized

	measure '% Directe kosten van totaal (benchmark schema)' = EXTERNALMEASURE("% Directe kosten van totaal (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 3562e7b6-bc93-4ff2-8f67-c9c6ff2a05db
		sourceLineageTag: 1c557bc8-569f-477d-88d3-dbb420315fa2
		dataCategory: Uncategorized

	measure '% Indirecte kosten van totaal (benchmark schema)' = EXTERNALMEASURE("% Indirecte kosten van totaal (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.00\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: c24bb452-efed-4f38-8696-8c1a89204d8c
		sourceLineageTag: b0068950-edd4-4050-ad9a-29014f2bfe3d
		dataCategory: Uncategorized

	measure '% Omzet van totaal (standaard)' = EXTERNALMEASURE("% Omzet van totaal (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 25223149-3ff1-4f34-bf17-8f2afc0a9783
		sourceLineageTag: e33db4c9-0859-46f2-8d83-ff0f6448ace5
		dataCategory: Uncategorized

	measure 'Bruto rendement (standaard)' = EXTERNALMEASURE("Bruto rendement (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: a11d4b22-913f-43b6-a54c-64f0618b9263
		sourceLineageTag: 99901552-f88d-4b4c-9b12-f60fc963b383
		dataCategory: Uncategorized

	measure 'Bruto rendement LY (standaard)' = EXTERNALMEASURE("Bruto rendement LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 7c7c5217-a21c-4241-b3b5-839408fd7682
		sourceLineageTag: 65cdf5ca-a402-48b9-9920-22432c1abfb1
		dataCategory: Uncategorized

	measure 'Bruto rendement YTD LY (standaard)' = EXTERNALMEASURE("Bruto rendement YTD LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: b681ad2e-fca7-4556-b490-42fa90de3c3b
		sourceLineageTag: c976eeca-acc2-4382-a2ad-f0a15d45fae5
		dataCategory: Uncategorized

	measure 'Brutowinst (standaard)' = EXTERNALMEASURE("Brutowinst (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: b889029c-87e2-4c46-96c9-b1f960627a4d
		sourceLineageTag: 6b222b72-04de-4902-a8e6-3aa4b012756d
		dataCategory: Uncategorized

	measure 'Brutowinst LY (standaard)' = EXTERNALMEASURE("Brutowinst LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 04f7d5c1-415d-423a-9bbf-070c03d4edff
		sourceLineageTag: d13ab6f2-a7ee-4691-9c68-a981207f22fb
		dataCategory: Uncategorized

	measure 'Brutowinst YTD (standaard)' = EXTERNALMEASURE("Brutowinst YTD (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: ad091f2d-7532-449c-9a10-1edf3df50b75
		sourceLineageTag: 95143ff3-dffa-4d82-afc6-123462975b6f
		dataCategory: Uncategorized

	measure 'Brutowinst YTDLY (standaard)' = EXTERNALMEASURE("Brutowinst YTDLY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: ec3687ed-108c-41e9-9251-eadffaba3d20
		sourceLineageTag: cb6ffb50-3c2f-456a-9d44-8bb4f884da34
		dataCategory: Uncategorized

	measure 'Omzet (standaard)' = EXTERNALMEASURE("Omzet (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: c5da8fc8-2915-4289-8539-4a84cb9f6428
		sourceLineageTag: e3ca582d-2ce5-4fd2-b9da-77ff9fa30180
		dataCategory: Uncategorized

	measure 'Omzet 12 maanden (standaard)' = EXTERNALMEASURE("Omzet 12 maanden (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 0ca1d239-854c-4238-8bed-2cba42da7097
		sourceLineageTag: b3309312-59da-4cfc-a256-16c445dcb892
		dataCategory: Uncategorized

	measure 'Omzet LY (standaard)' = EXTERNALMEASURE("Omzet LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: de355258-803b-4553-bf2c-89614ac4fe6b
		sourceLineageTag: 1e653ece-85e6-417f-94e5-891ea4a16b42
		dataCategory: Uncategorized

	measure 'Omzet YTD (standaard)' = EXTERNALMEASURE("Omzet YTD (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 77180536-bc31-4f3d-92d6-1ce26802509e
		sourceLineageTag: d69ec18b-bf08-4fb3-ba59-f194a1f95214
		dataCategory: Uncategorized

	measure 'Omzet YTDLY (standaard)' = EXTERNALMEASURE("Omzet YTDLY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: f21996d3-ffdc-4024-8e3b-7871ed29d6b4
		sourceLineageTag: 1d7c1584-5cbd-4366-9fab-384290b3720d
		dataCategory: Uncategorized

	measure '% Directe kosten van totaal (standaard)' = EXTERNALMEASURE("% Directe kosten van totaal (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 95b72fa7-a0e1-4da2-b6a9-474d73cd0580
		sourceLineageTag: 5e48a782-5743-4309-b56c-e58d2b4cbba8
		dataCategory: Uncategorized

	measure '% Indirecte kosten van totaal (standaard)' = EXTERNALMEASURE("% Indirecte kosten van totaal (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: d0a3bd10-99da-4afc-9a8b-2c24e49d19c5
		sourceLineageTag: 20deb12c-3b06-4183-bbf6-bb39d5f98827
		dataCategory: Uncategorized

	measure 'Geselecteerde methode resultaat bepaling' = EXTERNALMEASURE("Geselecteerde methode resultaat bepaling", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen
		lineageTag: eda79d53-3706-4454-baec-a9bc7e483208
		sourceLineageTag: 7a190054-9f7a-4ec4-a8ac-3b81296c5657
		dataCategory: Uncategorized

	measure 'jaar resultaat LY' = EXTERNALMEASURE("jaar resultaat LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: de00ada0-2216-43a7-b9ee-08084452cbe9
		sourceLineageTag: a26145c5-9160-4de6-bdff-14e0b8269162
		dataCategory: Uncategorized

	measure 'resultaat W&V' = EXTERNALMEASURE("resultaat W&V", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: aea75b75-d763-4154-ac8a-d34481b9be89
		sourceLineageTag: 5301f534-cb97-4d02-98d1-9e09637a4480
		dataCategory: Uncategorized

	measure BrowseDepth = EXTERNALMEASURE("BrowseDepth", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten
		lineageTag: 5e3c6170-5b86-47ce-9bec-0e65d04865c4
		sourceLineageTag: 11f4eeda-e03a-4a2e-84f8-f201bcdd8e41
		dataCategory: Uncategorized

	measure 'Niveau 3 tonen' = EXTERNALMEASURE("Niveau 3 tonen", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten
		lineageTag: d0b7bc3d-1dac-4ceb-a64a-5cb60bc91ad6
		sourceLineageTag: 608424d7-dbb8-448d-98d0-5053542c3e4b
		dataCategory: Uncategorized

	measure 'Niveau 2 tonen' = EXTERNALMEASURE("Niveau 2 tonen", STRING, "DirectQuery to AS - SSM")
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten
		lineageTag: 81600133-a278-4b63-94e4-0a67fe4ae2d1
		sourceLineageTag: 27837a5a-9a43-4c64-b14d-792496bcaa7c
		dataCategory: Uncategorized

	measure MaxNodeDepth = EXTERNALMEASURE("MaxNodeDepth", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten
		lineageTag: 280ce27c-93dc-4e91-90a8-acffd0c527cf
		sourceLineageTag: d6bf1080-026a-4b2b-8b08-c22d8baa3d23
		dataCategory: Uncategorized

	measure '% onderhouds paragrafen met WvB Arbeid' = EXTERNALMEASURE("% onderhouds paragrafen met WvB Arbeid", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: 8965317e-8c9c-484c-969b-0902e7da3609
		sourceLineageTag: 9f2bc680-6bd5-4867-9adf-07b544d9d339
		dataCategory: Uncategorized

	measure 'Aantal onderhoud werkbonparagrafen' = EXTERNALMEASURE("Aantal onderhoud werkbonparagrafen", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 4a2cda2c-000a-40d1-95bb-c0fe69636318
		sourceLineageTag: 672a07e9-9e18-4cfb-a528-e415b413cebd
		dataCategory: Uncategorized

	measure 'Aantal uur nog te doen' = EXTERNALMEASURE("Aantal uur nog te doen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning\Werkvoorraad
		lineageTag: c943cf54-6282-468e-96b5-3fd49bc7f5ae
		sourceLineageTag: 3b23b8a8-433d-4b32-bbb9-9e4a8dda8975
		dataCategory: Uncategorized

	measure 'geselecteerde methode' = EXTERNALMEASURE("geselecteerde methode", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: e9d1c9f4-9541-4dc5-8c4e-24af8444932d
		sourceLineageTag: 7e7791e0-ef9b-4a5c-8b95-d231237b1b5e
		dataCategory: Uncategorized

	measure 'Onbekend (regie/project) % van totaal' = EXTERNALMEASURE("Onbekend (regie/project) % van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: 13b894db-794d-444d-86fb-91d94880c767
		sourceLineageTag: a02d26e7-1e6e-4cb3-b55b-e411aedd7a69
		dataCategory: Uncategorized

	measure 'onderhoud % van totaal' = EXTERNALMEASURE("onderhoud % van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: 869a6a8c-6e08-46a6-bfc0-b2dfd16009fa
		sourceLineageTag: e40557ce-d4bc-4bff-ae9f-8e3aa39a3d73
		dataCategory: Uncategorized

	measure 'Onderhoud uitgevoerd (reisuren)' = EXTERNALMEASURE("Onderhoud uitgevoerd (reisuren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 2f75e685-ac46-4ec0-9c8c-7a30a16a0583
		sourceLineageTag: 288c15ba-9232-4ac6-a9d1-05ffcd67c19c
		dataCategory: Uncategorized

	measure 'Onderhoud uitgevoerd (werkelijke uren)' = EXTERNALMEASURE("Onderhoud uitgevoerd (werkelijke uren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 90da96bd-aece-4194-9e94-9c078a59aa45
		sourceLineageTag: 06d77aa2-b66e-4429-87bc-1852d1a7861b
		dataCategory: Uncategorized

	measure 'Onderhoud uitgevoerd (werkuren)' = EXTERNALMEASURE("Onderhoud uitgevoerd (werkuren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 92fd0f00-dc01-434d-b7f3-ba3d9a3f9cec
		sourceLineageTag: 16900cb8-da37-4037-b828-ff64d3ff04f7
		dataCategory: Uncategorized

	/// Betreft de uren op de werkvoorbereiding van de werkbonparagrafen van het type Onderhoud en status Uitgevoerd.  
	measure 'Onderhoud uitgevoerd (WvB uren)' = EXTERNALMEASURE("Onderhoud uitgevoerd (WvB uren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: c1cb0269-12a7-4f8b-a332-1c98ff1649dc
		sourceLineageTag: 5abc9048-fb0b-4fd8-b91a-c1f838f6856b
		dataCategory: Uncategorized

	measure 'Onderhoud uitgevoerd gemiddeld (reisuren)' = EXTERNALMEASURE("Onderhoud uitgevoerd gemiddeld (reisuren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 74f46357-c8f6-49fc-b1f6-87609906a253
		sourceLineageTag: 421ad405-5ff8-47f3-8a77-bbd0ee16ce0e
		dataCategory: Uncategorized

	measure 'Onderhoud uitgevoerd gemiddeld (werkelijke uren)' = EXTERNALMEASURE("Onderhoud uitgevoerd gemiddeld (werkelijke uren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 142a11c1-82d6-4aca-96cf-20aff6940f5d
		sourceLineageTag: 97fdab82-12da-425f-940a-1169169730ea
		dataCategory: Uncategorized

	measure 'Onderhoud uitgevoerd gemiddeld (werkuren)' = EXTERNALMEASURE("Onderhoud uitgevoerd gemiddeld (werkuren)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 3c0a172d-39f0-4ad8-9ef2-1c2d5c6598cb
		sourceLineageTag: 2969bd85-2f71-443d-9f3f-3dadede4aabe
		dataCategory: Uncategorized

	measure 'storing % van totaal' = EXTERNALMEASURE("storing % van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: 8aa0c5a1-ee43-4da1-887b-b7c882637917
		sourceLineageTag: c6c6dace-ce97-4060-bd45-262220e66071
		dataCategory: Uncategorized

	measure 'Totaal onderhoud' = EXTERNALMEASURE("Totaal onderhoud", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: 44dcea4d-83bd-4a37-b370-3dbfa7c41988
		sourceLineageTag: cf84eae8-1f7e-4535-8171-eac3512f8cbf
		dataCategory: Uncategorized

	measure 'Werkelijk onderhoud % van WvB' = EXTERNALMEASURE("Werkelijk onderhoud % van WvB", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: 5084d46f-b8b7-4ca5-9a19-01037fa95bd8
		sourceLineageTag: 8bf2778b-b65e-4b93-8850-c0a0bdb183fe
		dataCategory: Uncategorized

	measure 'Beschikbare uren' = EXTERNALMEASURE("Beschikbare uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: 7bb6a474-ce7b-4eab-8a1d-cb9cfd40324b
		sourceLineageTag: e61a7a58-12c8-4fe7-8720-d6a4522619e5
		dataCategory: Uncategorized

	measure Contracturen = EXTERNALMEASURE("Contracturen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: c8b5ecf6-f5ac-4f2c-ac53-ac5bd532cb5a
		sourceLineageTag: 44057d25-e40a-4918-8064-827075ea93b7
		dataCategory: Uncategorized

	measure 'Geplande uren' = EXTERNALMEASURE("Geplande uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: e439a1dd-55e4-4654-86a3-169a697ab011
		sourceLineageTag: 7220d6b2-44c4-4b16-8896-31bcddf6f760
		dataCategory: Uncategorized

	measure 'Geplande uren direct' = EXTERNALMEASURE("Geplande uren direct", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: f8691099-18d3-476f-8f16-70ab5ada1291
		sourceLineageTag: 5f7620a4-3ee4-4552-95e7-8f082e325b5f
		dataCategory: Uncategorized

	measure 'Geplande uren indirect' = EXTERNALMEASURE("Geplande uren indirect", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: d13b5cc0-e05f-4061-b433-88283c180282
		sourceLineageTag: ca33db63-d499-4310-b2b2-35373dc0d2cd
		dataCategory: Uncategorized

	measure 'Geplande uren indirect (-)' = EXTERNALMEASURE("Geplande uren indirect (-)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: 28223b93-64c2-47d9-b098-0bf9a08fdd13
		sourceLineageTag: ff5355a4-b4a1-418e-858f-f99df1b90b08
		dataCategory: Uncategorized

	measure 'Geselecteerd gemiddelde uitvoertijd onderhoud' = EXTERNALMEASURE("Geselecteerd gemiddelde uitvoertijd onderhoud", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.00
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: 52c47162-54a7-4aec-95df-f5bc2687f04c
		sourceLineageTag: 5c5d4082-44f8-41fc-b89b-705f10c74b69
		dataCategory: Uncategorized

	measure 'Geselecteerde methode uitvoertijd onderhoud' = EXTERNALMEASURE("Geselecteerde methode uitvoertijd onderhoud", STRING, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: fff4335d-207a-40b5-9ba8-42010834c30d
		sourceLineageTag: 7f3763e9-ad31-409d-ab27-59062df76c17
		dataCategory: Uncategorized

	measure 'Ongeplande uren' = EXTERNALMEASURE("Ongeplande uren", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Planning
		lineageTag: fcd62f41-cab3-40cd-857d-49e78fecffab
		sourceLineageTag: 693b5299-50e0-42eb-b51a-d6604ff74141
		dataCategory: Uncategorized

	measure 'Periode afgesloten' = EXTERNALMEASURE("Periode afgesloten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 3832349c-2906-4f14-aa06-c092d77eaa42
		sourceLineageTag: 93d40d05-4439-49cb-a7ad-05ff9fdc2bee
		dataCategory: Uncategorized

	measure 'Periode Invoer afgesloten' = EXTERNALMEASURE("Periode Invoer afgesloten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Controle
		lineageTag: 6025ef28-37dc-479e-bdc2-ba37d91664d3
		sourceLineageTag: fd482bcc-e176-4a31-8252-5a55ad6156e6
		dataCategory: Uncategorized

	measure 'Periode Openstaand' = EXTERNALMEASURE("Periode Openstaand", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Overig
		lineageTag: 76bb4dc7-47cb-4579-abc5-51fb48717502
		sourceLineageTag: 3c2f8dde-533c-468a-8d12-ed91bd3e3d49
		dataCategory: Uncategorized

	measure 'Aantal aangemaakte calculaties' = EXTERNALMEASURE("Aantal aangemaakte calculaties", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 91825a4e-e1e2-4194-bc0d-eba25b0af26c
		sourceLineageTag: 7b4a097a-eb0b-4d8e-b647-2a40dd7a2095
		dataCategory: Uncategorized

	measure 'Aantal dagen offerte uitstaand' = EXTERNALMEASURE("Aantal dagen offerte uitstaand", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 45465069-6ed8-43b9-ae5e-26074daec91a
		sourceLineageTag: 53d23a43-493b-4b6b-9b56-c1f3c73313aa
		dataCategory: Uncategorized

	measure 'Aantal offertes uitstaand' = EXTERNALMEASURE("Aantal offertes uitstaand", INTEGER, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 08466b7e-e70d-4bc3-b1b1-0fca44cef3fa
		sourceLineageTag: 896e6bfd-20ff-4855-b591-15951e39990d
		dataCategory: Uncategorized

	measure 'Budget facturatie' = EXTERNALMEASURE("Budget facturatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess
		lineageTag: 732cfaa4-ae04-487f-8822-2f4605fb3bc3
		sourceLineageTag: 33f9ec29-27bc-4495-bc6f-4d4eeeec49d1
		dataCategory: Uncategorized

	measure 'Budget facturatie cumulatief' = EXTERNALMEASURE("Budget facturatie cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0.0;-"€"\ #,0.0;"€"\ #,0.0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Budget\Bron - Syntess
		lineageTag: 3a7c44ac-b9fd-4c7f-afec-e7890c265ed0
		sourceLineageTag: e92061a0-2d07-4f7f-9123-c05a4997b50d
		dataCategory: Uncategorized

	measure 'Calculatie aantal dagen uitstaand' = EXTERNALMEASURE("Calculatie aantal dagen uitstaand", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 1aa24e61-0565-4103-9a8a-5a6666f0a97b
		sourceLineageTag: 02d1088e-3e69-4c2b-ae00-a380b5d3c06b
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs tbv offertes' = EXTERNALMEASURE("Calculatie kostprijs tbv offertes", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 9dfe5ec1-e016-4249-9c91-00a22da84a7e
		sourceLineageTag: 5285ea61-16fc-4cb0-9117-a3c5a6dec7dd
		dataCategory: Uncategorized

	measure 'Calculatie project einddatum' = EXTERNALMEASURE("Calculatie project einddatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 3a2af45c-54ba-4a88-ad7a-9b6d15847b8d
		sourceLineageTag: 9e714ef8-13fc-4b99-9c16-1a5f4e442e90
		dataCategory: Uncategorized

	measure 'Calculatie project startdatum' = EXTERNALMEASURE("Calculatie project startdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 1c3e2129-9385-46ad-acaf-3a5700ada25e
		sourceLineageTag: 865fa39e-8567-4a9e-8901-1edaf802d845
		dataCategory: Uncategorized

	measure 'Calculatie uren montage tbv offertes' = EXTERNALMEASURE("Calculatie uren montage tbv offertes", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 0840bd6f-84df-4885-a15a-a78737af148d
		sourceLineageTag: d2eb5be1-594e-41e7-8a5f-9cb203da18ad
		dataCategory: Uncategorized

	measure 'Calculatie uren projectgebonden tbv offertes' = EXTERNALMEASURE("Calculatie uren projectgebonden tbv offertes", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 3cab5ea4-49f8-4f9c-bb31-647cbf26d991
		sourceLineageTag: eccb7251-52ab-4dd1-be1f-dc2c403acb77
		dataCategory: Uncategorized

	measure 'Conversie naar opdracht' = EXTERNALMEASURE("Conversie naar opdracht", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 7bf11fdd-be1f-41f6-885f-494cc96a3d94
		sourceLineageTag: 6961104f-88e4-46cc-861b-24c777c371c3
		dataCategory: Uncategorized

	measure Gefactureerd = EXTERNALMEASURE("Gefactureerd", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 1933e2c8-c263-49bb-915d-f7bc302e887d
		sourceLineageTag: 2c2ac529-e603-4423-bb5a-44548a6acce3
		dataCategory: Uncategorized

	measure 'Gefactureerd % budget per dag' = EXTERNALMEASURE("Gefactureerd % budget per dag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 51b443f4-c053-49de-8ac9-7563f60c3c7b
		sourceLineageTag: 54d46084-2a67-4eb2-b09c-762550e2cd6b
		dataCategory: Uncategorized

	measure 'Gefactureerd % tov vorig jaar' = EXTERNALMEASURE("Gefactureerd % tov vorig jaar", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 9136d83d-37b7-4089-a596-7d790bf02eb5
		sourceLineageTag: 1e845229-0f30-468d-8635-4ad34ab7325e
		dataCategory: Uncategorized

	measure 'Gefactureerd cumulatief' = EXTERNALMEASURE("Gefactureerd cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 5dc2f2ea-0a2c-4b23-84d4-7067542aca81
		sourceLineageTag: b68a02fd-5243-4403-9dff-3c1e818e568b
		dataCategory: Uncategorized

	measure 'Gefactureerd cumulatief vorig jaar' = EXTERNALMEASURE("Gefactureerd cumulatief vorig jaar", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: 698600a9-41be-409a-b1da-26310679f913
		sourceLineageTag: 0eb64dea-5ad3-4b0e-8836-761e204ccd66
		dataCategory: Uncategorized

	measure 'Gefactureerd vorig jaar' = EXTERNALMEASURE("Gefactureerd vorig jaar", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Actual\Exploitatie
		lineageTag: bb506ba0-2f70-4085-8244-0142affbb05a
		sourceLineageTag: fb8e813f-567c-4212-92ed-a72ba482983d
		dataCategory: Uncategorized

	measure 'Melding conversie naar opdracht' = EXTERNALMEASURE("Melding conversie naar opdracht", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: caad8db7-2cc1-478d-bd43-72d1a0a5c43e
		sourceLineageTag: 99e5cf14-592b-4f4d-8d6b-d9b0f3c17682
		dataCategory: Uncategorized

	measure 'Melding offerte met  aantal uitstaand' = EXTERNALMEASURE("Melding offerte met  aantal uitstaand", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: ab046f56-4327-4a38-8288-420aabc871a0
		sourceLineageTag: 5e145021-2ffd-41bb-beaf-7e5cfda2276a
		dataCategory: Uncategorized

	measure 'Offerte project einddatum' = EXTERNALMEASURE("Offerte project einddatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 1b928053-97d9-42f1-9e1b-e89a7fcc3734
		sourceLineageTag: 2e9f27b7-52c7-4a32-a126-ce0a50528b66
		dataCategory: Uncategorized

	measure 'Offerte project startdatum' = EXTERNALMEASURE("Offerte project startdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yy
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 6e81b9e9-9509-4f1b-8dcd-5923fd307cdf
		sourceLineageTag: 73868c90-42bc-472f-add0-ac60f38d886a
		dataCategory: Uncategorized

	measure Offertebedrag = EXTERNALMEASURE("Offertebedrag", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: d9dd01bb-12dc-4337-9985-958d1590d95c
		sourceLineageTag: 011f6a0d-18eb-4c99-b6f0-0721b45f933e
		dataCategory: Uncategorized

	measure 'Offertebedrag alleen met VC kostprijs' = EXTERNALMEASURE("Offertebedrag alleen met VC kostprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: b424c9cc-bcab-4e26-9d84-b5805aa76fb1
		sourceLineageTag: 13215818-280a-4cce-98d9-fbd44c74f611
		dataCategory: Uncategorized

	measure 'Offertebedrag uitstaand' = EXTERNALMEASURE("Offertebedrag uitstaand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 6a537e94-7820-4b66-857d-8b3405eed9b9
		sourceLineageTag: 945440f6-44a5-410f-9279-218c0961ea28
		dataCategory: Uncategorized

	measure 'Orderintake eenmalig' = EXTERNALMEASURE("Orderintake eenmalig", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 6497b495-87f3-47a2-b474-46c12ab28d72
		sourceLineageTag: e8dee0a8-8347-44e8-909b-a1a739697b32
		dataCategory: Uncategorized

	measure 'Orderintake service' = EXTERNALMEASURE("Orderintake service", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 637d7e4c-3c94-47d4-807c-babfacba50d4
		sourceLineageTag: d0119b3f-e031-42b1-8214-0f6958fefa59
		dataCategory: Uncategorized

	measure 'Scoringskans offertes' = EXTERNALMEASURE("Scoringskans offertes", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 3f46aa77-5c06-4584-a015-7406bb4e266f
		sourceLineageTag: 726a11bb-d437-4155-9344-ce4dd23bcec0
		dataCategory: Uncategorized

	measure 'Scoringskans uitstaande offertes' = EXTERNALMEASURE("Scoringskans uitstaande offertes", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: f50b3906-517b-4f8f-948b-4626661b7387
		sourceLineageTag: 9487fffa-8d5c-465c-a6c6-49f697af5db0
		dataCategory: Uncategorized

	measure 'Winst %' = EXTERNALMEASURE("Winst %", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 6c969026-e1c4-47f3-88eb-94a80398d158
		sourceLineageTag: 321c84f1-c389-427f-90c7-7b114a0021ac
		dataCategory: Uncategorized

	measure 'Winst alleen met VC kostprijs' = EXTERNALMEASURE("Winst alleen met VC kostprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: d6c0fdef-c9cf-4eee-bf62-bd6f584281ed
		sourceLineageTag: 208ce9e1-68ab-4bee-b6b7-896557347763
		dataCategory: Uncategorized

	measure 'Calculatie winst %' = EXTERNALMEASURE("Calculatie winst %", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 12a95be6-5657-4ffa-be61-228c3640dc79
		sourceLineageTag: 55c52e73-2820-4c7f-8447-0ae2cdba818a
		dataCategory: Uncategorized

	measure 'Calculatie winst' = EXTERNALMEASURE("Calculatie winst", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: d142b83e-7d6c-4040-bf59-628dfee7d780
		sourceLineageTag: 26f53c43-7af7-44bd-85f3-d14b4b018c98
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs' = EXTERNALMEASURE("Calculatie kostprijs", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: d096f674-e844-4ccc-9930-4a19b55af1f9
		sourceLineageTag: b0060ffe-c646-4b75-9af6-83566f1ddadc
		dataCategory: Uncategorized

	measure 'Aantal calculaties' = EXTERNALMEASURE("Aantal calculaties", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: ea1a5e4d-2e71-44d9-8ee1-da0a7e2e6ffa
		sourceLineageTag: 717a9e4c-5c67-45ab-a692-c9781d90ad12
		dataCategory: Uncategorized

	measure 'Aantal actuele projecten' = EXTERNALMEASURE("Aantal actuele projecten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 330a60b8-7cb2-41bb-80f5-2fc57db1a2d1
		sourceLineageTag: 28449bf6-a7e9-44fb-8078-806449eeb398
		dataCategory: Uncategorized

	measure 'Aantal historische projecten' = EXTERNALMEASURE("Aantal historische projecten", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectselectie
		lineageTag: 66751265-3172-4667-8376-29a3d30e5837
		sourceLineageTag: ff8f3724-0116-4bff-8a4f-989ece560510
		dataCategory: Uncategorized

	measure 'Aantal openstaande facturen met dispuut' = EXTERNALMEASURE("Aantal openstaande facturen met dispuut", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 67802d63-b81c-45c5-88d2-6cc8a95dc858
		sourceLineageTag: 7ddccab9-e1f1-40b8-b95c-e84c9b24db51
		dataCategory: Uncategorized

	measure 'Aantal uitstaande offertes' = EXTERNALMEASURE("Aantal uitstaande offertes", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 171f2a95-9336-4d92-907c-955df2b5fe21
		sourceLineageTag: 958c8367-d4b4-4f14-ab1d-234ca8612ef8
		dataCategory: Uncategorized

	measure 'Controle 1 relatie geselecteerd' = EXTERNALMEASURE("Controle 1 relatie geselecteerd", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 39ddd672-cad2-4ea4-a1d3-8ac42cb84870
		sourceLineageTag: 6540672e-8d6d-454a-a110-8018f31b6c07
		dataCategory: Uncategorized

	measure 'Directe omzet' = EXTERNALMEASURE("Directe omzet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: 746e4b64-ccff-41d7-ade7-e96494716bc6
		sourceLineageTag: ab1d2502-6b2b-4e24-9c70-799b9827442e
		dataCategory: Uncategorized

	measure 'Openstaande bedragen met dispuut' = EXTERNALMEASURE("Openstaande bedragen met dispuut", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.05 Commercieel
		lineageTag: da5ef0a5-e817-45f7-88a4-ca2d8656a479
		sourceLineageTag: e80e912c-b819-4ebf-a0c2-ce7c6af55d53
		dataCategory: Uncategorized

	measure 'Project van offerte' = EXTERNALMEASURE("Project van offerte", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.05 Best practice Commercieel
		lineageTag: 4bd99f70-71fe-4eb5-b27f-913818e4806a
		sourceLineageTag: 7b40ef0d-f987-45ee-8ff5-8eb94733d9d7
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTDLY (standaard)' = EXTERNALMEASURE("Indirecte kosten YTDLY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: c0e656fb-f954-4796-a1e5-d7ecf2a832d7
		sourceLineageTag: 89d2f3a2-793f-4ac0-a167-73c021b11f84
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTD (standaard)' = EXTERNALMEASURE("Indirecte kosten YTD (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: d0ca2f8f-3de1-4c5e-8d5d-358952300b9e
		sourceLineageTag: 6b614653-71c7-40e8-92cb-93a14c2301c1
		dataCategory: Uncategorized

	measure 'Indirecte kosten LY (standaard)' = EXTERNALMEASURE("Indirecte kosten LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 68333cc8-9d1a-44c3-b8d5-040332b5a4e1
		sourceLineageTag: 3f50033d-63cd-43d3-aec6-958ff2136f3f
		dataCategory: Uncategorized

	measure 'Indirecte kosten neg (standaard)' = EXTERNALMEASURE("Indirecte kosten neg (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: f198e0dc-60be-4c72-b0a8-d1a84498c5b1
		sourceLineageTag: 9fab3ad5-8048-4663-8840-707d4a0ee6dd
		dataCategory: Uncategorized

	measure 'Indirecte kosten (standaard)' = EXTERNALMEASURE("Indirecte kosten (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 3c3ebfda-27f0-4dc4-acf1-a6c658ec3f4f
		sourceLineageTag: d3047ab3-6228-448a-902e-d847f40d8cb2
		dataCategory: Uncategorized

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY (standaard)' = EXTERNALMEASURE("Directe kosten YTDLY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 0794ac67-e1ed-4892-9605-22aeef293153
		sourceLineageTag: 361c4d82-75ef-4d0e-aa32-2c0fd3bcb348
		dataCategory: Uncategorized

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD (standaard)' = EXTERNALMEASURE("Directe kosten YTD (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: eed39c33-f67e-48f3-9367-4a2ccf4d6f51
		sourceLineageTag: a037e0b6-44ee-4198-b1cc-dccc696d2911
		dataCategory: Uncategorized

	measure 'Directe kosten neg (standaard)' = EXTERNALMEASURE("Directe kosten neg (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		isHidden
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 3d6b08bf-6622-4944-a297-3ce0e236695f
		sourceLineageTag: 8f97fa19-af6c-4980-8f2b-c0586d3bad08
		dataCategory: Uncategorized

	/// Zie [Directe kosten]. Betreft directe kosten over dezelfde periode vorig jaar.
	measure 'Directe kosten LY (standaard)' = EXTERNALMEASURE("Directe kosten LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: efee450a-6586-4e4c-b5df-ec0f9b4ec2a2
		sourceLineageTag: d20112c0-1ea1-4f77-9a06-5dc04360971d
		dataCategory: Uncategorized

	/// [Debet]-[Credit] op exploitatie rubrieken die niet de toepassing "omzetrekening" hebben. Betreft niet de projectjournalisering boekingen (alleen boxnummer 1 boekingen). Alleen de journaalregels die aan een project zijn gekoppeld. 
	measure 'Directe kosten (standaard)' = EXTERNALMEASURE("Directe kosten (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 9af305c5-8d13-49de-a005-d0e376094811
		sourceLineageTag: 86124413-7b86-465f-97ed-9a34b3b3877a
		dataCategory: Uncategorized

	measure 'Directe kosten LY (benchmark schema)' = EXTERNALMEASURE("Directe kosten LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 2ae3c87c-2ae4-45dc-8b90-0121f547be17
		sourceLineageTag: 9355c70b-7991-4dfe-b192-8a044cdc1eb5
		dataCategory: Uncategorized

	measure 'Directe kosten (benchmark schema)' = EXTERNALMEASURE("Directe kosten (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: b9df4dc1-71da-42f9-8bf0-dfbec2111240
		sourceLineageTag: 93432e8d-7fb8-478d-bd50-e92f7724b77d
		dataCategory: Uncategorized

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD (benchmark schema)' = EXTERNALMEASURE("Directe kosten YTD (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 3c2eb9de-7e11-4349-a6a9-16fbcb40df1c
		sourceLineageTag: f8982951-e5ad-4585-ba8c-272eb9a51a5e
		dataCategory: Uncategorized

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY (benchmark schema)' = EXTERNALMEASURE("Directe kosten YTDLY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: c9406930-5aef-4b27-abfc-5a4f571e6b9a
		sourceLineageTag: 78dc6f10-ff74-4535-b228-29f10289383f
		dataCategory: Uncategorized

	measure 'Indirecte kosten (benchmark schema)' = EXTERNALMEASURE("Indirecte kosten (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: f7941c1a-dbb6-4ef0-82b9-58a265771874
		sourceLineageTag: d005394a-413f-4b8d-9fab-a318ce0dac2c
		dataCategory: Uncategorized

	measure 'Indirecte kosten LY (benchmark schema)' = EXTERNALMEASURE("Indirecte kosten LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 224b9f53-b39c-4516-a5b9-49728a239776
		sourceLineageTag: 8eab2471-9f10-455e-87dc-b47426f4b3c3
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTD (benchmark schema)' = EXTERNALMEASURE("Indirecte kosten YTD (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: c4a4200d-eee1-4d3b-b5da-c1000a73e2e3
		sourceLineageTag: 54e8e83e-f3f2-45bc-9efd-437c726fc60c
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTDLY (benchmark schema)' = EXTERNALMEASURE("Indirecte kosten YTDLY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: bcccee24-5972-401b-91ff-92c5b75e2e64
		sourceLineageTag: d9aae81b-eb36-4141-bf33-62fcc27bd69d
		dataCategory: Uncategorized

	measure 'Omzet YTDLY (benchmark schema)' = EXTERNALMEASURE("Omzet YTDLY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: caf7bbc4-a8a4-41ec-9b0a-949eb7b225ce
		sourceLineageTag: 5979076d-8ec4-4fbb-9206-57973757b700
		dataCategory: Uncategorized

	measure 'Omzet YTD (benchmark schema)' = EXTERNALMEASURE("Omzet YTD (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 344317ac-5946-432e-95b6-0f862602cbfa
		sourceLineageTag: f2b4fe00-adbb-474b-9c40-c5ed61e90775
		dataCategory: Uncategorized

	measure 'Omzet LY (benchmark schema)' = EXTERNALMEASURE("Omzet LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: dc6f18ea-d792-4c3e-be3c-6ddf13c16077
		sourceLineageTag: b9fdb52c-7c5b-402d-9640-88fc5089cac8
		dataCategory: Uncategorized

	measure 'Omzet 12 maanden (benchmark schema)' = EXTERNALMEASURE("Omzet 12 maanden (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 45a369a7-6b16-459c-b8f9-3c17e52454a6
		sourceLineageTag: 7684150f-8156-4d12-8c07-163bc8d3c700
		dataCategory: Uncategorized

	measure 'Omzet (benchmark schema)' = EXTERNALMEASURE("Omzet (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 1f56b6ac-184c-428c-b045-19d6d2271991
		sourceLineageTag: 2ccf104a-6344-4de8-ab27-9a3633c425fb
		dataCategory: Uncategorized

	measure 'Nettowinst YTDLY (benchmark schema)' = EXTERNALMEASURE("Nettowinst YTDLY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 54a13bd7-cda7-4cbf-ae93-8bc74f868767
		sourceLineageTag: c9458471-5b78-4d7c-8ed3-d01cdae0f909
		dataCategory: Uncategorized

	measure 'Nettowinst YTD (benchmark schema)' = EXTERNALMEASURE("Nettowinst YTD (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: fe56f68d-a764-42fe-b6d7-31d490de64cd
		sourceLineageTag: 0b686bd2-b9f6-4d47-88bc-9a67fa9fca61
		dataCategory: Uncategorized

	measure 'Nettowinst LY (benchmark schema)' = EXTERNALMEASURE("Nettowinst LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: cd016ccc-8e73-42d5-9d1d-dd6e2314d93f
		sourceLineageTag: 5a1d1ef3-2787-4a0f-a890-ea0e38aa13b3
		dataCategory: Uncategorized

	measure 'nettowinst 12 maanden (benchmark schema)' = EXTERNALMEASURE("nettowinst 12 maanden (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: e148e5db-6634-4b20-8ace-95271c7c754d
		sourceLineageTag: 4bac5f88-7b2b-4a23-b1e8-83046c428b81
		dataCategory: Uncategorized

	measure 'Nettowinst (benchmark schema)' = EXTERNALMEASURE("Nettowinst (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: e3bef2f4-dafb-43d8-a530-bbf63ea3734d
		sourceLineageTag: 72d00c65-4b4b-4667-8b26-61b2bab89a05
		dataCategory: Uncategorized

	measure 'Netto rendement YTD LY (benchmark schema)' = EXTERNALMEASURE("Netto rendement YTD LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 7fdb1765-9826-4ebd-84f2-32c935faeb1e
		sourceLineageTag: e70624c6-982f-400c-9f75-7bbbb4b59dc4
		dataCategory: Uncategorized

	measure 'Netto rendement YTD (benchmark schema)' = EXTERNALMEASURE("Netto rendement YTD (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: db2716c1-33fa-43ea-a33c-8d604c78d371
		sourceLineageTag: fa68429d-70e3-47e8-8f52-201d6c020ba4
		dataCategory: Uncategorized

	measure 'Netto rendement LY (benchmark schema)' = EXTERNALMEASURE("Netto rendement LY (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 39fe7735-02aa-472f-86fa-e9f38118b792
		sourceLineageTag: 6c55861f-89b4-4ac8-9abd-b689dd262e6d
		dataCategory: Uncategorized

	measure 'Netto rendement 12 maanden (benchmark schema)' = EXTERNALMEASURE("Netto rendement 12 maanden (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 933a2b0b-ed96-4c07-935f-07dfb5ebc0a3
		sourceLineageTag: 736e5fdb-4965-4d9c-8f39-a4e4afe3c5e1
		dataCategory: Uncategorized

	measure 'Netto rendement (benchmark schema)' = EXTERNALMEASURE("Netto rendement (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 67661fe5-2aaa-437b-b934-a69d4d8eef90
		sourceLineageTag: eb00ed1f-24d2-470d-8faa-07b5084914dd
		dataCategory: Uncategorized

	measure 'Nettowinst YTDLY (standaard)' = EXTERNALMEASURE("Nettowinst YTDLY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: f7d76b7c-7f15-40b0-a887-144d877c8cd1
		sourceLineageTag: f834c166-b406-4ff6-aa9c-27f6f473d1f5
		dataCategory: Uncategorized

	measure 'Nettowinst YTD (standaard)' = EXTERNALMEASURE("Nettowinst YTD (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: cc16ecd4-674c-4764-bd59-a45f9dcd1ce2
		sourceLineageTag: 32ab8070-1201-44d0-9b9b-f7f0dc08290c
		dataCategory: Uncategorized

	measure 'Nettowinst LY (standaard)' = EXTERNALMEASURE("Nettowinst LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 6b8c09fe-a351-41a6-88a9-e7d6b421f98e
		sourceLineageTag: b5cb0beb-aaab-4949-b566-909b262a8597
		dataCategory: Uncategorized

	measure 'nettowinst 12 maanden (standaard)' = EXTERNALMEASURE("nettowinst 12 maanden (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: d17d5ff0-d0df-497d-a0e8-5de957708488
		sourceLineageTag: 77bcbadf-bc34-446d-a55c-4dac4ac879bb
		dataCategory: Uncategorized

	measure 'Nettowinst (standaard)' = EXTERNALMEASURE("Nettowinst (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: bcdd442e-7cdd-4ef9-93fb-d8ad8457a55a
		sourceLineageTag: 80eae096-8f3d-49fd-8f54-60fc553aad30
		dataCategory: Uncategorized

	measure 'Netto rendement YTD LY (standaard)' = EXTERNALMEASURE("Netto rendement YTD LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 1c42707c-0177-43fc-b190-c3b9655d1c71
		sourceLineageTag: e425f857-2ed6-48e7-96a9-c6bf89e1cae8
		dataCategory: Uncategorized

	measure 'Netto rendement YTD (standaard)' = EXTERNALMEASURE("Netto rendement YTD (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: b47be76c-912c-4163-a565-61ffce28733a
		sourceLineageTag: 505d0bab-3f87-4b76-a7cc-45a2768c9c9a
		dataCategory: Uncategorized

	measure 'Netto rendement LY (standaard)' = EXTERNALMEASURE("Netto rendement LY (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 608f3fdc-e1f8-40d6-a1d2-4ed306360d33
		sourceLineageTag: 086da001-c9e4-4228-a351-738e9c8c0bc6
		dataCategory: Uncategorized

	measure 'Netto rendement 12 maanden (standaard)' = EXTERNALMEASURE("Netto rendement 12 maanden (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 32455bda-26e3-474c-be8b-7a07a4803977
		sourceLineageTag: 8a523ad7-5c65-463c-b8ff-d58bea24016b
		dataCategory: Uncategorized

	measure 'Netto rendement (standaard)' = EXTERNALMEASURE("Netto rendement (standaard)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (standaard)
		lineageTag: 07eb0ff0-a3e9-4833-95af-7d770f69db35
		sourceLineageTag: 9a45ce6b-5939-4f05-aa3f-bb0a5d42af81
		dataCategory: Uncategorized

	measure 'Directe kosten neg (benchmark schema)' = EXTERNALMEASURE("Directe kosten neg (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: 6522c05e-9b9c-45c6-954a-0bce463dae7b
		sourceLineageTag: a936a5b5-69cf-4c3e-bff6-e0cc0de9f232
		dataCategory: Uncategorized

	measure 'Indirecte kosten neg (benchmark schema)' = EXTERNALMEASURE("Indirecte kosten neg (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Resultaat (benchmark schema)
		lineageTag: a6c8ab32-2a07-43d3-b711-4a52bbf0a349
		sourceLineageTag: e69b442a-f458-43f6-8f00-c27bea92ae6d
		dataCategory: Uncategorized

	measure Omzet = EXTERNALMEASURE("Omzet", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 2037561e-10f7-4068-b5cf-dd967cfc8598
		sourceLineageTag: e746558f-659c-49b5-8e6c-9e35dcab6a5e
		dataCategory: Uncategorized

	/// Resultaat (credit - debet) van het geboekte werkresultaat in de exploitatierekening. Werkresultaat is het definitieve resultaat bij vrijval van een project. 
	measure Werkresultaat = EXTERNALMEASURE("Werkresultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 08adaffe-c712-48fd-9825-e7e846680b0e
		sourceLineageTag: 74d9c2e8-3e2b-4b3d-a8ad-69d8e77c16fe
		dataCategory: Uncategorized

	/// Resultaat (credit - debet) van de geboekte projectwaarderingen in de exploitatierekening. Projectwaardering tonen de tussentijdse respresentatie van het verwachte resultaat. 
	measure Waarderingen = EXTERNALMEASURE("Waarderingen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 916fe425-c942-4e1c-a766-027d1ded2142
		sourceLineageTag: 2c1b37d3-4997-4ea6-bbf4-736094865145
		dataCategory: Uncategorized

	/// Verschil tussen 2 manieren van de dekkingen bepaling. Moet altijd €0 zijn.
	measure 'Verschil dekking berekeningen' = EXTERNALMEASURE("Verschil dekking berekeningen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Projectjournalisering zonder projectrelatie\Enterprise
		lineageTag: b3c47098-93a7-430e-97a9-68b701228d33
		sourceLineageTag: 90d32aad-bcf5-49b8-8398-848aaeaf05a2
		dataCategory: Uncategorized

	/// [Projectwaarderingen resultaat]+[Resultaat tegenboeken projectwaarderingen]+[Werkresultaat]
	measure 'Totaal projectwaardering + werkresultaat' = EXTERNALMEASURE("Totaal projectwaardering + werkresultaat", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 520c8bfa-ea31-49da-b66e-d81883dcc137
		sourceLineageTag: 106dd921-04ca-4d7a-a02e-44ac63f8eac6
		dataCategory: Uncategorized

	measure 'Projectkosten incl dekkingen op projecten' = EXTERNALMEASURE("Projectkosten incl dekkingen op projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 541eaa40-517b-4948-a229-ba4ad46114e9
		sourceLineageTag: 2d8ce65d-1d67-49d0-b823-5b3c0218bd5f
		dataCategory: Uncategorized

	/// [OHW mutatie in balans]+[Werkresultaat]
	measure 'Netto resultaat via OHW' = EXTERNALMEASURE("Netto resultaat via OHW", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 2916b973-4916-461d-83c2-bd1ec430fc9b
		sourceLineageTag: e10bf45c-f753-47ec-bc66-026d6d148067
		dataCategory: Uncategorized

	/// [OHW mutatie in exploitatie]+[Dekkingen op projecten]
	measure 'Netto resultaat via exploitatie' = EXTERNALMEASURE("Netto resultaat via exploitatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: 54c2b50f-5ca9-4db0-9667-e1c8bb4f764c
		sourceLineageTag: 716405da-5bca-4ffc-8012-7e29f0bb9976
		dataCategory: Uncategorized

	/// [OHW mutatie in exploitatie]-[OHW mutatie in balans]-[Werkresultaat]. Betreft een berekende waarde t.b.v. bepaling dekking op projectniveau.
	measure 'Dekkingen op projecten (berekend)' = EXTERNALMEASURE("Dekkingen op projecten (berekend)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Projectjournalisering
		lineageTag: e474312a-9737-4978-9718-71f1f705a80b
		sourceLineageTag: 425d069e-761a-4e58-9115-edf4ecedc960
		dataCategory: Uncategorized

	measure 'Omzet CoA' = EXTERNALMEASURE("Omzet CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: de1c3013-46d2-4387-9aec-e8da9924e877
		sourceLineageTag: fa1ed9dd-4401-4a82-897a-da4be38cf803
		dataCategory: Uncategorized

	measure 'Omloopsnelheid debiteuren per maand' = EXTERNALMEASURE("Omloopsnelheid debiteuren per maand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: 2b9d290d-de33-41e6-a09d-50aa4e2016b4
		sourceLineageTag: 5972ae7d-3fc7-4a96-acfb-3253f7c36665
		dataCategory: Uncategorized

	measure 'Omloopsnelheid debiteuren per jaar' = EXTERNALMEASURE("Omloopsnelheid debiteuren per jaar", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: e439589c-51bf-481d-85a2-15b896a8538d
		sourceLineageTag: 8df0fcda-5200-46c2-b6a0-adeb4990ae02
		dataCategory: Uncategorized

	measure 'Omloopsnelheid crediteuren per maand' = EXTERNALMEASURE("Omloopsnelheid crediteuren per maand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: c48e41dc-24b9-47d4-8387-9da6707f1476
		sourceLineageTag: 7ad28e8b-9cde-4062-8d78-6784d7e1e7eb
		dataCategory: Uncategorized

	measure 'Omloopsnelheid crediteuren per jaar' = EXTERNALMEASURE("Omloopsnelheid crediteuren per jaar", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0.0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: cb94eae0-f733-4bf9-aa30-c408d80bc02b
		sourceLineageTag: d4aeaf0f-03a4-41a1-95a8-3f35b1f5cfe1
		dataCategory: Uncategorized

	measure 'Gemiddeld debiteuren saldo' = EXTERNALMEASURE("Gemiddeld debiteuren saldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: 97d1cc4a-4ecf-429c-869d-77b6160ba096
		sourceLineageTag: 7ed9b12a-05e4-479f-8c9d-760ebd79e485
		dataCategory: Uncategorized

	measure 'Gemiddeld crediteuren saldo' = EXTERNALMEASURE("Gemiddeld crediteuren saldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: d4cc7355-7cca-4dc6-ac37-f339c0a11fc5
		sourceLineageTag: b72c0937-c89a-4fc3-a87b-0219dab12c61
		dataCategory: Uncategorized

	measure 'Debiteurensaldo einde periode' = EXTERNALMEASURE("Debiteurensaldo einde periode", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: 6ebc29ee-3d24-4331-a92d-bf884389c06e
		sourceLineageTag: 8379fc7a-abcd-4f7b-92f4-a1c7c7626a70
		dataCategory: Uncategorized

	measure 'Debiteurensaldo begin periode' = EXTERNALMEASURE("Debiteurensaldo begin periode", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: 569b49c0-b848-4472-a112-a6c71e4f2261
		sourceLineageTag: a694102c-66fa-455a-a1ba-75f6ce088f2d
		dataCategory: Uncategorized

	measure 'Crediteurensaldo einde periode' = EXTERNALMEASURE("Crediteurensaldo einde periode", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: d551bb38-855f-4cf8-85cc-f1ee72c4aa07
		sourceLineageTag: d61c2640-b502-46f3-bb13-dc9ff4e68ba2
		dataCategory: Uncategorized

	measure 'Crediteurensaldo begin periode' = EXTERNALMEASURE("Crediteurensaldo begin periode", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: 369d1464-6c1e-4338-be4b-b5e7384d78c0
		sourceLineageTag: 8846405f-a205-45ab-85cf-f4a1c26e5985
		dataCategory: Uncategorized

	measure 'Bedrijfskosten CoA' = EXTERNALMEASURE("Bedrijfskosten CoA", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\KPI
		lineageTag: cc69ebf8-c86e-4bfe-9a5d-ce3f0f3474b1
		sourceLineageTag: aabe411f-9558-4e05-ae0c-b2a8277154be
		dataCategory: Uncategorized

	measure 'Directe kosten' = EXTERNALMEASURE("Directe kosten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Resultaat in onderdelen\Samengevoegd
		lineageTag: 2bebb135-2dd2-41fe-a4d9-8261917a7232
		sourceLineageTag: e3b45a34-338d-49dd-9a02-4513297f0687
		dataCategory: Uncategorized

	measure 'Montage uren TW' = EXTERNALMEASURE("Montage uren TW", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 6c5bee7d-03af-4f87-a423-7f056495c043
		sourceLineageTag: ab055866-ec6f-455f-b7a1-ef2f47410c8c
		dataCategory: Uncategorized

	measure 'Montage uren via inkoopfacturen' = EXTERNALMEASURE("Montage uren via inkoopfacturen", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: df32a70a-5806-47b4-a184-d0587cf0e665
		sourceLineageTag: 1abc6586-b55f-462a-b4e2-064e9ccee891
		dataCategory: Uncategorized

	measure 'montage uren via urenstaten TW' = EXTERNALMEASURE("montage uren via urenstaten TW", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: 386654c7-a639-4433-83d6-26efc2a1bca5
		sourceLineageTag: d7163629-3b48-4aae-9700-f84001274ec0
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op realisatie per uur (TWR\u)' = EXTERNALMEASURE("Toegevoegde Waarde op realisatie per uur (TWR\u)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: """"\€""""\ #,0;-""""\€""""\ #,0;""""\€""""\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde
		lineageTag: b8df62e1-a523-48af-8b99-c01f976ac4f9
		sourceLineageTag: 0b95d464-aaa1-4f16-a733-1084337e47cc
		dataCategory: Uncategorized

	measure 'Toegevoegde Waarde op Realisatie (TWR, zonder datumfilter)' = EXTERNALMEASURE("Toegevoegde Waarde op Realisatie (TWR, zonder datumfilter)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Toegevoegde waarde\Zonder datumfilter
		lineageTag: 053dc9d4-3676-4a09-9cb7-318f8bfb8de9
		sourceLineageTag: d3440a6d-e3d0-42db-9d7c-b6d3089c8e56
		dataCategory: Uncategorized

	measure 'Melding bankrubrieken dubbel gekoppeld' = EXTERNALMEASURE("Melding bankrubrieken dubbel gekoppeld", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 962bf50b-fd2d-411c-80d6-05aeb337b6da
		sourceLineageTag: 0642dc2c-f2cc-4fd1-99fd-3613b141bd17
		dataCategory: Uncategorized

	measure 'Melding Geen openstaande bankafschriften' = EXTERNALMEASURE("Melding Geen openstaande bankafschriften", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: bd8516bb-7863-4b6b-beec-c5ba5b029a90
		sourceLineageTag: 2e2576fd-b1fe-4370-9566-ff28ad4d59a2
		dataCategory: Uncategorized

	measure 'Melding geselecteerde CF categorie' = EXTERNALMEASURE("Melding geselecteerde CF categorie", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Meldingen
		lineageTag: 7688e518-9c96-45ff-bee3-a004f07cc668
		sourceLineageTag: eb00a25b-3bc7-4812-bacc-5663a31f1288
		dataCategory: Uncategorized

	measure 'Bank incl. openstaande bankregels' = EXTERNALMEASURE("Bank incl. openstaande bankregels", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank\New folder
		lineageTag: 619409d6-6f0c-410b-ab8d-e7fc42507491
		sourceLineageTag: c94027d6-e4b3-4442-adbf-1b993c144af0
		dataCategory: Uncategorized

	measure 'Bank eindsaldo incl. openstaande bankregels' = EXTERNALMEASURE("Bank eindsaldo incl. openstaande bankregels", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank\New folder
		lineageTag: 40e43c92-4cb8-4325-88c7-b2ae58d6d5ac
		sourceLineageTag: 2f53b5b2-d090-428e-8723-e4a75a700506
		dataCategory: Uncategorized

	measure 'Bank beginsaldo incl. openstaande bankregels' = EXTERNALMEASURE("Bank beginsaldo incl. openstaande bankregels", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.01 Financieel\Hoofdadministratie\Cash flow\Bank\New folder
		lineageTag: a0302b82-284d-4da6-ac6d-45f59c1cf50d
		sourceLineageTag: 6cacd62f-1693-458f-80f6-1c27858e4827
		dataCategory: Uncategorized

	measure 'Nog te verwachten kosten via werkbon inkoop' = EXTERNALMEASURE("Nog te verwachten kosten via werkbon inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.04 Service\Werkbonparagrafen
		lineageTag: a2d8e22b-1257-4247-afa7-3fe1dfba5b8a
		sourceLineageTag: 88197247-cedd-4e2c-8161-bcb6f31c3e0f
		dataCategory: Uncategorized

	measure 'Budget resultaat (Projectbeheer)' = EXTERNALMEASURE("Budget resultaat (Projectbeheer)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: 386b38f6-2d7b-4dff-b278-e81bf0049abb
		sourceLineageTag: d538142e-8b04-4b50-9d9b-b6a1d6923cb3
		dataCategory: Uncategorized

	/// Basis: Orderbedrag. Indien specifiek geselecteerd;calculatie verkoopprijs
	measure 'budget omzet (Projectbeheer)' = EXTERNALMEASURE("budget omzet (Projectbeheer)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: 57a41e58-eaaa-4d88-93ed-b92175230898
		sourceLineageTag: e57beb7e-8e5b-480e-9633-15bb6d96d5be
		dataCategory: Uncategorized

	/// (Budget omzet - budgetkosten) /budgetomzet
	measure 'Budget marge (Projectbeheer)' = EXTERNALMEASURE("Budget marge (Projectbeheer)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Budget
		lineageTag: cf384aae-a7c8-4696-b1a5-6107335ef6ad
		sourceLineageTag: 43ac9467-4dda-41d5-bad4-a42be5d6a5cc
		dataCategory: Uncategorized

	measure 'Gerealiseerde rendement (Projectbeheer)' = EXTERNALMEASURE("Gerealiseerde rendement (Projectbeheer)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 6c7bde6d-1edc-45c4-960a-40fac4eb43c3
		sourceLineageTag: 514f6c98-c3ee-4acf-ae4e-bc6135a6d3f3
		dataCategory: Uncategorized

	measure 'Resultaat (Projectbeheer)' = EXTERNALMEASURE("Resultaat (Projectbeheer)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Ratios
		lineageTag: 5a32451b-c34f-4c27-a424-32b04983b78d
		sourceLineageTag: ea6d6039-0dd1-4fa0-92d0-ecf879a35a30
		dataCategory: Uncategorized

	measure AdministratieKey = EXTERNALMEASURE("AdministratieKey", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectselectie\1. Naar PowerApp
		lineageTag: e075e469-dbbd-48b0-9039-f219e853f276
		sourceLineageTag: 51f40a89-95c5-40b4-b72e-cee5955f578b
		dataCategory: Uncategorized

	measure 'Mutatie actual CoCFC' = EXTERNALMEASURE("Mutatie actual CoCFC", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: cdc0c8fc-452e-4a18-b655-6dbda4db4f04
		sourceLineageTag: 4783e3e4-490b-4a21-87bf-1f18ee2ee4b6
		dataCategory: Uncategorized

	measure 'Mutatie actual en forecast CoCFC' = EXTERNALMEASURE("Mutatie actual en forecast CoCFC", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 10b754e1-08ae-4ed8-9cc3-47f498297d7c
		sourceLineageTag: 7e000df5-906a-40dc-a51d-e74c4e873bc6
		dataCategory: Uncategorized

	measure 'Subtotaal codering mutatie actual CoCFC' = EXTERNALMEASURE("Subtotaal codering mutatie actual CoCFC", INTEGER, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 787df97e-954e-43c4-aac5-299b68ac9fa6
		sourceLineageTag: d8f881a6-9d5c-44d4-b147-b606e626db68
		dataCategory: Uncategorized

	measure 'Subtotaal codering mutatie actual en forecast CoCFC' = EXTERNALMEASURE("Subtotaal codering mutatie actual en forecast CoCFC", INTEGER, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 00a44bb7-f696-4264-9be5-b89c8665e406
		sourceLineageTag: fd55c735-7aef-439f-9413-9e74328b6e08
		dataCategory: Uncategorized

	measure 'Actual beginsaldo' = EXTERNALMEASURE("Actual beginsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 8c149841-aa69-4ad3-a3b8-2ddbe6cca78e
		sourceLineageTag: 073c889e-4a67-40b2-8b5a-0cc9070e5266
		dataCategory: Uncategorized

	measure 'Actual eindsaldo' = EXTERNALMEASURE("Actual eindsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 62dbecc8-c931-4f39-a350-cf0410a573a3
		sourceLineageTag: eb6590d3-131b-45c9-b2a4-a653e5ff69b5
		dataCategory: Uncategorized

	measure 'Forecast beginsaldo' = EXTERNALMEASURE("Forecast beginsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 7bbcf159-176d-49eb-a497-17e13c2fdd8a
		sourceLineageTag: 7defd28c-2d3d-4fba-9080-47cbc5f86ea6
		dataCategory: Uncategorized

	measure 'Forecast eindsaldo' = EXTERNALMEASURE("Forecast eindsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: e0d4604b-cc64-4969-9560-6c4c1a985016
		sourceLineageTag: 7e9d919e-50cb-4ea5-b8dd-83c7ef63f427
		dataCategory: Uncategorized

	measure 'Actual en forecast beginsaldo' = EXTERNALMEASURE("Actual en forecast beginsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 6543075e-d3df-409b-a3a2-be77ee6f8673
		sourceLineageTag: aafad719-cc31-4a79-998b-fab6ea07eb61
		dataCategory: Uncategorized

	measure 'Actual en forecast eindsaldo' = EXTERNALMEASURE("Actual en forecast eindsaldo", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 13f45d07-83a9-44ee-9785-958f8161cd3d
		sourceLineageTag: 6337d49c-00a3-4638-9869-a649c8d72bbb
		dataCategory: Uncategorized

	measure 'Actual mutatie' = EXTERNALMEASURE("Actual mutatie", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 96a169e8-fdd8-4c77-9da8-572bc159e787
		sourceLineageTag: 42c6b970-90f1-41b3-8ff7-fed2fc17174a
		dataCategory: Uncategorized

	measure 'Actual mutatie tot en met standdatum' = EXTERNALMEASURE("Actual mutatie tot en met standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 5e0a8412-3ee8-42b8-b3af-4cf47fee6046
		sourceLineageTag: 23c5185e-e2f7-461e-b6be-d55046bfaa18
		dataCategory: Uncategorized

	measure 'Forecast mutatie cashflow' = EXTERNALMEASURE("Forecast mutatie cashflow", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 401ea469-5405-4e1f-b299-7186955968b8
		sourceLineageTag: d0ea5362-5277-4058-851a-d78215281175
		dataCategory: Uncategorized

	measure 'Forecast mutatie vanaf standdatum' = EXTERNALMEASURE("Forecast mutatie vanaf standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 158f7985-3bfd-4abb-b7a9-15c2d9d9418e
		sourceLineageTag: 25d47916-2c01-431c-adcd-0b41aa5e0a9a
		dataCategory: Uncategorized

	measure 'laatste standdatum' = EXTERNALMEASURE("laatste standdatum", DATETIME, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: 4059e791-3675-438f-af8d-9d3e4672d543
		sourceLineageTag: 608048ef-6bab-4b89-aa53-ae1ecbe25f0e
		dataCategory: Uncategorized

	measure 'Codering voor achtergrond' = EXTERNALMEASURE("Codering voor achtergrond", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Cashflow forecast
		lineageTag: e0f1185b-e324-4ee4-a34b-290c319e6ee8
		sourceLineageTag: 734034d3-3f79-41b7-a573-d710d73b8f24
		dataCategory: Uncategorized

	measure 'Geselecteerde standdatum projecten' = EXTERNALMEASURE("Geselecteerde standdatum projecten", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen
		lineageTag: 5c83c3dc-c7da-4d5b-86db-3a1ca6a7bd32
		sourceLineageTag: 674ec8d3-f645-4227-a480-fbf67ba2a24a
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs (t/m standdatum)' = EXTERNALMEASURE("Definitieve kostprijs (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 729c0760-a34e-45b7-a7db-40337af8ce49
		sourceLineageTag: 2830898d-e7bb-4ecc-9e19-82abf7f86b2c
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs regie (t/m standdatum)' = EXTERNALMEASURE("Definitieve kostprijs regie (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 5c57f87e-a246-4f3e-9215-d8a3499527fe
		sourceLineageTag: b049b20e-b085-4139-b0d3-1caab40dfc8f
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs vaste prijs (t/m standdatum)' = EXTERNALMEASURE("Definitieve kostprijs vaste prijs (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 254bfa14-60ba-480c-8ce1-6e33b2cf1dad
		sourceLineageTag: 220b6227-5314-43f4-bb2f-d15c4231bda9
		dataCategory: Uncategorized

	measure 'Historische omzet (t/m standdatum)' = EXTERNALMEASURE("Historische omzet (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 928645a2-9ca8-4f63-8a30-2fea28a34ef2
		sourceLineageTag: e65789ac-88af-42bf-8dc6-06d334fe0789
		dataCategory: Uncategorized

	measure 'Historische omzet order (t/m standdatum)' = EXTERNALMEASURE("Historische omzet order (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 671e5524-6359-4e29-b993-79d986828054
		sourceLineageTag: 5bcc8f93-dc36-4511-bb88-7a184148c53b
		dataCategory: Uncategorized

	measure 'Historische omzet regie (t/m standdatum)' = EXTERNALMEASURE("Historische omzet regie (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: f3c19c19-3b98-47c2-b25d-230b07fdc3ce
		sourceLineageTag: 066f1959-15f0-4c01-93ae-47e1aa5e548e
		dataCategory: Uncategorized

	measure 'Projectjournalisering kosten (t/m standdatum)' = EXTERNALMEASURE("Projectjournalisering kosten (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 7742deb3-dccb-4842-a332-ad9122931e11
		sourceLineageTag: 28746807-ea13-4c43-b95f-1cdf05654850
		dataCategory: Uncategorized

	measure 'Projectjournalisering opbrengsten (t/m standdatum)' = EXTERNALMEASURE("Projectjournalisering opbrengsten (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: f98507a9-7431-49f7-b2df-cb45b7be3831
		sourceLineageTag: 9ce45120-50bd-4b1a-a3ce-52814f57a212
		dataCategory: Uncategorized

	measure 'Projectjournalisering projectwaarderingen (t/m standdatum)' = EXTERNALMEASURE("Projectjournalisering projectwaarderingen (t/m standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectwaardering
		lineageTag: 49df5309-74e8-40b7-b488-da76044d0720
		sourceLineageTag: 1f458a3e-75b5-4b8b-a83d-0dc68be1b9b3
		dataCategory: Uncategorized

	measure 'Melding projectstand Professional' = EXTERNALMEASURE("Melding projectstand Professional", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen
		lineageTag: 37a378fb-bb64-4867-b80a-8f57921da0e7
		sourceLineageTag: b7045316-cf44-48d7-8116-600de8901838
		dataCategory: Uncategorized

	measure 'Melding projectstand Enterprise' = EXTERNALMEASURE("Melding projectstand Enterprise", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen
		lineageTag: b1341807-8ceb-4055-8eea-b549a9c86978
		sourceLineageTag: b6085cfb-ec07-4b91-a2b8-5e355c08e160
		dataCategory: Uncategorized

	measure 'Melding projectstand' = EXTERNALMEASURE("Melding projectstand", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen
		lineageTag: f26bf989-1d04-403f-8a97-e3a6c756eba5
		sourceLineageTag: 0a751714-fe1d-4b69-ab64-262393afe9a3
		dataCategory: Uncategorized

	measure 'Melding projecten' = EXTERNALMEASURE("Melding projecten", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Algemeen
		lineageTag: 39a7a910-e47d-4c4c-912d-38b3d7839f06
		sourceLineageTag: f2428f37-3ec2-4579-9559-ce13a9b84d80
		dataCategory: Uncategorized

	/// --Omschrijving--
	/// Gerealiseerde uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     SUM('Geboekte Uren'[Aantal])
	///     ,NOT(ISBLANK('Geboekte Uren'[TaakKey]))
	///     ,'Geboekte Uren'[Uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Gerealiseerde uren historisch' = EXTERNALMEASURE("Gerealiseerde uren historisch", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.02 HR\Gerealiseerde uren
		lineageTag: 18ae871d-d27e-43b5-9a8c-28af960cab4f
		sourceLineageTag: 751a968b-17d4-4468-bdf5-602da4fa3b8f
		dataCategory: Uncategorized

	measure 'Gerealiseerde uren projecten' = EXTERNALMEASURE("Gerealiseerde uren projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 133cd255-285f-4b46-b22b-97a617aba4e0
		sourceLineageTag: a8fe9afa-1e16-408a-a415-c77c8a9feef9
		dataCategory: Uncategorized

	/// --Omschrijving--
	/// Gerealiseerde uren tot en met geselecteerde standdatum. 
	/// 
	/// LET OP; kan in combinatie met kalender tabel/filter ook gefilterd zijn.
	/// 
	/// 
	/// --DAX--
	/// CALCULATE(
	///     SUM('Geboekte Uren'[Aantal])
	///     ,NOT(ISBLANK('Geboekte Uren'[TaakKey]))
	///     ,'Geboekte Uren'[Uitvoeringsdatum]<=MAX('Standdatums'[standdatum])
	/// )
	measure 'Gerealiseerde uren historisch projecten' = EXTERNALMEASURE("Gerealiseerde uren historisch projecten", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 81275c0a-e877-4970-bdf7-584cc123650c
		sourceLineageTag: 916a0aa7-0371-40fe-add7-af36fbd1e7f3
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs arbeid montage' = EXTERNALMEASURE("Calculatie kostprijs arbeid montage", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: b58c0635-25c1-478e-9b5d-29b7bcbbb779
		sourceLineageTag: 2a63a163-faab-49ec-8e44-82c74b4d45c1
		dataCategory: Uncategorized

	measure 'Calculatie kostprijs arbeid projectgebonden' = EXTERNALMEASURE("Calculatie kostprijs arbeid projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 5c6320a7-344b-4ee0-a203-95cee11340bd
		sourceLineageTag: a3850863-a032-48a3-9698-8eb2ce3ad6dd
		dataCategory: Uncategorized

	measure 'Calculatie verrekenprijs inkoop' = EXTERNALMEASURE("Calculatie verrekenprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 8d2ce16c-e6e4-48a5-9981-2ed84393ef2f
		sourceLineageTag: 4be81a19-dd81-441f-b08f-47bbdb065b40
		dataCategory: Uncategorized

	measure 'Calculatie verrekenprijs arbeid montage' = EXTERNALMEASURE("Calculatie verrekenprijs arbeid montage", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: 6acbc36b-8584-4601-a785-92908c222156
		sourceLineageTag: d151c7e9-2668-491e-8d91-b5b2fe55d005
		dataCategory: Uncategorized

	measure 'Calculatie verrekenprijs arbeid projectgebonden' = EXTERNALMEASURE("Calculatie verrekenprijs arbeid projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Calculatie
		lineageTag: f270d263-d1c6-4e3b-b6e7-c4c7dd805d43
		sourceLineageTag: 05bbb1ce-58ad-447b-b6bd-e6aecca9579a
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs arbeid montage' = EXTERNALMEASURE("Definitieve kostprijs arbeid montage", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 616438c9-cd14-4653-a4e5-b236263fb612
		sourceLineageTag: 15e0a18d-dbf8-4762-86ff-afd9627321e7
		dataCategory: Uncategorized

	measure 'Definitieve kostprijs arbeid projectgebonden' = EXTERNALMEASURE("Definitieve kostprijs arbeid projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 2459d52f-1a49-48bb-bbec-15a8fb2f551b
		sourceLineageTag: 45296c68-cb1e-4b19-866a-d7eb8c287b4f
		dataCategory: Uncategorized

	measure 'Onverwerkte verrekenprijs arbeid montage' = EXTERNALMEASURE("Onverwerkte verrekenprijs arbeid montage", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 04444fc1-bdc8-4a08-abdf-cadb67f1822f
		sourceLineageTag: 32a1b21f-a1dd-4f92-9b40-765b267643ee
		dataCategory: Uncategorized

	measure 'Onverwerkte verrekenprijs arbeid projectgebonden' = EXTERNALMEASURE("Onverwerkte verrekenprijs arbeid projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 6cc63daa-94f0-472e-9243-95a3796d1dda
		sourceLineageTag: 9ebc5ff5-fd85-42a7-ae2e-a73664ff538a
		dataCategory: Uncategorized

	measure 'Einde boekdatum' = EXTERNALMEASURE("Einde boekdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 1b60d558-2fbe-4940-9f6c-129ec7f6badf
		sourceLineageTag: b67830ed-d5b9-4eea-8376-d48ab6a1c9e0
		dataCategory: Uncategorized

	measure 'Start boekdatum' = EXTERNALMEASURE("Start boekdatum", DATETIME, "DirectQuery to AS - SSM")
		formatString: Short Date
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Meldingen
		lineageTag: 30cbe329-b4aa-4ebf-8ddd-2b94082dddd5
		sourceLineageTag: 5cf5362b-39bc-4f1d-8b0e-88d022559758
		dataCategory: Uncategorized

	measure 'Verzoek Kosten arbeid montage' = EXTERNALMEASURE("Verzoek Kosten arbeid montage", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 7a679752-40a3-4dae-8876-ab29aafd5a9a
		sourceLineageTag: 191ecf8f-6918-4e66-a003-ecebcef4e3f3
		dataCategory: Uncategorized

	measure 'Verzoek Kosten arbeid projectgebonden' = EXTERNALMEASURE("Verzoek Kosten arbeid projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Budget en prognose\Budgetverzoek o.b.v. Budget Verzoek App
		lineageTag: 9b042bdd-bfe9-4922-9257-9046fb2f393e
		sourceLineageTag: c3ab2e9d-1d8d-47e2-aee3-e869fdfdddd2
		dataCategory: Uncategorized

	measure 'Definitieve verrekenprijs inkoop' = EXTERNALMEASURE("Definitieve verrekenprijs inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 97b9375e-122c-40c8-8ea8-cae3c0184041
		sourceLineageTag: e1003a8e-9307-4e16-adf6-8dbd8341ea5f
		dataCategory: Uncategorized

	measure 'Definitieve verrekenprijs arbeid montage' = EXTERNALMEASURE("Definitieve verrekenprijs arbeid montage", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: d0b62343-ac25-4b3d-9e32-2a02e143948c
		sourceLineageTag: b74a4047-c1b0-4671-8f0f-f547fd932c1d
		dataCategory: Uncategorized

	measure 'Definitieve verrekenprijs arbeid projectgebonden' = EXTERNALMEASURE("Definitieve verrekenprijs arbeid projectgebonden", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;#,0\ -"€";"€"\ #,0
		displayFolder: 1. Semantisch model\1.03 Projecten\Project kosten
		lineageTag: 9af93835-3acf-4b10-b6f3-92fc1da9ab52
		sourceLineageTag: 04f9348b-1750-42e6-9a76-e09806c5a8af
		dataCategory: Uncategorized

	measure 'Projectgebonden uren definitief' = EXTERNALMEASURE("Projectgebonden uren definitief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: ffde25c3-5a94-49e4-95ca-727a76f30254
		sourceLineageTag: 714c10e6-d41f-4772-be45-63ad8f0d20cc
		dataCategory: Uncategorized

	measure 'Montage uren definitief' = EXTERNALMEASURE("Montage uren definitief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 6ea636e2-34da-443f-acda-a36c99f09e0a
		sourceLineageTag: 9d5ac86b-6572-4814-82af-d90be9a0ce9e
		dataCategory: Uncategorized

	measure 'Projectgebonden uren onverwerkt' = EXTERNALMEASURE("Projectgebonden uren onverwerkt", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 0928884d-7b00-477c-b2c0-99eba28e7e96
		sourceLineageTag: 1a94d641-aa7e-4529-a469-e3a69f1237ee
		dataCategory: Uncategorized

	measure 'Montage uren onverwerkt' = EXTERNALMEASURE("Montage uren onverwerkt", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 599d6f63-d4d3-49ad-81e5-79f950816439
		sourceLineageTag: 049b0b40-60ca-4aac-8573-ca7cee09b2e1
		dataCategory: Uncategorized

	measure 'Start boekdatum projectvoortgang app' = EXTERNALMEASURE("Start boekdatum projectvoortgang app", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yyyy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App
		lineageTag: 38bb13e5-2703-40b8-8df1-70e9827d07a0
		sourceLineageTag: 7834b66a-ef92-46fa-8707-bea68c9f493b
		dataCategory: Uncategorized

	measure 'Eind boekdatum projectvoortgang app' = EXTERNALMEASURE("Eind boekdatum projectvoortgang app", DATETIME, "DirectQuery to AS - SSM")
		formatString: dd\-mm\-yyyy
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App
		lineageTag: b252ee37-d040-45fd-b9a6-3591e4c0c80f
		sourceLineageTag: 5e58ba0e-15f4-4cf1-8b30-aa6130a3ec75
		dataCategory: Uncategorized

	measure 'Klantnummer projectvoortgang app' = EXTERNALMEASURE("Klantnummer projectvoortgang app", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App
		lineageTag: 92349f08-41bf-4d58-b01d-88bf0adf00b6
		sourceLineageTag: c24a010f-bc4b-4ee1-a9d7-63ac1e6e729d
		dataCategory: Uncategorized

	measure 'Hoogste projectniveau voortgang app' = EXTERNALMEASURE("Hoogste projectniveau voortgang app", INTEGER, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 2. Rapport Specifieke Objecten\2.03 Best Practice Projecten\Projectvoortgang App
		lineageTag: dc8f39cb-3913-4106-9593-aff25eb953f1
		sourceLineageTag: 9785d103-f731-4f20-8e33-cf1a6f506732
		dataCategory: Uncategorized

	measure 'Geselecteerde maandindex standdatum kalender' = EXTERNALMEASURE("Geselecteerde maandindex standdatum kalender", INTEGER, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: d1bb017e-ae7c-4ccb-a974-f041c7aa2158
		sourceLineageTag: 4ef8bfd1-04b7-46a3-b0b3-ebf300aec5eb
		dataCategory: Uncategorized

	measure 'Melding periode cumulatief LY o.b.v. standdatum' = EXTERNALMEASURE("Melding periode cumulatief LY o.b.v. standdatum", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: aa8ce1c9-1c93-4bd5-96a0-4054a79c13fb
		sourceLineageTag: 80898374-dd73-4255-982e-c19ea34a3d16
		dataCategory: Uncategorized

	measure 'Melding periode cumulatief o.b.v. standdatum' = EXTERNALMEASURE("Melding periode cumulatief o.b.v. standdatum", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: 3c989cf4-3c5f-4d21-89af-54235d8a74d9
		sourceLineageTag: ce867e7d-7f7a-4564-8a73-6c3d4d44573c
		dataCategory: Uncategorized

	measure 'Melding resultaat cumulatief o.b.v. standdatum' = EXTERNALMEASURE("Melding resultaat cumulatief o.b.v. standdatum", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: 9259bdf1-72d0-4295-92af-b818e55581d3
		sourceLineageTag: 740688b4-2bcd-4ece-a5fe-5bd161f38544
		dataCategory: Uncategorized

	measure 'Melding resultaat geselecteerde maand o.b.v. standdatum' = EXTERNALMEASURE("Melding resultaat geselecteerde maand o.b.v. standdatum", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: 1c90e1ba-637b-4640-becf-279818f36670
		sourceLineageTag: 53592bdb-1a96-4604-9582-e5416404bf50
		dataCategory: Uncategorized

	measure 'Verschil debet-credit balans CoA o.b.v. standdatum' = EXTERNALMEASURE("Verschil debet-credit balans CoA o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans
		lineageTag: 4f10dc21-9865-49b8-bccc-30dace25fe60
		sourceLineageTag: b6201c2c-cc2e-4c5a-bd4b-2f7bcd21dbb9
		dataCategory: Uncategorized

	measure 'Verschil credit-debet balans CoA o.b.v. standdatum' = EXTERNALMEASURE("Verschil credit-debet balans CoA o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans
		lineageTag: a1050605-57d4-4580-a939-62b3f6264a12
		sourceLineageTag: 4b130ba3-85d0-48ad-a5a1-5ada6bf7d9b1
		dataCategory: Uncategorized

	measure 'CoA balans YTD o.b.v. standdatum' = EXTERNALMEASURE("CoA balans YTD o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans
		lineageTag: 98da8fac-3950-47c1-bc3b-28653aa847bd
		sourceLineageTag: 9532544f-ead1-45ae-b4ed-ac9a21e635e7
		dataCategory: Uncategorized

	measure 'Actual debet-YTD Balans CoA o.b.v. standdatum' = EXTERNALMEASURE("Actual debet-YTD Balans CoA o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans
		lineageTag: 33a27fba-bc0e-4c77-af1d-201451cebf73
		sourceLineageTag: b7d6b222-20b4-468a-990f-8bc8dd785f1d
		dataCategory: Uncategorized

	measure 'Actual credit-YTD Balans CoA o.b.v. standdatum' = EXTERNALMEASURE("Actual credit-YTD Balans CoA o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA Balans
		lineageTag: 752a8053-22eb-4c74-a734-8326d94bd235
		sourceLineageTag: 4e521501-0ebb-4860-988b-57b698aa4adb
		dataCategory: Uncategorized

	measure '% standmaand t.o.v. standmaand LY' = EXTERNALMEASURE("% standmaand t.o.v. standmaand LY", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Ratio
		lineageTag: e4748b2b-21c7-4c38-b6b7-d38d5871e22e
		sourceLineageTag: 79d6fc57-162a-448b-b601-e3f48e491666
		dataCategory: Uncategorized

	measure 'CoA actual LY in standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA actual LY in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 48473d0a-b1b0-4ed2-bece-e431a07194ac
		sourceLineageTag: 09c66e92-ead1-4c7c-b374-c2e41cc5ce13
		dataCategory: Uncategorized

	measure 'CoA mutatie budget in de standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA mutatie budget in de standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget
		lineageTag: ea69d6e5-5a80-4e9a-abf2-59196e09140c
		sourceLineageTag: 086d2fb7-26f1-4db8-8456-229dfd025d05
		dataCategory: Uncategorized

	measure 'CoA mutatie in de standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA mutatie in de standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 482a4e92-77cc-4c3f-b0f3-36828d0eac84
		sourceLineageTag: 87a37f10-dedd-4e1b-96dd-ffb39005a16e
		dataCategory: Uncategorized

	measure 'CoA YTD rendement budget in standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA YTD rendement budget in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget
		lineageTag: 85c37483-eb3d-4b81-902f-9626d35325a5
		sourceLineageTag: 1eac685a-d8a2-4fb7-b17a-38b49017c34d
		dataCategory: Uncategorized

	measure 'CoA YTD rendement in standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA YTD rendement in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 11f75f42-cdf4-44e2-a5c4-9d07e5cdc4b2
		sourceLineageTag: 06d1bf11-dbb7-4808-abd5-329d516466a6
		dataCategory: Uncategorized

	measure 'Delta standmaand - standmaand LY' = EXTERNALMEASURE("Delta standmaand - standmaand LY", DOUBLE, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 9dde102d-3331-490e-b581-50b6253dd192
		sourceLineageTag: ff6e72b6-81a6-4108-aebf-09958d4aa827
		dataCategory: Uncategorized

	measure 'Mutatie resultaat budget in standmaand o.b.v. standmaand' = EXTERNALMEASURE("Mutatie resultaat budget in standmaand o.b.v. standmaand", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Syntess budget
		lineageTag: b151d227-8bb8-478d-b430-f50a49f7bb1f
		sourceLineageTag: b3c75e91-e170-4fbe-8a8f-299f374865dc
		dataCategory: Uncategorized

	measure 'Mutatie resultaat in standmaand o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 9aea91d3-c4ad-412c-99b6-953da5dca8b6
		sourceLineageTag: f746b80d-3f1d-4067-8354-fd10053e0d9a
		dataCategory: Uncategorized

	measure 'Mutatie resultaat LY o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat LY o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: f82e2e22-2828-4b6c-a71b-7c22f6f7b0d9
		sourceLineageTag: 15f41e2f-1fb7-40f9-a888-b569ae29fd99
		dataCategory: Uncategorized

	measure 'Mutatie resultaat met mapping in standmaand LY o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat met mapping in standmaand LY o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 1b863dc2-f7df-448a-ae72-c3d3ac6b85ec
		sourceLineageTag: 67c7b252-e1f0-4993-9da0-1e70a1223ce5
		dataCategory: Uncategorized

	measure 'Mutatie resultaat met mapping in standmaand o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat met mapping in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: e689472c-a974-475d-8cde-3d1d7e3a5b9b
		sourceLineageTag: 1ba861bc-2555-4699-ae8e-ef5286b0bcd8
		dataCategory: Uncategorized

	measure 'Mutatie resultaat o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 1490f237-9e11-4267-8140-d9f88ac5ef59
		sourceLineageTag: c36887b6-255c-4cb4-9075-de1c7d0e540b
		dataCategory: Uncategorized

	measure 'Mutatie resultaat YTD LY o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat YTD LY o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 97efb5d4-23de-42d9-a71b-3efd123c6e15
		sourceLineageTag: 0e351a78-e182-48eb-8eaa-55398bb41749
		dataCategory: Uncategorized

	measure 'Mutatie resultaat YTD o.b.v. standdatum' = EXTERNALMEASURE("Mutatie resultaat YTD o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Actual
		lineageTag: 676e9f95-d821-4400-8774-d7df7e701278
		sourceLineageTag: b8eead40-5dce-4d62-aea7-dc8848fa3f95
		dataCategory: Uncategorized

	measure Kolombreedte7 = EXTERNALMEASURE("Kolombreedte7", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 1700ddf5-6743-4078-b534-2facf6f7a89c
		sourceLineageTag: 6e240d4b-7197-461e-b327-ab1f4eda9dff
		dataCategory: Uncategorized

	measure Kolombreedte6 = EXTERNALMEASURE("Kolombreedte6", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 3ca72998-2572-4fb9-a8cb-aa34be261e95
		sourceLineageTag: 1c7cb5a6-5476-4794-a71b-0a9df80a0c27
		dataCategory: Uncategorized

	measure Kolombreedte8 = EXTERNALMEASURE("Kolombreedte8", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: f89964c8-e416-4238-9dcf-09450666f9ab
		sourceLineageTag: 64d06f17-764c-49ea-a186-99fb51d730ae
		dataCategory: Uncategorized

	measure Kolombreedte9 = EXTERNALMEASURE("Kolombreedte9", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: 06d3f025-2131-46cc-8dba-cfea4150e544
		sourceLineageTag: 7c809c87-9bfe-4201-953d-1aad1b0c1735
		dataCategory: Uncategorized

	measure Kolombreedte5 = EXTERNALMEASURE("Kolombreedte5", STRING, "DirectQuery to AS - SSM")
		displayFolder: 1. Semantisch model\1.99 Overig\Algemeen
		lineageTag: d6436606-064e-44a1-9973-3c78c42d4bee
		sourceLineageTag: 98e102ec-0470-475f-ae34-5cdb1919fe77
		dataCategory: Uncategorized

	measure 'CoA mutatie notifica budget' = EXTERNALMEASURE("CoA mutatie notifica budget", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0;(#,##0);
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget
		lineageTag: 91082282-7878-46cd-97be-f175ca4cd30d
		sourceLineageTag: b1dd5bf8-5c8c-40b2-8bb3-3d55df08cb5d
		dataCategory: Uncategorized

	measure 'CoA YTD rendement notifica budget in standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA YTD rendement notifica budget in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Notifica budget
		lineageTag: b4476e15-a354-4778-8fa0-e0322c52727d
		sourceLineageTag: 3bc18daf-1799-493a-a9bc-8fda19343e81
		dataCategory: Uncategorized

	measure 'CoA Forecast mutatie in de standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA Forecast mutatie in de standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast
		lineageTag: 49d585f3-a1e7-4ea5-9367-af55ff6f0937
		sourceLineageTag: bb46826c-4fc1-41f5-874e-db860f5a41ff
		dataCategory: Uncategorized

	measure 'CoA YTD rendement notifica forecast in standmaand o.b.v. standdatum' = EXTERNALMEASURE("CoA YTD rendement notifica forecast in standmaand o.b.v. standdatum", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast
		lineageTag: fa63a318-640e-4e13-9541-50ec17e7dfee
		sourceLineageTag: 7c348b87-77b9-422a-91a1-53074575209c
		dataCategory: Uncategorized

	measure 'Mutatie resultaat notifica forecast' = EXTERNALMEASURE("Mutatie resultaat notifica forecast", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\CoA rekeningschema\Forecast
		lineageTag: 04489a91-f410-4134-9fc8-d8d9019b19e0
		sourceLineageTag: 0ea2b46c-0fb5-4ed4-9308-9e5b42237ca0
		dataCategory: Uncategorized

	measure 'Melding geselecteerd boekjaar' = EXTERNALMEASURE("Melding geselecteerd boekjaar", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: 74348c7c-7132-4aef-a7ea-2c2a35acf093
		sourceLineageTag: 595f030f-2753-4126-a7fd-9c45433ed55a
		dataCategory: Uncategorized

	measure 'Melding stand balans per einde standdatum' = EXTERNALMEASURE("Melding stand balans per einde standdatum", STRING, "DirectQuery to AS - SSM")
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Algemeen
		lineageTag: cf077aa3-f89a-447e-ac00-9c5089071640
		sourceLineageTag: 763e0a25-e2e6-4683-977a-d8fca24a2b61
		dataCategory: Uncategorized

	measure 'Montage uren incl inleen via inkoop cumulatief' = EXTERNALMEASURE("Montage uren incl inleen via inkoop cumulatief", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 4146cc31-ab79-420b-9293-96a6098d6944
		sourceLineageTag: 67e4fcbc-9a2e-44bc-86f0-27d759e332a8
		dataCategory: Uncategorized

	measure 'Montage uren incl inleen via inkoop' = EXTERNALMEASURE("Montage uren incl inleen via inkoop", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0
		displayFolder: 1. Semantisch model\1.03 Projecten\Arbeid
		lineageTag: 731d0606-ebe0-4733-8e0b-b3c93bba0f0f
		sourceLineageTag: e18d8f5f-9d4c-42b2-a405-e9c9b486bae8
		dataCategory: Uncategorized

	measure 'Bruto rendement YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Bruto rendement YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: f3d3b735-6f6c-450a-ac8e-374c4c7d824f
		sourceLineageTag: 95d8f5fd-3bad-445f-902b-0e80bdf6bdd5
		dataCategory: Uncategorized

	measure 'Bruto rendement YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Bruto rendement YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 5c5c98a5-be43-4de3-8477-cd52f90bf514
		sourceLineageTag: a02a1d5f-e88a-4656-9793-1d49748be9cd
		dataCategory: Uncategorized

	measure 'Brutowinst YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Brutowinst YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 6ba59daf-a40a-4d2a-ae4f-0ef95895abe3
		sourceLineageTag: 99464fd2-7654-472d-9aa9-4e93afc6b1a0
		dataCategory: Uncategorized

	measure 'Brutowinst YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Brutowinst YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 4eeb7804-bf0d-42c9-ad83-f5f8c99fa724
		sourceLineageTag: 9a7e02ac-ba04-403d-91ef-feff653fbf90
		dataCategory: Uncategorized

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Directe kosten (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 35ee86f5-104e-4b81-a487-aec33a1a2a3a
		sourceLineageTag: 25d17d87-f2a5-410f-8902-9a196a1b9f77
		dataCategory: Uncategorized

	measure 'Directe kosten t/m standdatum (benchmark schema)' = EXTERNALMEASURE("Directe kosten t/m standdatum (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: d4a48a73-db2b-440b-b0af-da9143f65d0b
		sourceLineageTag: b9cc571e-d13f-4b00-b915-8f390997a1bd
		dataCategory: Uncategorized

	/// Directe kosten cumulatief tot einde geselecteerde einddatum.
	measure 'Directe kosten YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Directe kosten YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: ea573a70-335a-4994-b2ce-3cc120c031c7
		sourceLineageTag: 4421acb9-2f65-41ec-85b5-98bed35fbaaf
		dataCategory: Uncategorized

	/// Zie [Directe kosten YTD]. Betreft directe kosten cumulaief over dezelfde periode vorig jaar.
	measure 'Directe kosten YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Directe kosten YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: b36e7059-a47f-47b7-a09b-2dc1d9ae8148
		sourceLineageTag: fa0fc66f-8ca5-4963-b853-b98836e8c4c6
		dataCategory: Uncategorized

	measure 'Indirecte kosten t/m standdatum (benchmark schema)' = EXTERNALMEASURE("Indirecte kosten t/m standdatum (benchmark schema)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: c05cc419-df94-430a-8589-cea188033c17
		sourceLineageTag: 4baf8716-2d38-46b0-98c7-79470150b978
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Indirecte kosten YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 6591d6d4-85dc-4363-b2cd-b3be2c4ab50e
		sourceLineageTag: 86f2f94e-9584-4a96-a3b8-66023ce1d1e2
		dataCategory: Uncategorized

	measure 'Indirecte kosten YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Indirecte kosten YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 673556b8-619b-48ec-acff-e227c1f752bc
		sourceLineageTag: 46480b15-4042-4bf4-953e-1fc47488f07d
		dataCategory: Uncategorized

	measure 'Netto rendement YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Netto rendement YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: bc18bb50-6e18-4904-9c43-ed99c77b2392
		sourceLineageTag: e44a2627-c8d1-43d9-86ad-9173609e7964
		dataCategory: Uncategorized

	measure 'Netto rendement YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Netto rendement YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 6ccebb85-d1ad-43bc-9887-fbf8f4bffead
		sourceLineageTag: 97dd7fa0-89ad-44d7-8011-1f5f12889ff3
		dataCategory: Uncategorized

	measure 'Nettowinst YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Nettowinst YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 37005bdd-eb95-4214-af47-5e61ca35b9c3
		sourceLineageTag: 3cd7e52c-a379-4403-8d2d-64f2b278c493
		dataCategory: Uncategorized

	measure 'Nettowinst YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Nettowinst YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 9d5da119-603b-4ea2-90a1-5ea4a8b4af0f
		sourceLineageTag: fe3cdf20-609b-45e7-a159-9dc8e16d2978
		dataCategory: Uncategorized

	measure 'Omzet YTD (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Omzet YTD (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: d21d8a14-e1b5-4850-8f3a-53daec6d57de
		sourceLineageTag: 48a5a342-6dd6-4835-b569-625cb78bc346
		dataCategory: Uncategorized

	measure 'Omzet YTDLY (benchmark schema o.b.v. standdatum)' = EXTERNALMEASURE("Omzet YTDLY (benchmark schema o.b.v. standdatum)", DOUBLE, "DirectQuery to AS - SSM")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		displayFolder: 2. Rapport Specifieke Objecten\2.01 Best Practice Financieel\Forecast resultaatrekening\Resultaat topsheet
		lineageTag: 1f50552a-340e-4a2c-b725-90a2ad2ba012
		sourceLineageTag: 0944cc60-4ab9-4f72-b5a4-268183b60794
		dataCategory: Uncategorized

	measure 'Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel' = EXTERNALMEASURE("Aantal uren werkbonparagraaf o.b.v. boekdatum urenregel", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: 717c7ab9-75a6-4f80-8a59-9b29b65b0dc2
		sourceLineageTag: f254c7d2-a2f3-4c19-a11c-e26f7a21fdf7
		dataCategory: Uncategorized

	measure 'Aantal uren werkbonparagraaf o.b.v. boekdatum werkbon' = EXTERNALMEASURE("Aantal uren werkbonparagraaf o.b.v. boekdatum werkbon", DOUBLE, "DirectQuery to AS - SSM")
		formatString: #,##0
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: a634bd18-ede0-4d78-ae2a-fe5eb9be8ce9
		sourceLineageTag: 2bdca691-8ff2-4c0e-ac2f-40aa90152fad
		dataCategory: Uncategorized

	measure 'onderhoud en storing % van totaal' = EXTERNALMEASURE("onderhoud en storing % van totaal", DOUBLE, "DirectQuery to AS - SSM")
		formatString: 0%;-0%;0%
		displayFolder: 2. Rapport Specifieke Objecten\2.04 Best practice Service\Onderhoudsplanning
		lineageTag: dee1821b-6d03-4f5b-bb90-d4865cc2a466
		sourceLineageTag: d2980af4-e4fb-4851-b2ed-158c8359570a
		dataCategory: Uncategorized

	column NietGebruiken
		dataType: string
		isHidden
		lineageTag: 3aee1c9b-64d6-4aa7-944e-5530b233e290
		sourceLineageTag: c66234ce-7e99-48cd-ae09-7f0eb0116884
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: NietGebruiken

		annotation SummarizationSetBy = User

	partition Formules = entity
		mode: directQuery
		source
			entityName: Formules
			expressionSource: 'DirectQuery to AS - SSM'

