// ============================================================================
// DAX MEASURES VOORRAAD - SYNTESS
// ============================================================================
// Versie: 1.0
// Datum: Januari 2026
//
// INSTRUCTIES:
// 1. Kopieer deze measures naar het Semantisch Model
// 2. Pas de Display Folder aan indien gewenst
// 3. Test elke measure voordat je doorgaat naar de volgende
//
// LET OP: De relatie UitgifteVoorraadpositieKey -> VoorraadpositieKey is
// INACTIEF in het model. Daarom gebruiken we USERELATIONSHIP() voor uitgiftes.
// ============================================================================


// ============================================================================
// FOLDER: Voorraad\1. Basis Mutaties
// ============================================================================

// Ontvangsten (IN-mutaties via actieve relatie)
Voorraad Ontvangst Aantal =
SUM('Voorraad mutaties'[Aantal])

// Ontvangsten waarde op kostprijs
Voorraad Ontvangst Waarde Kostprijs =
SUM('Voorraad mutaties'[Kostprijs])

// Ontvangsten waarde op verrekenprijs
Voorraad Ontvangst Waarde Verrekenprijs =
SUM('Voorraad mutaties'[Verrekenprijs])

// Uitgiftes (UIT-mutaties via INACTIEVE relatie - USERELATIONSHIP nodig!)
Voorraad Uitgifte Aantal =
CALCULATE(
    SUM('Voorraad mutaties'[Aantal]),
    USERELATIONSHIP(
        'Voorraad mutaties'[UitgifteVoorraadpositieKey],
        'Voorraad posities'[VoorraadpositieKey]
    )
)

// Uitgiftes waarde op kostprijs
Voorraad Uitgifte Waarde Kostprijs =
CALCULATE(
    SUM('Voorraad mutaties'[Kostprijs]),
    USERELATIONSHIP(
        'Voorraad mutaties'[UitgifteVoorraadpositieKey],
        'Voorraad posities'[VoorraadpositieKey]
    )
)

// Uitgiftes waarde op verrekenprijs
Voorraad Uitgifte Waarde Verrekenprijs =
CALCULATE(
    SUM('Voorraad mutaties'[Verrekenprijs]),
    USERELATIONSHIP(
        'Voorraad mutaties'[UitgifteVoorraadpositieKey],
        'Voorraad posities'[VoorraadpositieKey]
    )
)


// ============================================================================
// FOLDER: Voorraad\2. Voorraadstand
// ============================================================================

// Actuele voorraadstand in aantallen
Voorraad Stand Aantal =
VAR Ontvangsten = [Voorraad Ontvangst Aantal]
VAR Uitgiftes = [Voorraad Uitgifte Aantal]
RETURN
    Ontvangsten - Uitgiftes

// Voorraadwaarde op kostprijs
Voorraad Stand Waarde Kostprijs =
VAR Ontvangsten = [Voorraad Ontvangst Waarde Kostprijs]
VAR Uitgiftes = [Voorraad Uitgifte Waarde Kostprijs]
RETURN
    Ontvangsten - Uitgiftes

// Voorraadwaarde op verrekenprijs
Voorraad Stand Waarde Verrekenprijs =
VAR Ontvangsten = [Voorraad Ontvangst Waarde Verrekenprijs]
VAR Uitgiftes = [Voorraad Uitgifte Waarde Verrekenprijs]
RETURN
    Ontvangsten - Uitgiftes

// Gemiddelde kostprijs per eenheid op voorraad
Voorraad Gemiddelde Kostprijs =
DIVIDE(
    [Voorraad Stand Waarde Kostprijs],
    [Voorraad Stand Aantal],
    0
)

// Gemiddelde verrekenprijs per eenheid op voorraad
Voorraad Gemiddelde Verrekenprijs =
DIVIDE(
    [Voorraad Stand Waarde Verrekenprijs],
    [Voorraad Stand Aantal],
    0
)


// ============================================================================
// FOLDER: Voorraad\3. Min-Max Bewaking
// ============================================================================

// Aantal posities met voorraad onder minimum
Voorraad Onder Minimum Aantal Posities =
SUMX(
    'Voorraad posities',
    VAR HuidigeStand = [Voorraad Stand Aantal]
    VAR MinVoorraad = 'Voorraad posities'[MinimumVoorraad]
    RETURN
        IF(
            HuidigeStand < MinVoorraad
            && MinVoorraad > 0
            && 'Voorraad posities'[Status] = "Actueel",
            1,
            0
        )
)

// Aantal posities met voorraad boven maximum
Voorraad Boven Maximum Aantal Posities =
SUMX(
    'Voorraad posities',
    VAR HuidigeStand = [Voorraad Stand Aantal]
    VAR MaxVoorraad = 'Voorraad posities'[MaximumVoorraad]
    RETURN
        IF(
            HuidigeStand > MaxVoorraad
            && MaxVoorraad > 0
            && 'Voorraad posities'[Status] = "Actueel",
            1,
            0
        )
)

// Tekort t.o.v. minimum (voor specifieke positie)
Voorraad Tekort Aantal =
VAR MinVoorraad = SELECTEDVALUE('Voorraad posities'[MinimumVoorraad], 0)
VAR HuidigeStand = [Voorraad Stand Aantal]
RETURN
    IF(
        HuidigeStand < MinVoorraad && MinVoorraad > 0,
        MinVoorraad - HuidigeStand,
        0
    )

// Overschot t.o.v. maximum (voor specifieke positie)
Voorraad Overschot Aantal =
VAR MaxVoorraad = SELECTEDVALUE('Voorraad posities'[MaximumVoorraad], 0)
VAR HuidigeStand = [Voorraad Stand Aantal]
RETURN
    IF(
        HuidigeStand > MaxVoorraad && MaxVoorraad > 0,
        HuidigeStand - MaxVoorraad,
        0
    )

// Voorraadstatus als tekst (voor conditional formatting)
Voorraad Status =
VAR HuidigeStand = [Voorraad Stand Aantal]
VAR MinVoorraad = SELECTEDVALUE('Voorraad posities'[MinimumVoorraad], 0)
VAR MaxVoorraad = SELECTEDVALUE('Voorraad posities'[MaximumVoorraad], 0)
RETURN
    SWITCH(
        TRUE(),
        HuidigeStand <= 0, "Geen voorraad",
        MinVoorraad > 0 && HuidigeStand < MinVoorraad, "Onder minimum",
        MaxVoorraad > 0 && HuidigeStand > MaxVoorraad, "Boven maximum",
        "OK"
    )

// Voorraadstatus als getal (voor sortering: 1=kritiek, 4=ok)
Voorraad Status Sorteer =
VAR HuidigeStand = [Voorraad Stand Aantal]
VAR MinVoorraad = SELECTEDVALUE('Voorraad posities'[MinimumVoorraad], 0)
VAR MaxVoorraad = SELECTEDVALUE('Voorraad posities'[MaximumVoorraad], 0)
RETURN
    SWITCH(
        TRUE(),
        HuidigeStand <= 0, 1,
        MinVoorraad > 0 && HuidigeStand < MinVoorraad, 2,
        MaxVoorraad > 0 && HuidigeStand > MaxVoorraad, 3,
        4
    )


// ============================================================================
// FOLDER: Voorraad\4. Analyse
// ============================================================================

// Omloopsnelheid voorraad (jaarlijks)
Voorraad Omloopsnelheid =
VAR UitgifteJaar =
    CALCULATE(
        [Voorraad Uitgifte Waarde Kostprijs],
        DATESINPERIOD(Kalender[Datum], MAX(Kalender[Datum]), -1, YEAR)
    )
VAR GemiddeldeVoorraad =
    AVERAGEX(
        SUMMARIZE(
            DATESINPERIOD(Kalender[Datum], MAX(Kalender[Datum]), -1, YEAR),
            Kalender[Maand]
        ),
        [Voorraad Stand Waarde Kostprijs]
    )
RETURN
    DIVIDE(UitgifteJaar, GemiddeldeVoorraad, 0)

// Dagen voorraad (DSI - Days Sales of Inventory)
Voorraad Dagen Voorraad =
DIVIDE(
    365,
    [Voorraad Omloopsnelheid],
    BLANK()
)

// Aantal unieke artikelen met voorraad > 0
Voorraad Aantal Artikelen =
CALCULATE(
    DISTINCTCOUNT('Voorraad posities'[TariefKey]),
    FILTER(
        'Voorraad posities',
        [Voorraad Stand Aantal] > 0
    )
)

// Totaal aantal voorraadmutaties
Voorraad Aantal Mutaties =
COUNTROWS('Voorraad mutaties')

// Aantal ontvangst mutaties
Voorraad Aantal Ontvangsten =
CALCULATE(
    COUNTROWS('Voorraad mutaties'),
    NOT(ISBLANK('Voorraad mutaties'[OntvangstVoorraadpositieKey]))
)

// Aantal uitgifte mutaties
Voorraad Aantal Uitgiftes =
CALCULATE(
    COUNTROWS('Voorraad mutaties'),
    NOT(ISBLANK('Voorraad mutaties'[UitgifteVoorraadpositieKey]))
)


// ============================================================================
// FOLDER: Voorraad\5. Tijdvergelijking
// ============================================================================

// Voorraadstand vorige maand
Voorraad Stand VM =
CALCULATE(
    [Voorraad Stand Aantal],
    PREVIOUSMONTH(Kalender[Datum])
)

// Voorraadstand vorig jaar zelfde periode
Voorraad Stand VJ =
CALCULATE(
    [Voorraad Stand Aantal],
    SAMEPERIODLASTYEAR(Kalender[Datum])
)

// Mutatie maand-over-maand
Voorraad Mutatie MoM =
[Voorraad Stand Aantal] - [Voorraad Stand VM]

// Mutatie jaar-over-jaar
Voorraad Mutatie YoY =
[Voorraad Stand Aantal] - [Voorraad Stand VJ]

// Percentage mutatie MoM
Voorraad Mutatie MoM % =
DIVIDE(
    [Voorraad Mutatie MoM],
    [Voorraad Stand VM],
    0
)

// Year-to-date ontvangsten
Voorraad Ontvangst YTD =
CALCULATE(
    [Voorraad Ontvangst Aantal],
    DATESYTD(Kalender[Datum])
)

// Year-to-date uitgiftes
Voorraad Uitgifte YTD =
CALCULATE(
    [Voorraad Uitgifte Aantal],
    DATESYTD(Kalender[Datum])
)

// Year-to-date netto mutatie
Voorraad Netto Mutatie YTD =
[Voorraad Ontvangst YTD] - [Voorraad Uitgifte YTD]


// ============================================================================
// FOLDER: Voorraad\6. Magazijn Specifiek
// ============================================================================

// Voorraad in standaard magazijnen (geen projectmagazijnen)
Voorraad Stand Standaard Magazijnen =
CALCULATE(
    [Voorraad Stand Aantal],
    'Voorraad magazijnen'[Projectmagazijn] = "Nee"
)

// Voorraad in projectmagazijnen (OHW gerelateerd)
Voorraad Stand Projectmagazijnen =
CALCULATE(
    [Voorraad Stand Aantal],
    'Voorraad magazijnen'[Projectmagazijn] = "Ja"
)

// Waarde standaard magazijnen
Voorraad Waarde Standaard Magazijnen =
CALCULATE(
    [Voorraad Stand Waarde Kostprijs],
    'Voorraad magazijnen'[Projectmagazijn] = "Nee"
)

// Waarde projectmagazijnen
Voorraad Waarde Projectmagazijnen =
CALCULATE(
    [Voorraad Stand Waarde Kostprijs],
    'Voorraad magazijnen'[Projectmagazijn] = "Ja"
)

// Aantal actieve magazijnen
Magazijnen Aantal Actief =
CALCULATE(
    COUNTROWS('Voorraad magazijnen'),
    'Voorraad magazijnen'[Status] = "Actueel",
    'Voorraad magazijnen'[MagazijnGeblokkeerd] = "Nee"
)

// Aantal locaties per magazijn
Locaties Aantal =
CALCULATE(
    COUNTROWS('Voorraad locaties'),
    'Voorraad locaties'[Status] = "Ja" // Ja = Actueel (historisch_jn = N)
)

// Aantal posities per magazijn
Posities Aantal =
CALCULATE(
    COUNTROWS('Voorraad posities'),
    'Voorraad posities'[Status] = "Actueel"
)


// ============================================================================
// FOLDER: Voorraad\7. KPI Hulpmeasures
// ============================================================================

// Voorraadwaarde geformatteerd (voor card visuals)
Voorraad Waarde Display =
VAR Waarde = [Voorraad Stand Waarde Kostprijs]
RETURN
    IF(
        Waarde >= 1000000,
        FORMAT(Waarde / 1000000, "0.0") & " M",
        IF(
            Waarde >= 1000,
            FORMAT(Waarde / 1000, "0.0") & " K",
            FORMAT(Waarde, "0")
        )
    )

// Indicator voor conditional formatting (rood/groen)
Voorraad Trend Indicator =
VAR MutatieMoM = [Voorraad Mutatie MoM]
RETURN
    IF(MutatieMoM >= 0, 1, -1)

// Bezettingsgraad magazijn (stand vs max capaciteit)
Voorraad Bezettingsgraad =
VAR TotaalMax = SUM('Voorraad posities'[MaximumVoorraad])
VAR TotaalStand = [Voorraad Stand Aantal]
RETURN
    DIVIDE(TotaalStand, TotaalMax, 0)


// ============================================================================
// FOLDER: Voorraad\8. Leverancier Analyse
// ============================================================================

// Ontvangsten per leverancier (via relaties)
Voorraad Ontvangst Per Leverancier =
CALCULATE(
    [Voorraad Ontvangst Aantal],
    USERELATIONSHIP(
        'Voorraad mutaties'[LeverancierRelatieKey],
        Relaties[RelatieKey]
    )
)

// Waarde ontvangsten per leverancier
Voorraad Ontvangst Waarde Per Leverancier =
CALCULATE(
    [Voorraad Ontvangst Waarde Kostprijs],
    USERELATIONSHIP(
        'Voorraad mutaties'[LeverancierRelatieKey],
        Relaties[RelatieKey]
    )
)


// ============================================================================
// EINDE DAX MEASURES
// ============================================================================
